### PR TITLE
Replace cached GSOffset with live calculations

### LINKED ISSUE #2686: GS: MLB Power Pros crash
***PCSX2 version:***
v1.5.0-dev-2671-gca68ddd0d

***PCSX2 options:***
Defaults

***Plugins used:***
GSdx-AVX2, Defaults

***Description of the issue:***
This change introduced a memory leak for all renderers of GSdx in rare cases such as MLB Power Pros.

***How to reproduce the issue:***
Boot the game, find a section with 3D rendering.

***Last known version to work:***
 r1548, introduced in [r1549](https://github.com/PCSX2/pcsx2/commit/83b15dbac0b6069de4a1d7e52364f7839a583fcf)

***PC specifications:***
i5-6600K@4.7GHz, GTX 1070, Windows 10 64-Bit Home.

In GSState.cpp:
```
template<int i> void GSState::ApplyTEX0(GIFRegTEX0& TEX0)
{
	GL_REG("Apply TEX0_%d = 0x%x_%x", i, TEX0.u32[1], TEX0.u32[0]);

	// Handle invalid PSM here
	switch (TEX0.PSM) {
		case 3:
			TEX0.PSM = PSM_PSMT8; // International Star Soccer (menu)
			break;
		default:
			break;
	}

	// even if TEX0 did not change, a new palette may have been uploaded and will overwrite the currently queued for drawing
	bool wt = m_mem.m_clut.WriteTest(TEX0, m_env.TEXCLUT);

	// clut loading already covered with WriteTest, for drawing only have to check CPSM and CSA (MGS3 intro skybox would be drawn piece by piece without this)

	uint64 mask = 0x1f78001c3fffffffull; // TBP0 TBW PSM TW TCC TFX CPSM CSA

	if(wt || PRIM->CTXT == i && ((TEX0.u64 ^ m_env.CTXT[i].TEX0.u64) & mask))
	{
		Flush();
	}

	TEX0.CPSM &= 0xa; // 1010b

	if((TEX0.u32[0] ^ m_env.CTXT[i].TEX0.u32[0]) & 0x3ffffff) // TBP0 TBW PSM
	{
		m_env.CTXT[i].offset.tex = m_mem.GetOffset(TEX0.TBP0, TEX0.TBW, TEX0.PSM);


	}
```

In the bottom if statement: commenting out `		m_env.CTXT[i].offset.tex = m_mem.GetOffset(TEX0.TBP0, TEX0.TBW, TEX0.PSM);` will resolve the memory leak.

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Should fix #2686, please test

The non-cached calculations are pretty fast, but generally not quite as fast as the cached versions.  I haven't noticed any slowdown in anything I've tested, but it might be good for others to test.

Also this makes heavy use of lambdas hoping they'll be inlined, so we should performance test MSVC and make sure it actually does

Finally, we haven't used them much before, so what are people's thoughts on formatting lambdas passed to functions? I went with this (indented like you would the content of a loop):
```cpp
s->m_pages.loopPages([this, s](uint32 page)
{
	s->m_erase_it[page] = m_map[page].InsertFront(s);
});
```
but we could also go with this
```cpp
s->m_pages.loopPages([this, s](uint32 page)
	{
		s->m_erase_it[page] = m_map[page].InsertFront(s);
	});
```
or this
```cpp
s->m_pages.loopPages(
	[this, s](uint32 page)
	{
		s->m_erase_it[page] = m_map[page].InsertFront(s);
	});
```
I personally would like to not go with clang-format's preference of this, it destroys horizontal space
```cpp
s->m_pages.loopPages([this, s](uint32 page)
                     {
                         s->m_erase_it[page] = m_map[page].InsertFront(s);
                     });
```
Same question for locals
```cpp
auto helper = [&](...)
{
};
```
or
```cpp
auto helper = [&](...)
	{
	};
```

### CODE REVIEW

**Comment by seta-san** [comment]
tour de france doesn't have memory leak anymore. memory usage doesn't get much higher than 560mb. characters and other UI elements flicker in and out of existence which is new (incorrect) behavior.

**Comment by seta-san** [comment]
multiframe dump.
https://filebin.net/dham5zxe2g89mb8e

**Comment by tellowkrinkle** [comment]
@seta-san try now

**Comment by seta-san** [comment]
> @seta-san try now

works perfect now.

**Comment by MrPopoJunior** [comment]
Is this fix gonna be included in a dev build of PCSX2?

**Comment by F0bes** [comment]
Once the PR is merged into master, it will be in the latest dev build yes.

File: plugins/GSdx/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -2077,26 +2050,10 @@ void GSTextureCache::SourceMap::RemoveAt(Source* s)
...
+		s->m_pages.loopPages([this, s](uint32 page)
 		{
-			if(uint32 p = s->m_pages_as_bit[i])
-			{
-				auto* m = &m_map[i << 5];
-				const auto* e = &s->m_erase_it[i << 5];
-
-				unsigned long j;
-
-				while(_BitScanForward(&j, p))
```
Comment (iMineLink) [inline plugins/GSdx/Renderers/HW/GSTextureCache.cpp:2089]: This was a micro optimization from greg for reducing the source cache invalidation time with the old page validity bitmap; It might be a good benchmark to compare the time spent in the GSTextureCache::SourceMap::RemoveAt before and after the modifications.

Comment (tellowkrinkle) [reply plugins/GSdx/Renderers/HW/GSTextureCache.cpp:2089]: Hmm the two commits that modified it before were fa1377a8ee5120522a47666fb4416b45fd85c3dd and e58776e0951fd36a8cd0d03eda7df19e19b2386c

fa1377a8ee5120522a47666fb4416b45fd85c3dd looks like it was adding a caching system that's since been replaced, though it does name Champion of Norrath as the game to profile for this section of code

e58776e0951fd36a8cd0d03eda7df19e19b2386c is the one that adds the `_BitScanForward` and doesn't mention what games it's trying to improve

So does anyone have Champion of Norrath (or a gsdump of it) to profile?

Comment (refractionpcsx2) [reply plugins/GSdx/Renderers/HW/GSTextureCache.cpp:2089]: Champions of Norrath is just a Snowblind engine game, so any game using that, for example Baldurs Gate, will probably do.

**Comment by ThatDudeYouMetThatOneTime** [comment]
This build *seems* to have fixed the issue with Remote Control Dandy SF, which would cause the game to crash after about 10 to 15 minutes of playing. In my testing thus far, I have been able to play the game for an hour and 10 minutes without experiencing any crashes. If anyone else would be interested in testing RCD SF with this build as well, and for a longer period of time, please feel free to do so.

**Comment by seta-san** [comment]
> This build _seems_ to have fixed the issue with Remote Control Dandy SF, which would cause the game to crash after about 10 to 15 minutes of playing. In my testing thus far, I have been able to play the game for an hour and 10 minutes without experiencing any crashes. If anyone else would be interested in testing RCD SF with this build as well, and for a longer period of time, please feel free to do so.

ANOTHER KONAMI GAME

**Comment by RedDevilus** [comment]
Ultimate Spider-man doesn't seem to crash anymore even after 30 min, though the game suffers from other problems like texture cache.

**Comment by seta-san** [comment]
this may also effect "Anubis: Zone of Enders"

from 5chan 
658名無しさん＠お腹いっぱい。 (ﾜｯﾁｮｲ 9b62-0pr0)2021/04/06(火) 11:13:37.76ID:+rNq7+UQ0
anubisのメモリリークも解消されますように(May anubis memory leaks be eliminated.)

File: plugins/GSdx/Renderers/HW/GSTextureCache.cpp (hunk 1 above)
Comment (iMineLink) [reply plugins/GSdx/Renderers/HW/GSTextureCache.cpp:2089]: My memory has betrayed me about the git history, sorry. Anyway I tested the beginning of Baldur's Gate: Dark Alliance, and it is even a tad faster now! Great job.

**Comment by tellowkrinkle** [comment]
Speaking of 5ch
> 試したいけどgithub使ったことがなくてやり方が分からない
1. 右上のSign Upのボタンで無料でgithubのアカウントを作ろう。
2. 緑色の✔︎をクリックして、Windows buildの右のDetailsと言うボタンをクリック
image
3. ログインしているならArtifactsが表示される。そこでPCSX2-32bit-pr...をダウンロードする
image
4. 問題があれば[公式Discordサーバー](https://discord.gg/hQ6zH2eJYE)の`#help-windows`チャンネルで聞いてください。日本語で聞いても時間がちょっとかかるが日本語のできる人がきっと手伝うよ

**Review by F0bes — APPROVED** [review]
Tested with Colin McRae Rally 3 and Grand Theft Auto: LCS

Both seem to work fine, CM Rally seemed to be a couple of fps faster
GTA: LCS seemed to be a touch slower 

The difference is very minuscule and could just external factors.

**Comment by atomic83GitHub** [comment]
This PR produces visual glitches on Zone of the enders the 2nd runner demo.

image

**Comment by tellowkrinkle** [comment]
> This PR produces visual glitches on Zone of the enders the 2nd runner demo.

[Send a GSdump please](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump)

**Comment by tellowkrinkle** [comment]
@atomic83GitHub Can you see if the newest build fixes your issue?

**Comment by atomic83GitHub** [comment]
This PR also breaks every single PS1 games played through PS1DRV.

PR:

image

Master:

image

**Comment by kenshen112** [comment]
Does it work in SW mode

**Comment by atomic83GitHub** [comment]
Not in the PR, software behave the same as hardware on that game.

**Comment by RedDevilus** [comment]
True Crime NYC;

Spamming F9 or even one F9, applying GS settings:
Can hardcrash PCSX2


Upscaled:
Available VRAM is very low (-62432288), a crash is expected! Enable conservative buffer allocation or reduce upscaling!
GS OUT OF MEMORY
Which basically makes it run erratic and slow.

This game is so cursed. While Ultimate Spider-Man is fine for me.

**Comment by seta-san** [comment]
le tour de france crashed with this PR when it didn't before the gs merge

**Comment by tellowkrinkle** [comment]
> Available VRAM is very low (-62432288), a crash is expected! Enable conservative buffer allocation or reduce upscaling!

GSOffsets didn't live in VRAM so I would guess this is a different issue

> le tour de france crashed with this PR when it didn't before the gs merge

I tried rebasing against various points in the history between then and now, could you test the tags [gsoffset0, gsoffset1, and gsoffset2 here](https://github.com/tellowkrinkle/pcsx2/tags) and see which (if any) exhibit the issue?

**Comment by seta-san** [comment]
> > Available VRAM is very low (-62432288), a crash is expected! Enable conservative buffer allocation or reduce upscaling!
> 
> GSOffsets didn't live in VRAM so I would guess this is a different issue
> 
> > le tour de france crashed with this PR when it didn't before the gs merge
> 
> I tried rebasing against various points in the history between then and now, could you test the tags [gsoffset0, gsoffset1, and gsoffset2 here](https://github.com/tellowkrinkle/pcsx2/tags) and see which (if any) exhibit the issue?

none of them crashed in tour de france. the highest memory usage i saw was 415mb

**Comment by tellowkrinkle** [comment]
> none of them crashed in tour de france. the highest memory usage i saw was 415mb

Just added 3 more, can you test those?

**Comment by seta-san** [comment]
> > none of them crashed in tour de france. the highest memory usage i saw was 415mb
> 
> Just added 3 more, can you test those?

none of them crashed. #5 memory only went as high as 401mb

**Comment by RedDevilus** [comment]
Best rename prefix `GSdx:` to `GS:`

**Comment by seta-san** [comment]
i also can't get the build i said that crashed to crash again

**Comment by refractionpcsx2** [comment]
Should also fix https://forums.pcsx2.net/Thread-Prince-of-Tennis-games-crashing-issue but I can't test it.

**Comment by nf6429** [comment]
> Should also fix https://forums.pcsx2.net/Thread-Prince-of-Tennis-games-crashing-issue but I can't test it.

Can confirm that it fixes Princes of Tennis: Smash Tennis 2, played 30 and 20 min match with no crashes. Presume it also fixes theteam game, but I'll try that too. Yet again though, another Konami game.

**Review by RedDevilus — APPROVED** [review]

**Comment by Rasiohead91** [comment]
how to install this update on the pcsx2? I am just rookie

**Comment by Mrlinkwii** [comment]
@Rasiohead91 go to https://pcsx2.net/downloads/ and scroll down to where you see 1.7.27XX , if you have any other issues join the discord/ forums  thats linked in the readme :)  ,

**Comment by Rasiohead91** [comment]
> @Rasiohead91 go to https://pcsx2.net/downloads/ and scroll down to where you see 1.7.27XX , if you have any other issues join the discord/ forums thats linked in the readme :) ,

3q very much,and the latest version is the best?

**Comment by RedDevilus** [comment]
> > @Rasiohead91 go to [pcsx2.net/downloads](https://pcsx2.net/downloads/) and scroll down to where you see 1.7.27XX , if you have any other issues join the discord/ forums thats linked in the readme :) ,
> 
> 3q very much,and the latest version is the best?

I would assume having a big ass button would tell you that yes, the latest version is the best.
