### PR TITLE
PINE: fix regressions introduced in #10448

### LINKED ISSUE #10582: [BUG]: PINE stopped working
### Describe the Bug

PINE no longer works in the latest builds. It simply does not connect to PCSX2 anymore. I've narrowed the problem down to version v1.7.5327. It was working fine up to version v1.7.5326, but since v1.7.5327 it does not work anymore.

### Reproduction Steps

- Enable PINE in PCSX2 settings and restart PCSX2
- Launch any game
- Launch PINE and attempt to connect to PCSX2
- PINE gives a connection error

### Expected Behavior

PINE connects to PCSX2

### PCSX2 Revision

v1.7.5420

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 23.04

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by GovanifY**
### Description of Changes
PR #10448 introduced two regressions to PINE:

- Inverted the OOB checks, causing it to return that a packet is unsafe when within bounds
- Used the incorrect type for socket binding, leading to the socket never binding on Windows.

This fixes both regressions

### Rationale behind Changes
PINE was broken

### Suggested Testing Steps
Well a bit late but compile and run the sample client from here: https://projects.govanify.com/govanify/pine

This fixes #10582

### CODE REVIEW

File: pcsx2/PINE.h [hunk 1]
```diff
@@ -189,7 +189,7 @@ class PINEServer
 	 */
 	static inline bool SafetyChecks(u32 command_len, int command_size, u32 reply_len, int reply_size = 0, u32 buf_size = MAX_IPC_SIZE - 1)
 	{
-		return ((command_len + command_size) > buf_size ||
+		return !(bool)((command_len + command_size) > buf_size ||
```
Comment (refractionpcsx2) [inline pcsx2/PINE.h:192]: Update the C style casting to a static_cast please

Comment (GovanifY) [reply pcsx2/PINE.h]: done
