### PR TITLE
DEV9: Fix HDD Response when no HDD is connected

### LINKED ISSUE #10754: [BUG]: FFX International will not boot if you have network settings enabled but no HDD image.
### Describe the Bug

Trying to boot FFX International (Jp) while having Ethernet enabled will cause the game to fail to boot, leaving just a black screen, happens also on windows.
(Basically It won't boot if you have DEV9 enabled without providing any HDD image.)
Screenshot_01312024_192556
You can workaround it by creating or using a HDD raw image, doesn't need to be formatted.
Screenshot_01312024_192657

### Reproduction Steps

1. Enable Ethernet on game properties or globally
2. Try to boot the game.

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.5535

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

### CPU

Ryzen 5 5600

### GPU

Rx 6600

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Correctly reports no device connected when HDD is not enabled

### Rationale behind Changes
The PS2 always reports HDD functionality if you have an expansion bay addon. The device status/control register however reports all bits set (except the reset bit) if the game/program tries to poll it, which will result in it being reported as missing.

### Suggested Testing Steps
Test Final Fantasy X International with Ethernet enabled but HDD disabled

Fixes #10754

### CODE REVIEW

File: pcsx2/DEV9/DEV9.cpp [hunk 1]
```diff
@@ -419,16 +419,18 @@ u16 DEV9read16(u32 addr)
 			return hard;
 
 		case SPD_R_REV_3:
-			if (EmuConfig.DEV9.HddEnable)
-				hard |= SPD_CAPS_ATA;
-			if (EmuConfig.DEV9.EthEnable)
+			// The Expansion bay always says HDD and Ethernet are supported, we need to keep HDD enabled and we handle it elsewhere.
+			// Ethernet we will turn off as not sure on what that would do right now, but no known game cares if it's off.
+			if(EmuConfig.DEV9.EthEnable)
```
Comment (lightningterror) [inline pcsx2/DEV9/DEV9.cpp:424]: Formatting, space after if.

**Review by AmyRoxwell — APPROVED** [review]

**Review by kamfretoz — APPROVED** [review]
