### PR TITLE
Achievements: Harden RetroAchievements Hardcore Compliance

### LINKED ISSUE #13273: [BUG]: Loading a save state while RetroAchievements hardcore mode is enabled should never be possible
### Describe the Bug

Hi, I am an admin over at RetroAchievements 👋 

https://github.com/PCSX2/pcsx2/pull/13271 fixes a major regression that allows PCSX2 users to load a save state while playing in hardcore mode.

As best as I can tell, this fix appears to be a band-aid at the UI level. The emulator itself should enforce that states can't be loaded while hardcore mode is running in the function that loads the states. Otherwise, I fear this issue will keep coming up over and over again.

### Reproduction Steps

See #13271.

### Expected Behavior

The save state loading function itself should block loading states while RetroAchievements hardcore mode is enabled.

### PCSX2 Revision

2.5.160

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by SternXD**
Fixes #13273  
- Fully block save state loading, frame advance, and cheats when Hardcore Mode is active  
- Disable Load State UI buttons while in Hardcore Mode (with an OSD message if bypassed)  
- Standardize OSD warnings for most Hardcore restrictions I could see in VMManager.

Totally up to suggestions with all of this just wanted to try to prevent any issues from happening again. And if you would like me not to remove asking the user if they want to turn off Hardcore let me know (Did this just in case somehow they were able to cheat the UI)

### Description of Changes
This PR enforces stricter RetroAchievements Hardcore compliance by preventing restricted actions both in the UI and at the core level. It also improves consistency in how users are notified through OSD messages.

### Rationale Behind Changes
Previously, users were prompted to disable Hardcore Mode if they attempted a restricted action. This approach possibly allowed people to bypass it. With this change, actions such as loading states, frame advancing, or using cheats are now hard-blocked.

### Suggested Testing Steps
- Enable Hardcore Mode and attempt to:
  - Load a save state (should be blocked with an OSD warning).  
  - Save a state (should still be allowed).  
  - Use frame advance (should be blocked with an OSD warning).  
  - Enable cheats (should be disabled automatically with an OSD warning).  
- Verify that UI elements for restricted actions are disabled while Hardcore Mode is active.  
- Confirm that normal behavior is unaffected when Hardcore Mode is off.  

### Did you use AI to help find, test, or implement this issue or feature?
No

### CODE REVIEW

File: pcsx2-qt/MainWindow.cpp [hunk 1]
```diff
@@ -928,7 +932,7 @@ void MainWindow::restoreStateFromConfig()
 	}
 }
 
-void MainWindow::updateEmulationActions(bool starting, bool running, bool stopping)
+void MainWindow::updateEmulationActions(bool starting, bool running, bool stopping, bool hardcore_mode)
```
Comment (F0bes) [inline pcsx2-qt/MainWindow.cpp]: Is there a benefit to having an additional argument here? Or would having a `const bool hardcore_mode_active = Achievements::IsHardcoreModeActive()` at the top of this function work?
It looks like IsHardcoreModeActive() should be safe to call in any VM state.

Comment (SternXD) [reply pcsx2-qt/MainWindow.cpp]: Alright I have addressed this

**Comment by Serteyf** [comment]
Not a fan of removing the choice to switch to softcore when loading a state in hardcore, it was really useful for practicing no damage bosses on the fly. Can restrictive measure for hardcore compliance be achieved even with the old "do you want to change to softcore?" feature?

**Comment by JordanTheToaster** [comment]
> Not a fan of removing the choice to switch to softcore when loading a state in hardcore, it was really useful for practicing no damage bosses on the fly. Can restrictive measure for hardcore compliance be achieved even with the old "do you want to change to softcore?" feature?

As stated by the retro achievements documentation loading save states is always blocked in hardcore.

image

https://docs.retroachievements.org/general/hardcore-compliance-requirements.html

**Comment by SternXD** [comment]
> Not a fan of removing the choice to switch to softcore when loading a state in hardcore, it was really useful for practicing no damage bosses on the fly. Can restrictive measure for hardcore compliance be achieved even with the old "do you want to change to softcore?" feature?

If you want to use save states then just use Softcore don't be in Hardcore at all.
