### PR TITLE
FSUI: Automatically hide advanced graphics settings

### LINKED ISSUE #11239: [BUG]: Big Picture Mode shows advanced features in Graphics section
### Describe the Bug

With the option to show advanced settings turned off, Big Picture Mode still shows advanced settings in the Graphics section.

### Reproduction Steps

Turn off the option to show advanced settings
Go into BPM and verify that it shows some advanced settings

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

Automatically hide advanced graphics settings on BPM depending on global advanced settings visibility.
Forgot about it when i added the functionality on Qt

image

Closes #11239 

### Rationale behind Changes

Consistency 100

### Suggested Testing Steps

Test the functionality, toggle the global advanced settings option and see if the advanced graphics settings section gets hidden.

### CODE REVIEW

**Comment by kamfretoz** [comment]
Did an oopsie and accidentally sent the PR prematurely, OP has been updated.

**Comment by stenzek** [comment]
Please fix the formatting (use clang-format on the area, or manually indent it)

**Comment by kamfretoz** [comment]
Fixed.

File: pcsx2/ImGui/FullscreenUI.cpp [hunk 1]
```diff
@@ -3912,35 +3912,40 @@ void FullscreenUI::DrawGraphicsSettingsPage()
...
+		DrawToggleSetting(bsi, FSUI_CSTR("Skip Presenting Duplicate Frames"),
+			FSUI_CSTR("Skips displaying frames that don't change in 25/30fps games. Can improve speed, but increase input lag/make frame pacing "
+					  "worse."),
+			"EmuCore/GS", "SkipDuplicateFrames", false);
+		DrawToggleSetting(bsi, FSUI_CSTR("Disable Threaded Presentation"),
+			FSUI_CSTR("Presents frames on the main GS thread instead of a worker thread. Used for debugging frametime issues."),
+			"EmuCore/GS", "DisableThreadedPresentation", false);
+		if (hw_fixes_visible)
+		{
+			DrawIntListSetting(bsi, FSUI_CSTR("Hardware Download Mode"), FSUI_CSTR("Changes synchronization behavior for GS downloads."),
```
Comment (stenzek) [inline pcsx2/ImGui/FullscreenUI.cpp:3929]: This is not a hw fix.

Comment (kamfretoz) [reply pcsx2/ImGui/FullscreenUI.cpp]: Done.
