### PR TITLE
GSdx-d3d: Port max_layer mipmap calculation from opengl, update nvidia d3d hack

### LINKED ISSUE #1026: [Regression] D3D11 renderer adds black lines to bottom and right of the screen
While I was taking screenshots for #1025 to showcase the bug, I noticed that the D3D11 renderer adds very thin black lines on the bottom and right side of the screen, cutting off a bit of the image. This did not happen in 1.2.1 and it does not happen in the D3D9 or OGL renderers.

6x

The lines are actually thicker in native resolution:
native.

### PR DESCRIPTION
**Pull request by lightningterror**
Fixues issue with full mipmapping on D3D11 with textures appearing broken.
Some code still remains to be ported but at least the broken textures issue has been resolved.
Issue #2150 

GSdx-d3d: Update nvidia hack with vendor id detection.
Hack will no longer be active on Intel or AMD gpus.
Close #1026

Commits by: @KrossX

### CODE REVIEW

**Comment by turtleli** [comment]
If the commit is by KrossX then maybe the commit author should be changed to KrossX?

Also, the `ID3D11DeviceContext::Unmap` call takes a subresource parameter. I think that needs to match the subresource number that `ID3D11DeviceContext::Map` was called with?

**Comment by KrossX** [comment]
Indeed, unmap takes subresource too. Totally ignored that. Hmmm... might have to store "layer" somewhere.

File: plugins/GSdx/GSDevice11.cpp [hunk 1]
```diff
@@ -152,6 +154,21 @@ bool GSDevice11::Create(const std::shared_ptr<GSWnd> &wnd)
...
+		IDXGIAdapter *dxa;
+		DXGI_ADAPTER_DESC dxad;
+
+		if(SUCCEEDED(m_dev->QueryInterface(__uuidof(IDXGIDevice), (void**)&dxd)) &&
+			SUCCEEDED(dxd->GetParent(__uuidof(IDXGIAdapter), (void**)&dxa)) &&
+			SUCCEEDED(dxa->GetDesc(&dxad))) {
+			vendor_id_nvidia = dxad.VendorId == 0x10DE;
+		}
+
+		Hack_TopLeft_offset = (!vendor_id_nvidia || UserHacks_disable_NV_hack || spritehack > 0 || isNative) ? 0.0f : -0.01f;
```
[the remark this answers is not in the document]
Comment (lightningterror) [reply plugins/GSdx/GSDevice11.cpp]: Perhaps the entire UserHacks_disable_NV_hack is useless. spritehack kinda does the same thing.

[the remark this answers is not in the document]
Comment (turtleli) [reply plugins/GSdx/GSDevice11.cpp]: ... Didn't you introduce it in the first place? #2145.

[the remark this answers is not in the document]
Comment (lightningterror) [reply plugins/GSdx/GSDevice11.cpp]: I did but now with the vendor lookup it's a bit useless.

File: plugins/GSdx/GSDevice11.cpp [hunk 2]
```diff
@@ -152,6 +151,23 @@ bool GSDevice11::Create(const std::shared_ptr<GSWnd> &wnd)
...
+		IDXGIAdapter *dxa;
+		DXGI_ADAPTER_DESC dxad;
+
+		if(SUCCEEDED(m_dev->QueryInterface(IID_PPV_ARGS(&dxd))) && SUCCEEDED(dxd->GetParent(IID_PPV_ARGS(&dxa))) && SUCCEEDED(dxa->GetDesc(&dxad)))
+		{
+			is_vendor_id_nvidia = dxad.VendorId == 0x10DE;
+		}
+
+		bool is_native = theApp.GetConfigI("upscale_multiplier") == 1;
+		int is_spritehack = theApp.GetConfigB("UserHacks") ? theApp.GetConfigI("UserHacks_SpriteHack") : 0;
```
Comment (turtleli) [inline plugins/GSdx/GSDevice11.cpp]: I made the suggestion to change `isNative` to `is_native` because `isNative` uses camel case whereas `is_native` uses snake case. I did not suggest to add `is_` to all the variables. I'm not sure `is_spritehack` makes that much sense.

Personally I would have written `!nvidia_gpu || native_resolution || spritehack_enabled` because it's more readable to me than `(!is_vendor_id_nvidia || is_spritehack || is_native)`and would have also changed `spritehack_enabled` to a bool and changed the expression to `theApp.GetConfigB("UserHacks") && theApp.GetConfigI("UserHacks_SpriteHack")`.

**Comment by lightningterror** [comment]
@turtleli are you fine with the changes, can I merge this ?

File: plugins/GSdx/GSTexture11.cpp [hunk 3]
```diff
@@ -65,19 +73,24 @@ bool GSTexture11::Map(GSMap& m, const GSVector4i* r, int layer)
...
 		return false;
 	}
 
+	if(layer >= m_max_layer)
+		return false;
+
 	if(m_texture && m_desc.Usage == D3D11_USAGE_STAGING)
 	{
 		D3D11_MAPPED_SUBRESOURCE map;
+		UINT subresource = layer; // ???
```
Comment (turtleli) [inline plugins/GSdx/GSTexture11.cpp]: Comment is useless?

File: plugins/GSdx/GSTexture11.cpp [hunk 4]
```diff
@@ -89,7 +102,10 @@ void GSTexture11::Unmap()
 {
 	if(m_texture)
 	{
-		m_ctx->Unmap(m_texture, 0);
+		UINT subresource = m_layer; // ???
```
Comment (turtleli) [inline plugins/GSdx/GSTexture11.cpp]: Ditto.

File: plugins/GSdx/GSTexture11.h [hunk 5]
```diff
@@ -34,6 +34,11 @@ class GSTexture11 : public GSTexture
 	CComPtr<ID3D11RenderTargetView> m_rtv;
 	CComPtr<ID3D11DepthStencilView> m_dsv;
 
+	bool m_generate_mipmap;
```
Comment (turtleli) [inline plugins/GSdx/GSTexture11.h]: This isn't initialised in the constructor. Actually, I'd suggest removing `m_generate_mipmap` since it currently isn't used.

Apart from that the code looks ok.

**Comment by lightningterror** [comment]
https://github.com/PCSX2/pcsx2/commit/99f1d376a8fc739144c79cfd986c81a7ffad3180 also fixes horizontal lines on Fatal Frame series.
Just dropping this info here so we know.
