### PR TITLE
Misc:Debugger: Support write-only GS priv reads

### LINKED ISSUE #4336: [BUG] Debugger not display correctly HEX values for GS privileged registers
**Describe the bug**

Pcsx2 dev v1.7 - 1163 x86 (offical buildbot), in debugger, going to memory panel  to address 12000000 GS privileged register showing random hex values, in pcx2 v1.6 stable this address show correct hex values; i was testing pcsx2 1.7 dev builds around july 2020 working ok, now lastest builds tested all have this problem.

**GS Settings**
Default options

**Emulation Settings**
Default Options

**GS Window Screenshots**

**System Info (please complete the following information):**
 -   PCSX2 Revision: PCSX2 v1.7.0-dev-1163
 -   OS: Windows 10 x64 official 20H2
 -   CPU: Ryzen 3400g
 -   GPU: Gpu integrated vega 11

**Logs and Dumps**

### PR DESCRIPTION
**Pull request by F0bes**
Fixes #4336 

Introduces a new register category based around GS Privileged registers.

- [x] Supports reading
- [x] Supports writing

Note: The memory view still shows the mirrored CSR values and writing to the registers using the memory view does not work.

### CODE REVIEW

File: pcsx2/GS.h [hunk 1]
```diff
@@ -435,6 +435,7 @@ extern u8   gsRead8(u32 mem);
 extern u16  gsRead16(u32 mem);
 extern u32  gsRead32(u32 mem);
 extern u64  gsRead64(u32 mem);
+extern u128	gsNonMirroredRead(u32 mem);
```
Comment (lightningterror) [inline pcsx2/GS.h:438]: Space instead of tab after u128.

Comment (refractionpcsx2) [inline pcsx2/GS.h:438]: Tabs vs spaces

**Review by tadanokojin — APPROVED** [review]
looks good thanks

**Comment by felixthecat1970** [comment]
nice F0bes, i hope can be merged untill GS merge happens (for me takes time organice this values and i have compressed chds for new builds); also i dont know if can be possible enable a sort of "black, grey" color style for debuger (white color make me eyes tired)

**Comment by F0bes** [comment]
As much as I would like to, I believe that waiting until pcsx2 moves to Qt and away from Wx would be the best time to implement a dark mode, instead of hacking it in now.
