### PR TITLE
PCSX2-WX: Display boot medium, fix shutdown menu behavior and some string updates

### LINKED ISSUE #1620: WX/GUI: Discuss possible string changes
This issue is intended as a continuation of PR #1577 as turtleli suggested. If you'd like to see any strings changed, you can suggest them here

So far we have:
- [x]  Fix "Shutdown" menu state if necessary
- [x]  Change `Iso` to `ISO` (turtleli's suggestion)
- [x]  Resolve boot medium GUI behavior (#1381)
- [x]  Remove `HostFs` from GUI on release builds (user can still edit value via pcsx2_vm)
- [ ]  Reduce string size of gamefix panel help text.
- [x]  ~~Remove tooltip of ``Restore Defaults`` in speedhacks panel.~~ **(done by turtleli)**

### PR DESCRIPTION
**Pull request by ssakash**
**Summary of changes**:

* Fix shutdown menu item behavior (Thanks to @MrCK1 for looking into it)
* Disable Host Filesystem menu item for release builds as it isn't generally useful for endusers.
* Display proper boot medium on the menu items.
* Some string updates, here and there.

~~``[WIP]`` I still need to update https://github.com/PCSX2/pcsx2/commit/80ed0c367f8d46c30aa89fdefd8c93fd0c130bfd at a later time, other than that code is complete.~~ **Done**

Gregory suggested refraction to reduce the gamefix panel help string size, so #1620 could probably be closed after that I guess.

### CODE REVIEW

**Comment by sudonim1** [comment]
Hmm, not sure I agree on host:, it's for homebrew in general and I was just now looking at finishing the work on it so getstat(), dopen() and dread() can be used (catch: the structures for these vary with ioman versions, but this is simpler to deal with than I remembered), which are what break most homebrew.  And besides we use it for running test programs and we kind of need to run tests on release builds....

**Comment by FlatOutPS2** [comment]
You can still enable it through the ini, so you can still use it in release builds.

If we do keep it, we could consider greying out the option when preset is enabled.

**Comment by sudonim1** [comment]
Well it's basically harmless, it doesn't do anything unless a program tries to open a host: path

**Comment by sudonim1** [comment]
Uh I SAY it's harmless but upon reviewing it seems that file writing was added without proper safety in path translation.  That's not harmless at all, for all we know thousands of users could've been rooted.

File: common/include/Utilities/IniInterface.h [hunk 1]
```diff
@@ -70,10 +70,11 @@ class IniInterface
 	void EnumEntry( const wxString& var, T& value, const wxChar* const* enumArray=NULL, const T defvalue=(T)0 )
 	{
 		int tstore = (int)value;
+		int defaultvalue = (int)defvalue;
```
Comment (gregory38) [inline common/include/Utilities/IniInterface.h]: why? To support the enum class? But why did you convert cdvd source to an enum class, actually ?

Comment (ssakash) [inline common/include/Utilities/IniInterface.h]: Well, I remember a previous discussion where you had mentioned to consider using``enum class`` over normal enums at all scenarios to prevent scope/name classes. Also personally, I prefer ``enum class`` over ``enum``. ``( Yes, I noticed the pseudo scope but I still feel enum classes are better)``

Though honestly what's wrong with the modification on ``IniInterface.h``? It should also work for other enums as they have an underlying type of ``int``.

Comment (gregory38) [inline common/include/Utilities/IniInterface.h]: Well, I don't like all those verbose cast, beside it is error-prone on the type.

First, we (you ;) ) need to add a function to ease the cast. Here some example from stack overflow. For the naming, I took `as_int` but there are various possibillities.
```
template <typename Enumeration>
auto as_int(Enumeration const value)
    -> typename std::underlying_type<Enumeration>::type
{
    return static_cast<typename std::underlying_type<Enumeration>::type>(value);
}

template <typename E>
constexpr typename std::underlying_type<E>::type as_int(E e) {
    return static_cast<typename std::underlying_type<E>::type>(e);
}

template <typename E>
constexpr auto as_int(E e) noexcept
{
    return static_cast<std::underlying_type_t<E>>(e);
}
```

Then EnumEntry uses a template type. However you will always cast to an `int` which defeat the purpose of the template. Boolean variable will be stored as int. I'm pretty sure we can find a better solution (SFINAE), basically a template that call EnumEntry(..., as_int(value), ....)

File: pcsx2/gui/MainFrame.cpp [hunk 2]
```diff
@@ -637,35 +639,51 @@ void MainEmuFrame::ApplyCoreStatus()
...
+	SourceLabel[static_cast<uint8_t>(CDVD_SourceType::Iso)] = _("ISO");
+	SourceLabel[static_cast<uint8_t>(CDVD_SourceType::Plugin)] = _("CDVD");
+	SourceLabel[static_cast<uint8_t>(CDVD_SourceType::NoDisc)] = _("BIOS");
+
+	BootIndicator[0][0] = _("Boot");
+	BootIndicator[0][1] = _("Reboot");
+	BootIndicator[1][0] = _(" (f&ull)");
+	BootIndicator[1][1] = _(" (&fast)");
+
+	wxString MenuItemLabel = static_cast<wxString>(BootIndicator[0][ActiveVM]) + " " + static_cast<wxString>(SourceLabel[static_cast<uint8_t>(Source)]);
```
Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: Some languages don't really use spaces (Chinese), so the `" "` shouldn't be placed here. Actually, breaking up a translatable string into multiple parts isn't a great idea - different languages have different word orders.

Also, those casts are unnecessary when you could just do `wxString(whatever)`.

File: common/include/Utilities/IniInterface.h (hunk 1 above)
Comment (ssakash) [inline common/include/Utilities/IniInterface.h]: I'm not sure I fully understand your idea, so basically you want to replace the static casts with a template function call? ``as_int(enum)`` instead of ``static_cast<uint8>(enum)`` to directly cast to the underlying type of the enum?

File: pcsx2/gui/MainFrame.cpp (hunk 2 above)
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: > Some languages don't really use spaces (Chinese), so the " " shouldn't be placed here. 

I see, didn't know you were from China. I thought you were from UK based on your wordings on replies but guess I was wrong :P 

> Actually, breaking up a translatable string into multiple parts isn't a great idea - different languages have different word orders.

Fair enough, I'll fix it ASAP along with the ``" " `` thing on few translations.

**Comment by ssakash** [comment]
FWIW, I'm not around a build environment right now. I'll probably handle these changes on Sunday, if anyone wants to get this merged before that time, feel free to add commits to add the changes suggested by turtleli and Gregory.

 I have opened this branch on the PCSX2 repo so you guys should be able to push changes on it.

File: pcsx2/gui/MainFrame.cpp (hunk 2 above)
Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: > I see, didn't know you were from China. I thought you were from UK based on your wordings on replies but guess I was wrong :P

Last I checked I was from the UK. XD

My second language does happen to be Chinese though (Cantonese/Traditional Chinese).

File: pcsx2/gui/MainFrame.cpp [hunk 3]
```diff
@@ -437,13 +437,15 @@ MainEmuFrame::MainEmuFrame(wxWindow* parent, const wxString& title)
...
-		wxEmptyString, wxITEM_CHECK);
+	if(IsDebugBuild || IsDevBuild)
+		m_menuSys.Append(MenuId_EnableHostFs,	_("Enable &Host Filesystem"),
+			wxEmptyString, wxITEM_CHECK);
 
 	m_menuSys.AppendSeparator();
 
 	m_menuSys.Append(MenuId_Sys_Shutdown,	_("Shut&down"),
 		_("Wipes all internal VM states and shuts down plugins."));
+	m_menuSys.FindItem(MenuId_Sys_Shutdown)->Enable(false);
```
Comment (MrCK1) [inline pcsx2/gui/MainFrame.cpp]: So I know it's not great to run external programs with PCSX2; but I've ran FRAPS with PCSX2 all the time (as an FPS meter) and I've never had any issues until now.  SuperVU fails to allocate memory if the First Time Wizard is run while a FRAPS process is active. After running the First Time Wizard, the plugins are shutdown right before virtual memory mapping occurs (if you reopen the .exe, this doesn't happen)
	```Shutdown DEV9 and so on``` ...
```Plugins shutdown successfully```
```Reserving memory for recompilers...```
```SuperVU0 Recompiler Cache: host memory @ 0x0E800000 -> 0x0F000000 is unavailable; attempting to map elsewhere...```
```SuperVU1 Recompiler Cache: host memory @ 0x0F000000 -> 0x0F800000 is unavailable; attempting to map elsewhere...```
	```CPU provider error:```
	```Virtual memory map failed while reserving 'SuperVU1 Recompiler Cache':```
	```SuperVU failed to allocate virtual memory below 256MB.```

Do you think this is related to any changes in this PR? I ran the FTW with an older build/FRAPS running; and had no problems with the sVU rec. It would be good to find out if other programs cause this as well, so we don't have any issues in the upcoming stable release.

Comment (MrCK1) [inline pcsx2/gui/MainFrame.cpp]: OK, sounds good ;)

**Comment by ssakash** [comment]
Updated the commit to add a template function for enumeration casts and integrated the strings into a single part as suggested by turtleli.

**Comment by FlatOutPS2** [comment]
It seems like VS2013 compilation is failing. :P

**Comment by ssakash** [comment]
Oh, I think I understood why VS2013 compilation is failing now. It seems VS2013 doesn't support ``constexpr`` https://msdn.microsoft.com/en-us/library/hh567368.aspx :/

**Comment by ssakash** [comment]
So, there are two options - let's remove support for VS2013 **(or)** drop the template idea casting of enumeration classes? ``constexpr`` is mandatory at this case as we need compile time constants for the array subscripts.

Honestly I'm in favor of dropping VS2013 if it prevents us from using new features like ``constexpr`` , ``noexcept`` and * **insert bunch of other cool features** *.

**Comment by refractionpcsx2** [comment]
Well 2013 is still current, so I'm against dropping support for that until VS 2016/2017 is out of beta. So maybe comment it out for now with a comment about using that once 2013 is dropped and for now drop the template idea.

**Comment by gregory38** [comment]
@refractionpcsx2 I'm not sure what you mean by beta but I think it is RC (and VS2017).
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

However, I will prefer to wait an official release.

**Comment by avih** [comment]
I'm also with 2013. Can't get myself to register with MS only to be able to compile with 2015...

**Comment by refractionpcsx2** [comment]
> However, I will prefer to wait an official release.

That's what I mean, I want to wait for the completely stable release before we jump in to it.

> I'm also with 2013. Can't get myself to register with MS only to be able to compile with 2015...

Well, you might have to soon :P

**Comment by gregory38** [comment]
@ssakash Where do you need compile time constant exactly ?

**Comment by ssakash** [comment]
> @ssakash Where do you need compile time constant exactly ?

As I said earlier,
> constexpr is mandatory at this case as **we need compile time constants for the array subscripts**.

Here's a list of the errors produced when ``constexpr`` is removed from the function.
```
.\..\gui\MainFrame.cpp(643): error C2131: expression did not evaluate to a constant
1>  ..\..\gui\MainFrame.cpp(643): note: failure was caused by non-constant arguments or reference to a non-constant symbol
1>  ..\..\gui\MainFrame.cpp(643): note: see usage of 'TotalSources'
1>..\..\gui\MainFrame.cpp(645): error C2131: expression did not evaluate to a constant
1>  ..\..\gui\MainFrame.cpp(645): note: failure was caused by non-constant arguments or reference to a non-constant symbol
1>  ..\..\gui\MainFrame.cpp(645): note: see usage of 'TotalSources'
1>..\..\gui\MainFrame.cpp(647): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(648): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(649): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(651): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(652): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(653): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(654): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(655): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(656): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(657): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(658): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(659): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(660): error C3863: array type 'const wxChar *[TotalSources]' is not assignable
1>..\..\gui\MainFrame.cpp(665): error C2664: 'void wxMenuItem::SetItemLabel(const wxString &)': cannot convert argument 1 from 'const wxChar *[TotalSources]' to 'const wxString &'
1>  ..\..\gui\MainFrame.cpp(665): note: Reason: cannot convert from 'const wxChar *[TotalSources]' to 'const wxString'
1>  ..\..\gui\MainFrame.cpp(665): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>..\..\gui\MainFrame.cpp(669): error C2664: 'void wxMenuItemBase::SetHelp(const wxString &)': cannot convert argument 1 from 'const wxChar *[TotalSources]' to 'const wxString &'
1>  ..\..\gui\MainFrame.cpp(669): note: Reason: cannot convert from 'const wxChar *[TotalSources]' to 'const wxString'
1>  ..\..\gui\MainFrame.cpp(669): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>..\..\gui\MainFrame.cpp(673): error C2664: 'void wxMenuBase::Insert(size_t,int,const wxString &,const wxString &,bool)': cannot convert argument 3 from 'const wxChar *[TotalSources]' to 'const wxString &'
1>  ..\..\gui\MainFrame.cpp(673): note: Reason: cannot convert from 'const wxChar *[TotalSources]' to 'const wxString'
1>  ..\..\gui\MainFrame.cpp(673): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>..\..\gui\MainFrame.cpp(675): error C2664: 'void wxMenuItem::SetItemLabel(const wxString &)': cannot convert argument 1 from 'const wxChar *[TotalSources]' to 'const wxString &'
1>  ..\..\gui\MainFrame.cpp(675): note: Reason: cannot convert from 'const wxChar *[TotalSources]' to 'const wxString'
1>  ..\..\gui\MainFrame.cpp(675): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

Only compile time constants can be used for declaring an array's size.

**Comment by ssakash** [comment]
Wait, _**what the heck?**_ So all I need to do is just replace a single instance of ``enum_cast`` with ``static_cast`` and there should be no problem as the array is the only thing which needs ``constexpr``. why the heck didn't I do just do that then? I'm an idiot! -_-

File: pcsx2/gui/MainFrame.cpp [hunk 4]
```diff
@@ -636,35 +638,49 @@ void MainEmuFrame::ApplyCoreStatus()
...
+	MenuItemLabels[0][0][enum_cast(CDVD_SourceType::Iso)]    = _("Boot ISO (f&ull)");
+	MenuItemLabels[0][1][enum_cast(CDVD_SourceType::Iso)]    = _("Boot ISO (&fast)");
+	MenuItemLabels[1][0][enum_cast(CDVD_SourceType::Iso)]    = _("Reboot ISO (f&ull)");
+	MenuItemLabels[1][1][enum_cast(CDVD_SourceType::Iso)]    = _("Reboot ISO (&fast)");
+	MenuItemLabels[0][0][enum_cast(CDVD_SourceType::Plugin)] = _("Boot CDVD (f&ull)");
+	MenuItemLabels[0][1][enum_cast(CDVD_SourceType::Plugin)] = _("Boot CDVD (&fast)");
+	MenuItemLabels[1][0][enum_cast(CDVD_SourceType::Plugin)] = _("Reboot CDVD (f&ull)");
+	MenuItemLabels[1][1][enum_cast(CDVD_SourceType::Plugin)] = _("Reboot CDVD (&fast)");
+	MenuItemLabels[0][0][enum_cast(CDVD_SourceType::NoDisc)] = _("Boot BIOS");
+	MenuItemLabels[1][0][enum_cast(CDVD_SourceType::NoDisc)] = _("Reboot BIOS");
```
Comment (refractionpcsx2) [inline pcsx2/gui/MainFrame.cpp]: Does it matter too much? This isn't time critical code, afterall.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: Well, it's not optimal, and I think using switches and ifs would be nicer and have the additional benefit of not having to enum cast every single thing.

Comment (refractionpcsx2) [inline pcsx2/gui/MainFrame.cpp]: I agree a switch would be nicer.

Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: > Maybe it'd be better not to use an array? This code does 13 translation lookups, but only uses up to 3 of the strings.

Maybe an array with static storage class so that the string lookup is done only once for each of them?

Don't really love the switch-case idea as I'd have to later duplicate that string's value on the insert function's argument.

File: pcsx2/gui/MainFrame.cpp [hunk 5]
```diff
@@ -636,35 +638,49 @@ void MainEmuFrame::ApplyCoreStatus()
...
-			cdvd2->SetHelp(_("Reboot using fast BOOT (skips splash screens)"));
-		}
-		else
-		{
-			cdvd2->SetItemLabel(_("Boot CDVD (&fast)"));
-			cdvd2->SetHelp(_("Use fast boot to skip PS2 startup and splash screens"));
-		}
-	}
+	if(!cdvd2)
+		cdvd2 = m_menuSys.Insert(1, MenuId_Boot_CDVD2, MenuItemLabels[ActiveVM][1][enum_cast(Source)]);
```
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: > It'd be better to not create the menu item in the no disc case if it doesn't already exist since it'll just get destroyed later.

IIRC, I added a ``Source!= CDVD_SourceType::Nodisc`` check on that ``if()`` before which ended up with the whole GUI freezing so didn't really bother with that and was too lazy to look into it.

>Also, assertions will fail in debug mode in the no disc case since a menu item is being created with no label.

Passing a string with blank spaces should be good then, I assume the array had it as a null character since it was left out of initialization.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: It really isn't so difficult. This:
```
wxMenuItem *cdvd_fast = menubar.FindItem(MenuId_Boot_CDVD2);
if (g_Conf->CdvdSource == CDVD_SourceType::NoDisc) {
	if (cdvd_fast)
		m_menuSys.Destroy(cdvd_fast);
} else {
	wxString label;
	wxString help_text;
	if (ActiveVM) {
		if (g_Conf->CdvdSource == CDVD_SourceType::Iso)
			label = _("Reboot ISO (&fast)");
		else
			label = _("Reboot CDVD (&fast)");
		help_text = _("Reboot using fast boot (skips splash screens)");
	} else {
		if (g_Conf->CdvdSource == CDVD_SourceType::Iso)
			label = _("Boot ISO (&fast)");
		else
			label = _("Boot CDVD (&fast)");
		help_text = _("Use fast boot to skip PS2 startup and splash screens");
	}

	if (cdvd_fast == nullptr) {
		m_menuSys.Insert(1, MenuId_Boot_CDVD2, label, help_text);
	} else {
		cdvd_fast->SetItemLabel(label);
		cdvd_fast->SetHelp(help_text);
	}
}
```
works for me. I didn't need to create and destroy an item that doesn't get used. I also didn't need to use an array and spam casts.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: I prefer my version - it's more obvious to me what labels and help messages are being used in each case.

Your array code is dependent on enum order. And I don't think checking for an empty label is a great way of expressing "We don't want a fast boot menu item when No Disc is selected". I'm not sure the static will work if the language is changed BTW - I don't know whether the pointed to memory will go out of scope or not, I haven't checked. (The menu language also won't change after changing the language, but that applies to quite a bit of the other translated parts of the GUI as well).

> (Though it should probably be changed for variable naming consistency)

Change if necessary - some of the GUI files use N different naming conventions which is a PITA, so I just used that convention (FWIW the naming isn't all that inconsistent when you only look at the rest of the function).

Comment (refractionpcsx2) [inline pcsx2/gui/MainFrame.cpp]: @turtleli your version looks better, however you have absolutely no "boot fast" options.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: Sure, my version is longer, but it's also safer. It doesn't assume specific enum values so you avoid ever having to bugfix like a415d59e2f9e36c92c218073709d540c03a57a0e. The safety is worth the extra lines.

Comment (refractionpcsx2) [inline pcsx2/gui/MainFrame.cpp]: But that commit adds the enums where they were missing? I don't get your point there.

I understand your issue with Enums, but unless that stuff needs to change at some point to add new options etc, it shouldn't be an issue.

Comment (refractionpcsx2) [inline pcsx2/gui/MainFrame.cpp]: oh yes, sorry I see it now.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: BTW, there may be other ways of writing the code that we haven't considered - `std::map` could possibly work too.

File: pcsx2/gui/MainFrame.cpp [hunk 6]
```diff
@@ -584,19 +587,66 @@ void MainEmuFrame::OnActivate( wxActivateEvent& evt )
 }
 // ----------------------------------------------------------------------------
 
+static void GetMenuItemLabel(MenuIdentifiers Id, wxString* label)
```
Comment (gregory38) [inline pcsx2/gui/MainFrame.cpp]: It would be so much better to directly return the string. Beside it would remove the various break and `{}` in the case.

File: pcsx2/gui/MainFrame.cpp [hunk 7]
```diff
@@ -636,35 +686,45 @@ void MainEmuFrame::ApplyCoreStatus()
...
+	{
+		wxString label;
+		std::map<CDVD_SourceType, wxString> help_text;
+		help_text.insert(std::pair<CDVD_SourceType, wxString>(CDVD_SourceType::Iso, _("Boot the VM using the current ISO source media")));
+		help_text.insert(std::pair<CDVD_SourceType, wxString>(CDVD_SourceType::Plugin, _("Boot the VM using the current CD/DVD source media")));
+		help_text.insert(std::pair<CDVD_SourceType, wxString>(CDVD_SourceType::NoDisc, _("Boot the VM without any source media")));
+		GetMenuItemLabel(fullboot_id, &label);
+
+		cdvd_full->SetItemLabel(label);
+		cdvd_full->SetHelp(help_text.at(Source));
```
Comment (gregory38) [inline pcsx2/gui/MainFrame.cpp]: Why not a switch case ? Or a bunch of if/elseif.

File: pcsx2/gui/MainFrame.cpp [hunk 8]
```diff
@@ -584,19 +587,66 @@ void MainEmuFrame::OnActivate( wxActivateEvent& evt )
 }
 // ----------------------------------------------------------------------------
 
+static void GetMenuItemLabel(MenuIdentifiers Id, wxString* label)
+{
+	const CDVD_SourceType Source = g_Conf->CdvdSource;
+	const bool ActiveVM = SysHasValidState();
```
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: ``ActiveVM`` is no longer needed as we removed the ``reboot`` option. Just a left over from my older code where the function was also initializing strings for the reboot menu item labels.

File: pcsx2/gui/MainFrame.cpp (hunk 6 above)
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: Fine, IIRC I made it call by reference for some reason but no clue why.

File: pcsx2/gui/MainFrame.cpp (hunk 7 above)
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: Probably because the code will take up more lines?

File: pcsx2/gui/MainFrame.cpp (hunk 6 above)
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: > It would probably be better to just use the switch directly instead of placing the switch in a function.

I'm not keen on separating it from a dedicated function, it looks much cleaner to handle the menu item labels naming separately and helps to avoid congesting up the code in ``MainEmuFrame::ApplyCoreStatus()``.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: Well, I think less time is used to determine what label and help text is used in:
```
if (wxMenuItem *cdvd_full = menubar.FindItem(fullboot_id)) {
	switch (Source) {
	case CDVD_SourceType::Iso:
		cdvd_full->SetItemLabel("Boot ISO (f&ull)");
		cdvd_full->SetHelp(_("Boot the VM using the current ISO source media"));
		break;
	case CDVD_SourceType::Plugin:
		cdvd_full->SetItemLabel("Boot CDVD (f&ull)");
		cdvd_full->SetHelp(_("Boot the VM using the current CD/DVD source media"));
		break;
	case CDVD_SourceType::NoDisc:
		cdvd_full->SetItemLabel("Boot BIOS");
		cdvd_full->SetHelp(_("Boot the VM without any source media"));
		break;
	default:
		pxAssert(false);
	}
}
```
than in:
```
if (wxMenuItem *cdvd_full = menubar.FindItem(fullboot_id))
{
	wxString label = GetMenuItemLabel(fullboot_id);
	std::map<CDVD_SourceType, wxString> help_text;
	help_text.insert(std::make_pair(CDVD_SourceType::Iso, _("Boot the VM using the current ISO source media")));
	help_text.insert(std::make_pair(CDVD_SourceType::Plugin, _("Boot the VM using the current CD/DVD source media")));
	help_text.insert(std::make_pair(CDVD_SourceType::NoDisc, _("Boot the VM without any source media")));

	cdvd_full->SetItemLabel(label);
	cdvd_full->SetHelp(help_text.at(Source));
}
```
where the help text is more or less immediately known, but you have then navigate to SetMenuItemLabel to determine what label is being used:

```
if (Id == MenuId_Boot_CDVD)
{
	switch (Source)
	{
	case CDVD_SourceType::Iso:    return _("Boot ISO (f&ull)");
	case CDVD_SourceType::Plugin: return _("Boot CDVD (f&ull)");
	case CDVD_SourceType::NoDisc: return _("Boot BIOS");
	default:
		pxAssert(false);
	}
}
```
YMMV

Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: > but you have then navigate to SetMenuItemLabel to determine what label is being used:

I think you mean ``GetMenuItemLabel()``? It's literally just one line before ``MainEmuFrame::ApplyCoreStatus()`` and I don't see how navigating to a function to view it's content is a hard thing. I would prefer to separate these label string initialization to a separate function to reduce the mess in  ``MainEmuFrame::ApplyCoreStatus()`` as stated earlier.

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: It requires less time (as I said before) and less thinking to understand the switch version IMO. But let's just disagree on this.

**Comment by turtleli** [comment]
Oops, didn't realise I created a merge conflict. Anyway, reviewed, I still think just using local switches is preferable instead of map + switch in separate function, but I'm not going to stop a merge if others think it's okay.

**Comment by ssakash** [comment]
> Oops, didn't realise I created a merge conflict.

 "**What turtleli actually thinks**"

``Haha, you deserve that merge conflict for not inclining to my request on using ifs/switch. Mwahahaha!``

:P

**Comment by turtleli** [comment]
**"What turtleli actually thinks"**

> I do not comprehend. ApplyCoreStatus() only enables/disables menu items and sets their labels and help text. Is a helper function needed for getting the labels when the function is simple enough? I do not comprehend.

;)

**Comment by turtleli** [comment]
@gregory38 @refractionpcsx2 I'll leave the decision to you ;)

**Comment by gregory38** [comment]
@turtleli which decision ?

**Comment by gregory38** [comment]
A switch case is better than a map. @ssakash could you update it please.

By the way what do you think of `s/CDVD_SourceType/CDVD_Source/` ? Enum name feels rather long.

**Comment by turtleli** [comment]
Yeah, it was the decision to merge or not - I did test the code and it did work fine, but I disagreed on the separate function and map.

**Comment by ssakash** [comment]
> A switch case is better than a map. @ssakash could you update it please.

Guess I'm outnumbered here, changed it to ``switch-case`` as turtleli suggested.

> By the way what do you think of s/CDVD_SourceType/CDVD_Source/ ? Enum name feels rather long.

Well, the original name of the enum was ``CDVD_SourceType`` and personally I have no plans to change it unless it's necessary to be changed for some sort of reason, also we use these sort of naming in other places at GSdx. ``(GPURendererType, GSRendererType, stateType)``

Maybe it could be reduced for typing convenience but honestly the current name seems rather fine to me.

File: pcsx2/gui/MainFrame.cpp [hunk 9]
```diff
@@ -645,31 +643,65 @@ void MainEmuFrame::ApplyCoreStatus()
...
-			cdvd->SetItemLabel(_("Reboot CDVD (f&ull)"));
-			cdvd->SetHelp(_("Hard reset of the active VM."));
+		case CDVD_SourceType::Iso:
+			label = _("Boot ISO (&fast)");
+			break;
+		case CDVD_SourceType::Plugin:
+			label = _("Boot CDVD (&fast)");
+			break;
+		case CDVD_SourceType::NoDisc:
+			break; // Fast boot menu item is destroyed when no disc is selected.
```
Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: Hmm. Coverity might complain about this case since it can't actually be reached.

File: pcsx2/gui/MainFrame.cpp [hunk 10]
```diff
@@ -643,35 +643,66 @@ void MainEmuFrame::ApplyCoreStatus()
...
+		case CDVD_SourceType::Iso:
+			cdvd_full->SetItemLabel(_("Boot ISO (f&ull)"));
+			cdvd_full->SetHelp(_("Boot the VM using the current ISO source media"));
+			break;
+		case CDVD_SourceType::Plugin:
+			cdvd_full->SetItemLabel(_("Boot CDVD (f&ull)"));
+			cdvd_full->SetHelp(_("Boot the VM using the current CD/DVD source media"));
+			break;
+		case CDVD_SourceType::NoDisc:
+			cdvd_full->SetItemLabel(_("Boot BIOS"));
```
Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: One last thing: Perhaps make the shortcut key `t` for the full/bios boot cases?

File: pcsx2/gui/MainFrame.cpp [hunk 11]
```diff
@@ -465,13 +465,13 @@ MainEmuFrame::MainEmuFrame(wxWindow* parent, const wxString& title)
 	m_menuCDVD.Append( GetPluginMenuId_Settings(PluginId_CDVD), _("Plugin &Menu"), m_PluginMenuPacks[PluginId_CDVD] );
 
 	m_menuCDVD.AppendSeparator();
-	m_menuCDVD.Append( MenuId_Src_Iso,		_("&Iso"),		_("Makes the specified ISO image the CDVD source."), wxITEM_RADIO );
```
Comment (ssakash) [inline pcsx2/gui/MainFrame.cpp]: *sigh* I missed the instance of ``Iso`` in line [464](https://github.com/PCSX2/pcsx2/pull/1651/files#diff-1d6e5cd2c2b8d912c67d623d8e73d31dR464).

Comment (turtleli) [inline pcsx2/gui/MainFrame.cpp]: There's Iso in pcsx2/gui/AppRes.cpp line 66 as well.
