### PR TITLE
GS/HW: Improve Clear, Copy and offset Z behaviour

### LINKED ISSUE #12725: [BUG]: GPU Renderer. Some shedders are not processed.
### Describe the Bug

The game **Toro to Kyuujitsu** does not correctly describe the lighting shedder.

### Reproduction Steps

Play normally. Shadows are not portrayed normally when free play is available.

### Expected Behavior

Shadows are displayed correctly.

### PCSX2 Revision

v2.3.372

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7-10700K

### GPU

RTX 3060 12G

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

Software
Image
Auto(Vulkan HW)
Image

### Logs & Dumps

GSdump
[snaps.zip](https://github.com/user-attachments/files/20447215/snaps.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Improves detection of double half clears both vertically and horizontally, 16bit clears with 32bit textures, and fixes up offset Z on rt in rt draws.

### Rationale behind Changes
The first issue was where the framebuffer was pushed right up against the zbuffer and they were cleared at the same time, being misinterpreted as a double half clear, making a 896 pixel high buffer, which then causer problems with trying to write Z to the same target as the render target in Monster Lab, then making a mess.

Fixing this exposed another problem where it didn't know about horizontal double half clears not being detected unless a target already existed, so gave that a better heuristic.

Toro to Kyuujitsu does 32bit clears for 16bit targets, and also some funky offset Z behaviour, so this fixes those up.

### Suggested Testing Steps
Test Monster Lab, Area 51, MLB 11 The Show and Toro to Kyuujitsu
Other games that came up in the dump run (but no visual differences):
F1 Career Challenge
Ghost Master - The Gravenville Chronicles
Harry Potter and the Goblet of Fire
Project Snowblind
Shadow Hearts
Shox
Star Wars - Battlefront II
Tomb Raider Legend
Transformers Armada - Prelude to Energon/Transformers Special Edition

### Did you use AI to help find, test, or implement this issue or feature?
No.

Fixes #12725

Monster Lab:
Master:
Monster Lab_SLUS-21838_20250624214146_frame02622
PR:
Monster Lab_SLUS-21838_20250624214146_frame02622

Toro to Kyuujitsu:
Master:
image
PR:
image

Area 51 slight fix (Look at the shadow of the guy in the top right, I recommend zooming in):
Master:
image
PR:
image

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -2672,10 +2672,37 @@ void GSRendererHW::Draw()
...
+		if (const_color != 0 && (const_color >> 16) == (const_color & 0xFFFF))
+		{
+			const int get_next_ctx = m_env.PRIM.CTXT;
+			const GSDrawingContext& next_ctx = m_env.CTXT[get_next_ctx];
+
+			if (next_ctx.FRAME.FBP == m_cached_ctx.FRAME.FBP && (next_ctx.FRAME.PSM & 0x3) == PSMCT16 && !(m_cached_ctx.FRAME.PSM & 0x2))
+			{
+				GL_CACHE("Clear 16bit with 32bit");
+
+				if(next_ctx.FRAME.FBW == (m_cached_ctx.FRAME.FBW * 2))
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: Space after if.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 2]
```diff
@@ -3633,47 +3661,33 @@ void GSRendererHW::Draw()
...
-						}
-						if (width_diff)
-						{
-							const int adjust = std::min(width_diff, (horizontal_offset - z_horizontal_offset));
-							sRect.z += static_cast<float>(adjust) / static_cast<float>(ds->m_unscaled_size.x);
-							dRect.z += adjust;
-						}
-					}
-					else
+					if(restricted_copy)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: Here too.

**Review by JordanTheToaster — APPROVED** [review]
