### PR TITLE
GS/HW: Optimize source sizes when using CLAMP_CLAMP

### LINKED ISSUE #13705: [BUG]: D.C.I.F. ~Da Capo~ Innocent Finale Transition screen effect sub 10 fps in vulkan.
### Describe the Bug

This game opening effect when pressing start in hardware mode really slow
https://youtu.be/LCIJcnzh-HM?t=32

### Reproduction Steps

1. Press start on main menu

### Expected Behavior

Should run like software mode which runs at full speed.

https://github.com/user-attachments/assets/171c8564-a0de-43ed-8962-83955822173d

### PCSX2 Revision

v2.5.385

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Bazzite

### CPU

5800x

### GPU

3060 ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Optimises source sizes when using CLAMP_CLAMP. Improves performance by a bit in D.C.I.F Da Capo Innocent Finale during a screen transition.

Fixes #13705 

image

### Rationale behind Changes
10 fps is unacceptable for a simple screen transition may also speed up other games.

### Suggested Testing Steps
Test any games that use the hash cache heavily or that use paltex or estimate texture region and make sure they don't regress visually or performance wise.

### Did you use AI to help find, test, or implement this issue or feature?
No

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -1094,8 +1095,24 @@ __ri static GSTextureCache::Source* FindSourceInMap(const GIFRegTEX0& TEX0, cons
 			// When fixed tex0 is used, we must find a matching region texture. The base likely
 			// doesn't contain to the correct region. Bit cheeky here, avoid a logical or by
 			// adding the invalid tex0 bit in.
-			if (((s->m_region.bits | fixed_tex0) != 0) && s->m_region.bits != region.bits)
-				continue;
+			
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp]: Small nitpick, remove the extra empty rows.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 2]
```diff
@@ -1094,8 +1095,24 @@ __ri static GSTextureCache::Source* FindSourceInMap(const GIFRegTEX0& TEX0, cons
...
+			if (((s->m_region.bits | fixed_tex0) != 0))
+			{
+				const bool is_clamped = CLAMP.WMS == CLAMP_CLAMP && CLAMP.WMT == CLAMP_CLAMP;
+				if (is_clamped && s->m_region.GetMinX() == 0 && s->m_region.GetMinY() == 0)
+				{
+					GSVector4i read_region = GSVector4i(0, 0, read_area.z, read_area.w);
+					GSVector4i region_area = GSVector4i(s->m_region.GetMinX(), s->m_region.GetMinY(), s->m_region.HasX() ? s->m_region.GetMaxX() : (1 << s->m_TEX0.TW), s->m_region.HasY() ? s->m_region.GetMaxY() : (1 << s->m_TEX0.TW));
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp]: These two can be const.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 3]
```diff
@@ -9060,39 +9060,58 @@ bool GSRendererHW::OI_BlitFMV(GSTextureCache::Target* _rt, GSTextureCache::Sourc
...
+		const int tw = tex->m_unscaled_size.x;
+		int th = tex->m_unscaled_size.y;
 
 		// Compute the Bottom of texture rectangle
 		pxAssert(m_cached_ctx.TEX0.TBP0 > m_cached_ctx.FRAME.Block());
 		const int offset = (m_cached_ctx.TEX0.TBP0 - m_cached_ctx.FRAME.Block()) / m_cached_ctx.TEX0.TBW;
 		GSVector4i r_texture(r_draw);
 		r_texture.y -= offset;
 		r_texture.w -= offset;
+		int new_height = std::max(r_texture.w, th);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: This too.

**Comment by F0bes** [comment]
![https://www.reactiongifs.us/wp-content/uploads/2013/08/clamps_futurama.gif]

**Comment by F0bes** [comment]
I hate GH mobile
