### PR TITLE
GS/HW: Fix temp z and clear detection regression

### LINKED ISSUE #12965: [BUG]: Tales of Destiny (Director's Cut) - Battle End Transitions Broken since v2.3.275
### Describe the Bug

Whenever finishing a battle in ToD, the screen slides to and from black when cutting from the battle scene to battle results. This effect is seemingly broken in versions `2.3.275` and onwards' HW renderer (Vulkan/OGL), where the screen instead abruptly flashes black.

FWIW, the version in question seems to be when *RT in RT* was implemented, so I set *Manual Hardware Renderer Fixes* on and tried reproducing the bug with all variations of the *Texture Inside RT* combobox, and the bug occurs regardless of what fixes are or aren't applied.

### Reproduction Steps

1. Go into any battle.
2. Win said battle; observe the awkward black frames being inserted where they shouldn't be.

### Expected Behavior

Should look the same as in `v2.3.274`.

### PCSX2 Revision

v2.5.28

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

AMD Ryzen 5 5600X

### GPU

NVIDIA GeForce RTX 3060ti

### GS Settings

Upscaling: 6x Native (No difference)
Anti-Blur: On (No difference)
Disable Interlace Offset: On (No difference)

### Emulation Settings

Enable Multithreaded VU1: On

### GS Window Screenshots

Video demonstration of this effect - while recorded with the Translation Patch (v1.5), this still applies to an unpatched original copy of ToD:DC.
`v2.3.274`
https://github.com/user-attachments/assets/4b28b9b1-da84-4137-8e0e-213555f05475

`v2.3.275+`
https://github.com/user-attachments/assets/10ca7296-a949-437a-96be-124abf5d36da

### Logs & Dumps

[ToDDC GSdump.zip](https://github.com/user-attachments/files/21048856/ToDDC.GSdump.zip)

### LINKED ISSUE #12966: [BUG]: Time Crisis 3 - Graphical Regressions when *Texture Inside RT* is enabled
### Describe the Bug

Since `v2.3.275`, Time Crisis 3 has exhibited some noticeable graphical issues with default GS fixes:
 - Obvious banding in various geometry
 - Effects layering issues
 - Two-player split screen exhibits seizure-inducing levels of 3D geometry flickering on/off.

...and since `v2.3.353`, some more issues have cropped up, namely that the 3rd rolling demo (one of the sniper stages) has **the entire screen flickering gray** when unscoped and within the scope view, with some extra weird banding/corruption issues happening in addition, alongside the aforementioned layering issues with e.g. the spotlights.

These issues do not appear when *Manual Hardware Renderer Fixes* is enabled and *Texture Inside RT* is set to *Disabled (Default)* for this game.

### Reproduction Steps

1. Start the game.
2. Wait for any of the first three rolling demos to start, observe the graphical inconsistencies when *Texture Inside RT* is enabled or disabled (enabling will cause certain aforementioned graphical anomalies to be temporarily fixed until the game loads the next demo)

### Expected Behavior

Default *Texture Inside RT* fix setting should appear stable like when it's forcibly disabled?

### PCSX2 Revision

v2.5.28

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

AMD Ryzen 5 5600X

### GPU

NVIDIA GeForce RTX 3060ti

### GS Settings

Upscaling: 6x Native (No difference)
Anti-Blur: Enabled (No difference)
Disable Interlace Offset: Enabled (No difference)
Apply No-Interlacing Patches: Enabled (No difference)

### Emulation Settings

Enable Multithreaded VU1: Enabled

### GS Window Screenshots

Example of banding (Demo 1/Stage 1: Scene 1):
Image

Example of graphical corruption in Demo 3:
Image

### Logs & Dumps

[tc3_demo1_banding-GSdump.zip](https://github.com/user-attachments/files/21049069/tc3_demo1_banding-GSdump.zip)

[tc3_demo3_scopeCorruption-GSdump.zip](https://github.com/user-attachments/files/21049073/tc3_demo3_scopeCorruption-GSdump.zip)

[tc3_demo3_sceneFlicker-GSdump.zip](https://github.com/user-attachments/files/21049080/tc3_demo3_sceneFlicker-GSdump.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Fixes an issue with temporarily offset Z and a clear misdetection.

### Rationale behind Changes
Offset Z in Time Crisis 3 was detecting a channel shuffle (which was technically correct) and not copying the Z correctly to the new position, it now properly detects this situation.

Tales of Destiny does 2 triangles across the screen to do a cool effect at the end of of a battle, but this was being detected as a clear with quad. The code now checks for at least one shared vertex in this case.

From here on the GT3 demo (possibly the full game) may require high blending if it doesn't already to stop the left/right buttons in the car select from flickering. This was an issue before RT in RT but due to the false clear, it kind of "fixed" it.

### Suggested Testing Steps
Test Tales of Destiny and Time Crisis 3 (visible in menu demos).  Can also check Black, Burnout 3, GT 3, MGS 3, Tekken Tag, as they show up in the results.

### Did you use AI to help find, test, or implement this issue or feature?
No

Fixes #12966
Fixes #12965

Tales of Destiny:
Master:
image
PR:
image

Time Crisis 3 (There was also some stripes which are now also gone):
Master:
image
PR:
image

### CODE REVIEW

File: pcsx2/GS/GSState.cpp [hunk 1]
```diff
@@ -2972,6 +2972,22 @@ bool GSState::TrianglesAreQuads(bool shuffle_check)
 		}
 		else if (m_index.tail == 6)
 		{
+			bool shared_vert_found = false;
```
Comment (TJnotJT) [inline pcsx2/GS/GSState.cpp:2975]: Not specifically related to the issue being fixed here, but could the logic of trianglesarequads be simplified a bit? One approach that might work:

1. Check if each pair of tris forms a quad. As long as their x/y coords lie on exactly 2 values (as already checked) and their right angle corner points are diagonal from each other, this should hold. Tellowkrinkle made a function for finding triangle corner points that is in this PR: https://github.com/PCSX2/pcsx2/pull/12813.
2. Then check if the rectangles formed are tightly packed in a grid. For example, could be done by looking at all the top-left corners of each quad and making sure they lie on a grid with equal spacing.

Just some thoughts though maybe it is something for a separate PR.

Comment (refractionpcsx2) [reply pcsx2/GS/GSState.cpp:2975]: That would be great, if games weren't complete pains in the neck. But also the code already kinda does this, just not the bit I modified.

By all means if you think it can be improved you can try, but it will need thorough dump runs to check it.

Comment (TJnotJT) [reply pcsx2/GS/GSState.cpp:2975]: Ok, I see. I may try to do write some tests to check the edges cases.

**Comment by TJnotJT** [comment]
GS dump run with Vulkan:

PR:
00418_f00001_fr1_01180_C_32
Master:
00418_f00001_fr1_01180_C_32
The UI elements appear a bit fainter in PR. See on left just under "color selection sign" and on right yellow arrow. Not sure which is correct. File: GT3DemoCorrupt.gs.xz. OGL is the same. In DX11 master looks same as attached PR.

PR:
01659_f00002_fr1_00000_C_32
Master:
01659_f00002_fr1_00000_C_32
The lighting on truck appears to be improved in PR. See just right of speedometer on bottom left. Dump: Big.Mutha.Truckers.gs.xz. Same in OGL and DX11 also.

**Comment by refractionpcsx2** [comment]
As I mentioned in the OP, GT3 will need High blending.

As for that Big Mutha Truckers dump, it's missing Tex in RT because it's a very old dump.

**Comment by TJnotJT** [comment]
My mistake, you did mention that. The GT3 dumps looks good with high blending.
