### PR TITLE
EE: Force sync on EE Timer read

### LINKED ISSUE #4486: [BUG] Major League Baseball 2K10 -> Game freeze at the copyright screen
Describe the bug
As soon as the game boot, it will show the copyright screen, the game then stop there

To reproduce
Simply start the game , which will freeze in less than 30 seconds

Expected behavior
On a real Playstation 2, the game will boot and proceed as normal

GS Settings
Default GS Settings

Emulation Settings
Default settings and Software Mode

System Info (please complete the following information):

PCSX2 Revision: dev-1283
OS: Windows 10 (lastest update)
CPU: i7-8700K
GPU: NVIDIA GeForce RTX 2060 Super

Logs and Dumps

[majorleaguebaseball2k10.txt](https://github.com/PCSX2/pcsx2/files/6613246/majorleaguebaseball2k10.txt)

The last four row of the log are also shown here.

[VC IRX module][ VCMain ] IOP system memory Free:0x97400(619520) , MaxBlock:0x96700(616192)
padman: *** VBLANK OVERLAP ***
padman: *** VBLANK OVERLAP ***
	[VC IRX module][ VCMain ] IOP system memory Free:0x5f400(390144) , MaxBlock:0x5e700(386816)
padman: *** VBLANK OVERLAP ***

Other information

A personal dump of a Brand new (factory sealed) Major League Baseball 2K10

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Forces the EE JIT/Interpreter to do an event test to update counters on read to properly deal with interrupt states.

### Rationale behind Changes
the ESPN games do this while checking the EE Timer 0 as part of a routine that extends its length to 32bits by using an interrupt to increment a value by the counter maximum amount and add it on.  Problem being if this happens during this update, it causes a race condition deadlock if the counters are not properly updated, meaning the new value will loop (after overflow) but the interrupt won't have incremented the extension, so the new value is smaller than the old value, causing an underflow. 

This PR makes the EE JIT/Interpreter update its state on counter read to catch up with this state.

### Suggested Testing Steps
make sure any of the ESPN games work fine, mainly the ones with a 2K# date.

### Did you use AI to help find, test, or implement this issue or feature?
No

Fixes long standing (but patched around) bug with ESPN games.

Fixes #4486

### CODE REVIEW

**Comment by ghost** [comment]
Is it possible this might fix other voodoo, or timing issues?

**Comment by refractionpcsx2** [comment]
In theory, yes, but in practice? no clue :P

**Comment by ghost** [comment]
I was hoping it'd fix #10622 but after testing, even now, after so long, the timer still gives out the same value (0x18). Hope it fixes other games though.

**Comment by F0bes** [comment]
I thought this PR originally did an event test whenever the `sync` instruction was run. Am I mistaken, or was that not needed.

**Comment by refractionpcsx2** [comment]
> I thought this PR originally did an event test whenever the `sync` instruction was run. Am I mistaken, or was that not needed.

It did, but that felt a bit too much of a specific scenario, so instead it does it whenever a timer is read, specifically.

File: pcsx2/x86/ix86-32/iR5900LoadStore.cpp [hunk 1]
```diff
@@ -107,9 +107,14 @@ static void recLoad(u32 bits, bool sign)
 		alloc_cb = []() { return _allocX86reg(X86TYPE_GPR, _Rt_, MODE_WRITE); };
 
 	int x86reg;
+	bool needs_flush = false;
 	if (GPR_IS_CONST1(_Rs_))
 	{
 		const u32 srcadr = g_cpuConstRegs[_Rs_].UL[0] + _Imm_;
+
+		if (bits <= 32 && (srcadr & 0xFFFFE0000) == 0x10000000)
```
Comment (F0bes) [inline pcsx2/x86/ix86-32/iR5900LoadStore.cpp:116]: Can you add a comment here? ~~I would~~ Someone would have to look at the mapping or git blame to know what / why this is here.
`// Event test on timer reads. Fixes a stability issue in various ESPN games` or something

Adding it to the interpreter is up to you.

Comment (refractionpcsx2) [reply pcsx2/x86/ix86-32/iR5900LoadStore.cpp:116]: sure

Comment (refractionpcsx2) [reply pcsx2/x86/ix86-32/iR5900LoadStore.cpp:116]: done
