### PR TITLE
3rdparty/imgui: General fixes

### LINKED ISSUE #11699: [BUG]: Weird rectangle appearing when holding the Square button on controller if frametime graph is displayed
### Describe the Bug

When holding the Square button on a controller while a game is running a grey rectangle appears in the middle of the screen + some white lines around the frametime graph. Only tested with XInput controllers, it's also not happening with a keyboard.

image

If I click with my mouse on the PCSX2 Window the bug won't show again during that game session, however it will happen again if I close the game and launch it again.

The bug only happens when the frametime graph is currently shown on-screen.

From my tests, it started happening with v2.1.75 (#11680), I can't reproduce the issue in v2.1.74.

#11693 fixes the issue for Jordan, but I grabbed the artifact from the GH Actions and I also built PCSX2 locally with that PR changes but for me it's still happening, which is why I still wanted to open an issue about it.

### Reproduction Steps

1. Have a XInput controller (but it might work with SDL or DInput, I haven't tested).
2. Enable the frametime graph from the OSD menu.
3. Start a game and hold Square button.

### Expected Behavior

_No response_

### PCSX2 Revision

v2.1.83

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Fixes the nav menu appearing when holding square and also removes some obsolete functions.

Fixes #11699 

### Rationale behind Changes
Tidy code is good code also the nav menu is annoying.

### Suggested Testing Steps
Make extra sure this time that everything works and no strange boxes take over your screens.

### CODE REVIEW

File: 3rdparty/imgui/include/imgui_internal.h [hunk 1]
```diff
@@ -1357,8 +1357,8 @@ typedef ImBitArray<ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN>    ImBitAr
 #define ImGuiKey_NavKeyboardTweakFast   ImGuiMod_Shift
 #define ImGuiKey_NavGamepadTweakSlow    ImGuiKey_GamepadL1
 #define ImGuiKey_NavGamepadTweakFast    ImGuiKey_GamepadR1
-#define ImGuiKey_NavGamepadActivate     ImGuiKey_GamepadFaceDown
-#define ImGuiKey_NavGamepadCancel       ImGuiKey_GamepadFaceRight
+#define ImGuiKey_NavGamepadActivate     (g.IO.ConfigNavSwapGamepadButtons ? ImGuiKey_GamepadFaceRight : ImGuiKey_GamepadFaceDown)
```
Comment (F0bes) [inline 3rdparty/imgui/include/imgui_internal.h:1360]: I don't see a place where we set ConfigNavSwapGamepadButtons. Is this actually used anywhere?

Comment (JordanTheToaster) [reply 3rdparty/imgui/include/imgui_internal.h:1360]: Yeah it's used under where I put the comment about the macros being used.

**Review by kamfretoz — APPROVED** [review]
LGTM, fixes the square box issue
image
