### PR TITLE
GS/HW: Implement moves in texture cache

### LINKED ISSUE #1725: Devil May Cry: Upper-third of screen is blurred (regression)
***PCSX2 version:***
v1.5.0-dev-1744-g8fecd35

#1613 (gsdx tc: miss a set scaling call) introduced the regression

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults, GSdx OGL, 4x Native

***Description of the issue:***
During 3D portions of the game, the upper-third of the screen is blurry. You can see the separation in screenshot. The issue is only visible in resolutions above Native.

***How to reproduce the issue:***
Boot the game, start a level and look at the top of the screen.

***Last known version to work:***
v1.5.0-dev-1426-g3b73393

***PC specifications:***
i5-6600k@4.7Ghz, GTX 1070 SC, Windows 10 64-bit Insider Build 14986

dmcregression

### LINKED ISSUE #3169: Armored Core: Last Raven (NTSC-U - SLUS_213.38) - Blurry graphics during missions (in HW mode).
***PCSX2 version:***
1.7.0 dev 1040 (also tried 1.6.0 and 1.4.0. No difference)

***PCSX2 options:***
Defaults, 'Safe' preset. I've also tried different settings to no effect. Speedhacks were disabled during testing.

***Plugins used:***
GSdx, SPU2-X, LilyPad, cdvdGigaherz, the rest are null plugins.

***Plugin settings:*** 
Tested GSdx in both OpenGL and Direct3D 11 modes, HW and SW. Tried all sort of settings combinations to no effect. "Preload Frame Data" hack enabled to avoid HW mode blackscreen.

GS dump: [gsdx_20191205031754.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/3925432/gsdx_20191205031754.gs.xz.zip)

***Description of the issue:***
The game simply looks wrong during missions in HW mode. The entire screen is a blurry mess. Graphics are perfectly fine while in menus (no blur + proper upscaling). This issue doesn't show up in the previous game in the series (Armored Core: Nexus). Image comparison included, screenshots taken in OpenGL HW mode.

gsdx_20191204205752 gsdx_20191204204827
HW mode upscaling working properly in menus, no blur present:
gsdx_20210317131417

***How to reproduce the issue:***
Enter any mission, battle or AC Test mode.

***Last known version to work:***
Never worked right, as far as I'm aware.

***PC specifications:***
CPU: AMD Ryzen 5 2600
GPU: Geforce GTX 1060 6GB
OS: Windows 7 Ultimate SP1 x64

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Currently, for local memory moves, we invalidate all hardware targets, and then do the copy on the CPU. Which works great, but it's slow (readbacks), and you lose upscaling.

This PR implements a subset of the possible move cases in the texture cache (when SBP+DBP exist in the target list, and the sizes/psm match). Which is enough for games such as Armored Core, Devil May Cry, Bust-A-Move Dance Summit 2001.

### Rationale behind Changes

More brr, more upscaling.

### Suggested Testing Steps

Test games which use GS moves.

Fixes #1725
Fixes #3169

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -1047,6 +1047,68 @@ void GSTextureCache::InvalidateLocalMem(const GSOffset& off, const GSVector4i& r
...
+
+	// Invalidate any sources that overlap with the target (since they're now stale).
+	InvalidateVideoMem(m_renderer->m_mem.GetOffset(DBP, DBW, DPSM), GSVector4i(dx, dy, dx + w, dy + h), false);
+	return true;
+}
+
+GSTextureCache::Target* GSTextureCache::GetExactTarget(u32 BP, u32 BW, u32 PSM) const
+{
+	auto& rts = m_dst[GSLocalMemory::m_psm[PSM].depth ? DepthStencil : RenderTarget];
+	for (auto it = rts.rbegin(); it != rts.rend(); ++it) // Iterate targets from LRU to MRU.
```
Comment (iMineLink) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1102]: Here you may want to search starting from the MRU, so from the beginning of the list; Hopefully it won't make a difference though.

**Comment by Dreadmoth** [comment]
The motion blur effect on zoom level transitions in Champions of Norrath and Champions: Return to Arms now upscales nicely:

Master (5x Native):
crta_master

PR (5x Native):
crta_pr

The fade to black on entering/exiting the inventory is similarly improved.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp (hunk 1 above)
Comment (stenzek) [reply pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1102]: Good point, I just grabbed it from the lookup functions.

But yeah, if we have more than one target with a matching BP, BW and PSM, we probably have bigger problems..

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 2]
```diff
@@ -1047,6 +1047,68 @@ void GSTextureCache::InvalidateLocalMem(const GSOffset& off, const GSVector4i& r
...
+	// but so far haven't seen anything which needs it.
+	if (GSConfig.Renderer == GSRendererType::DX11 || GSConfig.Renderer == GSRendererType::DX12)
+	{
+		if (GSLocalMemory::m_psm[SPSM].depth || GSLocalMemory::m_psm[DPSM].depth)
+			return false;
+	}
+
+	// Look for an exact match on the targets.
+	GSTextureCache::Target* src = GetExactTarget(SBP, SBW, SPSM);
+	GSTextureCache::Target* dst = GetExactTarget(DBP, DBW, DPSM);
```
Comment (iMineLink) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1070]: Now that I'm thinking of it, it dst does not exist in cache you can just copy src, change the BP/BW fields and add it to the relevant list. Also it might be needed to check that no overlap exist between the src and dst GS memory regions...but... that would be an evil move.

Comment (stenzek) [reply pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1068]: Good suggestion, but for the record, I wanted to keep this change as small as possible in case of regressions. Could be worth doing in the future, but I don't think there's any cases where it does happen currently (at least in the ones I tested, it was moves *inside* an existing target).

Also keep in mind that the missing-from-cache cache would only happen once, with the previous frame's target being around for the next frame. So we'd probably want to drop the old target in such a case.

**Comment by washingleavesandthensome23-434** [comment]
very freakin nice my guys ....no idea how long ive been waiting for this for dmc1, big thanks !
