### PR TITLE
GSdx: Palette management refactor and fix (v2)

### LINKED ISSUE #2702: Tales of Legendia - Segfaults with CRC level 'None' or 'Minimum'
***PCSX2 version:***
https://github.com/PCSX2/pcsx2/commit/3d6921d9ca05ac0b5a637a6c5163110e3133d0a8

***PCSX2 options:***
`Automatic CRC Level: None or Minimum`

***Plugins used:***
`GSdx (GCC 8.2.0 SSE2/AVX) 1.1.0 [libGSdx]`

The legacy GSdx is unaffected.
`GSdx (GCC 8.2.0, SSE2) 1.0.0 [libGSdx-legacy-1.0.0]`

***Description of the issue:***

When playing `Tales of Legendia` with CRC level `none` or `minimum` pcsx2 will segfault consistently in certain parts of the games. For example:

* When loading a save to the world map.
* When opening `Config > Video (GS) > Plugin Settings...` during emulation of a field map.
* When stopping emulation.
* When just running the game for some period of time.

With the first method sometimes this assert will be shown before it proceeds to crash.
```
/tmp/SBo/pcsx2/common/src/Utilities/Linux/LnxHostSys.cpp(70) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    MTGS
    Condition: false
    Message:   Unhandled page fault @ 0x000000a7

Stacktrace:
[00] wxSizer::Add(wxWindow*, wxSizerFlags const&)
[01] __kernel_rt_sigreturn                       
[02] 0x0xd79ac67d     
```
I tried to use GDB, but I am having difficulty actually proceeding into the game and then capturing the crash. Please see issue https://github.com/PCSX2/pcsx2/issues/1806 for further discussion.

***How to reproduce the issue:***

Here are two methods which seem to reproduce it consistently.

1. Set the `Automatic CRC Level` to `None`.
2. Start `Tales of Legendia`.
3. Proceed to a field map such as the start of the game before the first town.
4. Open `Config > Video (GS) > Plugin Settings...`
5. pcsx2 should segfault.

Or

1. Set the `Automatic CRC Level` to `None`.
2. Start `Tales of Legendia`.
3. Load the a save game to the world map.
4. It should crash shortly after loading and presenting the world map with very wrong colors.

Here is a memory card containing a save file.
http://0x0.st/sU54.xz

***Last known version to work:***

I bisected this.
```
$ git bisect bad
42aee34482d9bf251b4a1f296d5341bab57166db is the first bad commit
commit 42aee34482d9bf251b4a1f296d5341bab57166db
Author: iMineLink <iminelink@gmail.com>
Date:   Tue Nov 13 19:22:13 2018 +0100

    GSdx-TC: Use PaletteMap also when 8-bit texture is disabled by caching only clut copies. (#2681)
    
    Enabled caching of clut copies with PaletteMap also in the case 8-bit texture is disabled, which is the default (on #2344 the caching of clut copies and palette textures was done only when 8-bit texture was enabled).
    Brings moderate speedups ~10% in the most concitated parts of the ZoE2 Anubis benchmark, but may improve performance in all the cases when there are many Source objects created with clut copies to be stored.
    The quality of the comments has been improved to better highlight the mechanics of the caching system.

:040000 040000 5a852542b45865779aaf07be2158d3a48337b095 4d5780b97ae675680cac629a2a85493cb29027be M	plugins
```
42aee34482d9bf251b4a1f296d5341bab57166db

***PC specifications:***
OS: `Slackware64-current`
Compiler: `gcc-8.2.0`
mesa: https://github.com/mesa3d/mesa/commit/9367514524f70faad99c721bac92339c8ff8bad9

### LINKED ISSUE #2736: OpenGL regression in Burnout 3 (draw distance is black)
***PCSX2 version:***
v1.5.0-dev-2714

***PCSX2 options:***
All defaults.

***Plugins used:***
All defaults. 

***Description of the issue:***
In the OpenGL Hardware plugin, there is a new issue where geometry in the distance is completely black. 

Here is a screenshot: 
image

***How to reproduce the issue:***
It is pretty evident in any race. That race in the screenshot is Silver Lake. 

***Last known version to work:***
Seems to work fine in dev-2484.

***PC specifications:***
Tested on Windows 7/i7-3770/GTX 1050Ti and Windows 10/i5-7200U/GT 960M, both affected

### PR DESCRIPTION
**Pull request by AlessandroVetere**
Refactor and fix palette management.

1. Improve ICO hack by using palette cache for depth sampling, removing only point of creation of palette textures outside TC (removes conditional deletion of `Source::m_palette` in `~Source()`),
2. Purge comments,
3. Reformat parts of the code,
4. Centralize CLUT comparison logic in `PaletteKey` equality operator,
5. Fix and rationalize palette texture or clut copy attachment and update with respect to pre-`PaletteMap` behavior,
6. Make `PaletteMap` capable of managing at the same time Palette with and without `GSTexture`,
7. Handle possible case of `Source` lookup hit with `psm.pal` value changed.

Closes #2702 , Closes #2736 and prevents possible similar regressions.

### CODE REVIEW

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp [hunk 1]
```diff
@@ -1451,13 +1454,13 @@ GSTextureCache::Source* GSTextureCache::CreateSource(const GIFRegTEX0& TEX0, con
...
 			src->m_texture = m_renderer->m_dev->CreateTexture(tw, th, Get8bitFormat());
-			src->m_should_have_tex_palette = true;
-			// Palette (Palette object, clut copy and palette texture) is going to be attached in Source lookup code exploiting initial condition !src->m_clut
+			AttachPaletteToSource(src, psm.pal, true);
 		}
 		else {
 			src->m_texture = m_renderer->m_dev->CreateTexture(tw, th);
-			// by default: src->m_should_have_tex_palette = false;
-			AttachPaletteToSource(src, psm.pal, false); // Attach only Palette object and clut copy
+			if (psm.pal > 0) {
```
Comment (AlessandroVetere) [inline plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: This change is most likely what fixed #2702, as we were malloc'in 0 bytes clut arrays without the `psm.pal > 0` check.

Comment (orbea) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: No, that change doesn't seem to affect `Tales of Legendia`.

Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Oh strange. Could you please try again the last version of PR plugin to see if the regression is still fixed? I applied some modifications to make things easier to manage.

Comment (orbea) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Yes, I applied the whole PR as a patch to master and both `Tales of Legendia` and `Tales of the Abyss` still seem fixed with and without `8 bits textures`.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp [hunk 2]
```diff
@@ -2116,11 +2116,13 @@ std::size_t GSTextureCache::PaletteKeyHash::operator()(const PaletteKey &key) co
...
-	ASSERT(lhs.pal == rhs.pal); // By design, each map SHOULD contain only PaletteKey with the same pal value
-	
-	uint16 pal = lhs.pal;
-	uint16 palette_size = pal * sizeof(uint32);
-	return GSVector4i::compare64(lhs.clut, rhs.clut, palette_size);
+	if (lhs.pal != rhs.pal) {
+		return false;
+	}
+
+	ASSERT((lhs.pal & 15) == 0);
```
Comment (gregory38) [inline plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Why the assert ? It doesn't make any sense here

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp [hunk 3]
```diff
@@ -1451,6 +1452,7 @@ GSTextureCache::Source* GSTextureCache::CreateSource(const GIFRegTEX0& TEX0, con
 		{
 			src->m_texture = m_renderer->m_dev->CreateTexture(tw, th, Get8bitFormat());
 			src->m_should_have_tex_palette = true;
+			AttachPaletteToSource(src, psm.pal, true);
```
Comment (gregory38) [inline plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Not related to this line of code in particular.
Is there a possibilities that we attach the palette twice ?
We attach in Create Src and in LookUp Src.

Maybe it could be possible to avoid the compare64 check in lookup ? It isn't critical if current code is safe but potentially a bit "slower".

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp [hunk 4]
```diff
@@ -2077,6 +2077,13 @@ GSTexture* GSTextureCache::Palette::GetPaletteGSTexture() {
 	return m_tex_palette;
 }
 
+void GSTextureCache::Palette::UploadClut() {
+	if (!m_tex_palette) {
+		m_tex_palette = m_renderer->m_dev->CreateTexture(256, 1);
+		m_tex_palette->Update(GSVector4i(0, 0, m_pal, 1), m_clut, m_pal * sizeof(m_clut[0]));
```
Comment (gregory38) [inline plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Is it expected that UploadClut will upload only once ?

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 3 above)
Comment (gregory38) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: it feels like the last commit, isn't it ?

**Comment by gregory38** [comment]
It is much better with small commits. Small comments but it is fine for me. It requires a couple of final tests. And it should be fine.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 3 above)
Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: You are right, this commit alone introduces double palette attachment (as it invalidates the current fast path), but with the last commit the fast path is managed in an easier way and it always avoid double attachment in Create Src and LookUp Src.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 4 above)
Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Yes because the clut content for a given `Palette` is copied at object creation and never changed, so also the palette need only to be uploaded once (possibly lazy upload)

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 2 above)
Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Yeah maybe you are right there is already the ASSERT in the `GSVector4i::compare64`, I can remove it if needed

Comment (gregory38) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: yes because this assert belong to compare64 not this function.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 3 above)
Comment (gregory38) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: I think the best will be to do a single commit
* that attach palette in all cases / as soon as possible
* the bool new_source of latest commit (which I think is the fix to double attachment)

This way we have an atomic (and logical) commit.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 4 above)
Comment (gregory38) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: In this case, UploadClut could have a better name. Create/Initialize (once) vs Upload (can be repeated). 

You can also reduce the size of the texture. 256 is too big for small m_pal.

Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Ok for name. As for Tex size, IIRC I tried and creating smaller textures lead to various errors. Will test again.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 3 above)
Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: I agree with that, the intermediate commit breaks fast path so it's better to squash them in one.

File: plugins/GSdx/Renderers/Common/GSTextureCache.cpp (hunk 4 above)
Comment (AlessandroVetere) [reply plugins/GSdx/Renderers/Common/GSTextureCache.cpp]: Yeah creating texture with 16 as width breaks the plugin (both dx and ogl), while for big pal (256) it is good (as hardcoded in there). However it would be an interesting enhancement to create smaller textures for this use case.

**Comment by lightningterror** [comment]
The crash mentioned in https://github.com/PCSX2/pcsx2/issues/2702 is reproducible in variety of dumps/games tested, oddly enough the crash is reproducible if a game utilizes depth, now since dx11 got depth convert as well it's also reproducible there.

@gregory38 if the PR has small nitpicks to be taken care of I suggest we postpone them for another PR, this one is rather really important and I'd like to see it merged as fast as possible.

**Comment by gregory38** [comment]
No need to rush man.

Code is fine for me. It can be merged.

**Comment by lightningterror** [comment]
> No need to rush man.

I don't like crash regressions :smile:
