### PR TITLE
GS-HW: Expand width on output read if DBX offset

### LINKED ISSUE #4409: [BUG] FMV display issue at the right of the screen in some games.
**Describe the bug**
In some games "such as the demo of DK decks and FX" FMV sequences can appear wrongly distorted in hardware mode when using any resolution higher than native.

image

**To Reproduce**
Load DJ deck and FX or drakengard and look an FMV in hardware mode when upscaling.

**Expected behavior**
The FMV should have display issues like in software.

**System Info (please complete the following information):**
PCSX2 Revision: v1.7.0-dev-1202-g721253bf4
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
[DJ decks and FX FMV right of the screen issue.zip](https://github.com/PCSX2/pcsx2/files/6401353/DJ.decks.and.FX.FMV.right.of.the.screen.issue.zip)

### LINKED ISSUE #6813: [BUG]: Cutscenes are broken with hardware rendering in The Sniper 2 (Europe)
### Describe the Bug

All cutscenes have graphical garbage on the right side of the screen with hardware renderers. Software looks fine.

Sniper 2_ The_SLES-51623_20220810072820

Sniper 2_ The_SLES-51623_20220810072933

### Reproduction Steps

Play the game with any hardware renderer and watch the opening cutscene.

### Expected Behavior

The cutscene shouldn't be broken. 

### PCSX2 Revision

pcsx2-v1.7.3137-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

All settings default

### Emulation Settings

All settings default

### GS Window Screenshots

_No response_

### Logs & Dumps

[Sniper 2_ The_SLES-51623_20220810072933.zip](https://github.com/PCSX2/pcsx2/files/9294777/Sniper.2_.The_SLES-51623_20220810072933.zip)

### LINKED ISSUE #6884: [BUG]: Flashing intro FMV in JPN version of The Thing in hardware mode.
### Describe the Bug

The intro video of "Yuusei kara no Buttai X - Episode II" (SLPM-62245), the Japanese version of "The Thing", seems to displays every second frame as black, resulting in some very serious flashing, especially during the display of the Konami logo with its white background.

### Reproduction Steps

Load the game in hardware mode, the copyright info displays normally, then the intro FMV starts with the Konami logo and flashes.

Multiframe GS Dump of part of the copyright info (not FMV) and the transition to the flashing intro video (zipped, extract first)
**EPILEPSY WARNING - FLASHING LIGHTS**
[Yuusei kara no Buttai X - Episode II_SLPM-62245_20220820124017.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/9388035/Yuusei.kara.no.Buttai.X.-.Episode.II_SLPM-62245_20220820124017.gs.xz.zip)

The flashing occurs only during the first loop of the GS dump and is fixed afterwards.

In the full game, the flashing stops when switching from hw to sw and back to hw mode or when changing graphics settings from the rendering tab, like Internal Resolution, Texture Preloading etc.
The flashing does not stop when changing settings from the Display tab like Deinterlacing, VSync etc.

When taking a GS Dump of the video, the moment when the video starts to play has to be included for the flashing to occur.

This GS dump is part of the same intro video as above, but it does not flash in the GS dump (it does flash in the game when played from the beginning). It does display smearing on the right side in hw mode though.
[Yuusei kara no Buttai X - Episode II_SLPM-62245_20220820133456.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/9388045/Yuusei.kara.no.Buttai.X.-.Episode.II_SLPM-62245_20220820133456.gs.xz.zip)

### Expected Behavior

Video should not flash and look the same as software mode.

### PCSX2 Revision

v1.7.3238

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i9-9900k

### GPU

RTX 2080ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Expands the target read on the merge circuit when there is an offset to the framebuffer. Also update the TBP0 on double buffer change and mis detect, which caused flickering on FMVs (not all FMVs that flicker have this same issue, unfortunately)

### Rationale behind Changes
wasn't accounting for this, causing the right side of the screen to stretch in FMV's. As mentioned in previous PR's, the hardware renderer reads the entire texture, then cuts it up in the merge circuit, so we need to over-read.

Also bad pointer matches are bad.

### Suggested Testing Steps
test FMV's which went stretchy on the right side or flickering.

Effect is seen on (for example)

Chaos Field (Also mentioned in #6813)
DJ Decks ( Fixes #4409 )
Mashed - Fully Loaded
Meiwaku Seijin Panic Maker
Sniper 2 ( Fixes #6813 )
Taiko no Tatsujin: Tatacon de Dodon ga Don
Taiko no Tatsujin: Doki! Shinkyoku Darake no Haru Matsuri
Taiko no Tatsujin: Appare Sandaime
Taiko no Tatsujin: Waku Waku Anime Matsuri
Worms 4 Mayhem
Yamasa Digi World 4 & Yamasa Digi World 4 DX
Yuusei kara no Buttai X ( Fixes #6884 )
Yuusei kara no Buttai X - Episode II

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -251,8 +251,13 @@ GSTexture* GSRendererHW::GetOutput(int i, int& y_offset)
 	// TRACE(_T("[%d] GetOutput %d %05x (%d)\n"), (int)m_perfmon.GetFrame(), i, (int)TEX0.TBP0, (int)TEX0.PSM);
 
 	GSTexture* t = NULL;
+	GSVector2i size = GetOutputSize(fb_height);
 
-	if (GSTextureCache::Target* rt = m_tc->LookupDisplayTarget(TEX0, GetOutputSize(fb_height), fb_height))
+	// Expand read horizontally if offset in to the texture. (Causes visible stretching on FMVs otherwise)
+	if(DISPFB.DBX)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:257]: Formatting.

**Comment by refractionpcsx2** [comment]
DJ Decks

Before:
image

After:
image

Sniper 2

Before:
image

After:
image

Mashed Fully Loaded

Before:
image

After:
image

Chaos Field

Before:
image

After:
image

**Comment by MarioSonic2987** [comment]
Fixes streched videos in Worms 4 Mayhem.

**Before**:
image


**After**:
image

**Comment by refractionpcsx2** [comment]
Thanks for letting us know! :)

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 2]
```diff
@@ -414,7 +414,7 @@ GSTextureCache::Source* GSTextureCache::LookupSource(const GIFRegTEX0& TEX0, con
 	return src;
 }
 
-GSTextureCache::Target* GSTextureCache::LookupTarget(const GIFRegTEX0& TEX0, const GSVector2i& size, int type, bool used, u32 fbmask, const bool is_frame, const int real_h)
+GSTextureCache::Target* GSTextureCache::LookupTarget(const GIFRegTEX0& TEX0, const GSVector2i& size, int type, bool used, u32 fbmask, const bool is_frame, const int real_h, const int real_w)
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:417]: Could be worth swapping `real_h` and `real_w` here, having them around the other way in one function seems a bit inconsistent.

**Review by JordanTheToaster — APPROVED** [review]

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp (hunk 2 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSTextureCache.cpp:417]: Yeah, I'll do that today. I also thought I probably wanna do a std::max on the new height and new width, since before it was only checking if one changed, but right now it's possible it could shrink one direction when expanding the other, so I should probably avoid that :D

**Comment by noigeaR** [comment]
Very nice!

I can confirm it fixes flickering in the following games:

- Yuusei kara no Buttai X - Episode II (GameDB fix can be removed again)
- Meiwaku Seijin Panic Maker
- Yamasa Digi World 4 & Yamasa Digi World 4 DX (GameDB fix can be removed)

and also fixes stretched video on the right side in:

- Taiko no Tatsujin: Tatacon de Dodon ga Don
- Taiko no Tatsujin: Doki! Shinkyoku Darake no Haru Matsuri
- Taiko no Tatsujin: Appare Sandaime
- Taiko no Tatsujin: Waku Waku Anime Matsuri

SoftwareRendererFMVHack for all Taiko games can be removed from GameDB
The newer Taiko no Tatsujin games were not affected by stretched videos.

**Comment by refractionpcsx2** [comment]
Thanks for the tests! :)

**Comment by AhayriSG** [comment]
SLUS20890
v1.7.3234
v1 7 3234
pr[6894]-sha[93054c3]
pr 6894 -sha 93054c3

**Comment by refractionpcsx2** [comment]
You shouldn't have interlacing turned off, we've been over this.

**Review by lightningterror — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Comment by AhayriSG** [comment]
@Mrlinkwii 
https://github.com/PCSX2/pcsx2/issues/6813#issuecomment-1227718520
SLUS21420
https://github.com/PCSX2/pcsx2/commit/ce34fbe5021cce613aacda2105d93ebf452fca8a - default settings

master

[93054c3](https://github.com/PCSX2/pcsx2/commit/93054c31038e65cd909ab2242c3b0e15c9b8933e) - default settings
PR

**Review by lightningterror — COMMENTED** [review]
Tested a number of games, didn't spot any issues.
