### PR TITLE
[GSdx OGL HW]: Perform a texture shuffle when the address of the framebuffer and the texture are the same

### LINKED ISSUE #2215: [GSdx OGL HW Regression] Tomb Raider: The Angel of Darkness - Missing Fog
***PCSX2 version:***
1.5.0-dev-2215

***PCSX2 options:***
Defaults

***Plugins used:***
GSdx OGL HW. (DX11/DX9 were never emulated correctly in HW - the fog fills the entire screen)

***Description of the issue:***
Fog in the distance is missing from the game.

***How to reproduce the issue:***
Go in-game, find an alleyway/area with long view distance; observe missing fog.

***Last known version to work:***
https://github.com/PCSX2/pcsx2/commit/4d10eda30821ca3fa049a8d1bb7253f25502ac1d

Regression introduced here: https://github.com/PCSX2/pcsx2/commit/52a2bb55241ffdf3b580f567400fe047c96b56fc

***PC specifications:***
i5-6600k @ 4.7GHz, GTX 1070, Windows 10 Home 64-bit

***Notes***

Debug messages:
```
T:Error	ID:10716	S:Mid	=> FBMASK SW emulated fb_mask:80808080 on 32 bits format
T:Error	ID:10738	S:Mid	=> First vertex is  P: 28800 => 36992    T: 8 => 8200
T:Error	ID:10738	S:Mid	=> Color shuffle R => B
T:Error	ID:10738	S:Mid	=> Color shuffle G => A
T:Error	ID:10738	S:Mid	=> ERROR: RT height is too small only 2048 but require 3584
```
I fixed the issue by flipping the sign in ```m_texture_shuffle = ((v[1].U - v[0].U) < 256);```

However, we need an alternative solution here. Replacing ```256``` with any value up to ```4096``` will also remedy the issue (while the sign is flipped) - I didn't test with values higher then that.
```
	// Shadow_of_memories_Shadow_Flickering
	if (m_texture_shuffle && count < 3 && PRIM->FST) {
		// Avious dubious call to m_texture_shuffle on 16 bits games
		// The pattern is severals column of 8 pixels. A single sprite
		// smell fishy but a big sprite is wrong.
		m_texture_shuffle = ((v[1].U - v[0].U) < 256);
}
```

OGL HW: (see top-left corner)
gsdx_20171211194518

OGL SW:
gsdx_20171211194518_ 2

### PR DESCRIPTION
**Pull request by MrCK1**
Perform a texture shuffle when the address of the framebuffer and the texture are the same. 

Tomb Raider: Angel of Darkness relies on this behavior to produce a distance fog effect. 

I didn't find regressions on any of the games I tested, but Shadow of Memories needs to be checked before this gets merged.

Closes #2215 (Let's keep the train rolling 😉 )

### CODE REVIEW

File: plugins/GSdx/GSRendererOGL.cpp [hunk 1]
```diff
@@ -234,7 +234,14 @@ void GSRendererOGL::EmulateTextureShuffleAndFbmask()
...
 		// smell fishy but a big sprite is wrong.
-		m_texture_shuffle = ((v[1].U - v[0].U) < 256);
+
+		// Tomb Raider Angel of Darkness relies on this behavior to prodce a fog effect.
+		// In this case, the address of the framebuffer 
+		// and texture are the same. 
+		// The game will take RG => BA and then the BA => RG of next pixels. 
+		// However, only RG => BA needs to be emulated because RG isn't used.
+		GL_INS("WARNING: Possible misdetection of a texture shuffle effect");
+		m_texture_shuffle = ((v[1].U - v[0].U) < 256) || ((m_context->FRAME.Block() == m_context->TEX0.TBP0));
```
Comment (FlatOutPS2) [inline plugins/GSdx/GSRendererOGL.cpp]: There are double brackets around m_context->FRAME.Block() == m_context->TEX0.TBP0 ;)

Comment (MrCK1) [reply plugins/GSdx/GSRendererOGL.cpp]: It was nearly perfect. I'll fix it after I eat :P

File: plugins/GSdx/GSRendererOGL.cpp [hunk 2]
```diff
@@ -234,7 +234,14 @@ void GSRendererOGL::EmulateTextureShuffleAndFbmask()
 		// Avious dubious call to m_texture_shuffle on 16 bits games
 		// The pattern is severals column of 8 pixels. A single sprite
 		// smell fishy but a big sprite is wrong.
-		m_texture_shuffle = ((v[1].U - v[0].U) < 256);
+
+		// Tomb Raider Angel of Darkness relies on this behavior to prodce a fog effect.
+		// In this case, the address of the framebuffer 
+		// and texture are the same.
```
Comment (FlatOutPS2) [inline plugins/GSdx/GSRendererOGL.cpp]: While you're at it, you should add the text here to the previous line.

Comment (MrCK1) [reply plugins/GSdx/GSRendererOGL.cpp]: Git's finally done being stupid (saying my branch wasn't published) The changes are done.

File: plugins/GSdx/GSRendererOGL.cpp (hunk 1 above)
Comment (turtleli) [reply plugins/GSdx/GSRendererOGL.cpp]: I think all the brackets (except after Block of course) are unnecessary? Though perhaps the brackets around `v[1].U - v[0].U` helps improve clarity.

Comment (MrCK1) [reply plugins/GSdx/GSRendererOGL.cpp]: I assume you want me to remove them?

Comment (turtleli) [reply plugins/GSdx/GSRendererOGL.cpp]: Personally I would, but I don't know if others will have trouble figuring out the evaluation order.

File: plugins/GSdx/GSRendererOGL.cpp [hunk 3]
```diff
@@ -234,7 +234,13 @@ void GSRendererOGL::EmulateTextureShuffleAndFbmask()
 		// Avious dubious call to m_texture_shuffle on 16 bits games
 		// The pattern is severals column of 8 pixels. A single sprite
 		// smell fishy but a big sprite is wrong.
-		m_texture_shuffle = ((v[1].U - v[0].U) < 256);
+
+		// Tomb Raider Angel of Darkness relies on this behavior to prodce a fog effect.
```
Comment (ssakash) [inline plugins/GSdx/GSRendererOGL.cpp]: *produce

**Comment by FlatOutPS2** [comment]
@MrCK1 You should make it clear in the commit title/message that this only applies to OpenGL HW.

**Comment by MrCK1** [comment]
Well the file changed already debotes that, but I'll fix it later  :P

**Comment by MrCK1** [comment]
This can be merged now.

**Comment by ssakash** [comment]
**Note**: There are potential chances for regression if the channel shuffle is emulated at scenarios when not necessary (due to the new base pointer check), so keep a look out for regressions.
