### PR TITLE
GIF: Sync GIF DMA packet ends

### LINKED ISSUE #6210: [BUG]: Mana Khemia - Artifacts (Regression?)
### Describe the Bug

Hi, this game was previously working fine, so I'm guessing it's a regression issue.

here a video:
https://user-images.githubusercontent.com/17991404/170619114-504db4de-7bd7-4fca-a773-2d704c58885b.mp4

### Reproduction Steps

The bug is appreciated as soon as you begin to control the protagonist. It's just walking around and seeing the artifacts.

### Expected Behavior

No artifacts.
In old versions, this didn't happen, I think you can compare with the last time the game was fixed which was last year, I think...

### PCSX2 Revision

v1.7.2813

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i7 10800h

### GPU

RTX 3060

### GS Settings

all default

### Emulation Settings

_No response_

### GS Window Screenshots

gs_20220526224501_Mana Khemia - Alchemists of Al-Revis_SLUS-21735

### Logs & Dumps

this is a gs dump.
[gs_20220526224501_Mana Khemia - Alchemists of Al-Revis_SLUS-21735.zip](https://github.com/PCSX2/pcsx2/files/8783631/gs_20220526224501_Mana.Khemia.-.Alchemists.of.Al-Revis_SLUS-21735.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adjusts the length of GIF packets being read if there's more than 8 quadwords in order to make sure FINISH signals don't fire before the GIF DMA is ready to complete, which could cause timing issues.

### Rationale behind Changes
Things happened too quick with big packets causing sync/timing issues. Make @darkxex happy

### Suggested Testing Steps
Test games, make sure there's no graphical issues

Fixes #6210

### CODE REVIEW

**Comment by darkxex** [comment]
thanks bro.

File: pcsx2/Gif.cpp [hunk 1]
```diff
@@ -328,6 +328,10 @@ static u32 WRITERING_DMA(u32* pMem, u32 qwc)
 		else
 			qwc = std::min(qwc, 8u);
 	}
+	// If the packet is larger than 8qw, try to time the packet somewhat so any "finish" signals don't fire way too early and GIF syncs with other units.
+	// (Mana Khemia exhibits flickering characters without).
+	else if(qwc > 8)
```
Comment (lightningterror) [inline pcsx2/Gif.cpp:333]: Formatting.
