### PR TITLE
Core: Plugin resume after configure

### LINKED ISSUE #3989: [PAD Regression] Trying to configure Lilypad kills any Pad input.
Starting with dev-609 #3935 , trying to configure Lilypad results in Input not responding.

**To Reproduce**
1. Run a Game
2. Config --> Controller (Pad) --> Plugin Settings
3. Click "OK"
4. Input stops responding

Credit: NewMoon

### PR DESCRIPTION
**Pull request by TheLastRar**
SysExecEvent_SaveSinglePlugin would close the plugin, but not reopen it

Should fix the issue of lilypad input breaking after configuring during emulation

Fixes #3989

### CODE REVIEW

**Comment by Fabianpaw** [comment]
Seems to fix #3989 without any new Regressions in my Testing.

File: pcsx2/gui/AppCorePlugins.cpp [hunk 1]
```diff
@@ -553,6 +553,8 @@ void SysExecEvent_SaveSinglePlugin::InvokeEvent()
 			GetCorePlugins().Freeze( m_pid, save );
 		}
 			
+		bool wasOpen = GetCorePlugins().IsOpen(m_pid);
```
Comment (lightningterror) [inline pcsx2/gui/AppCorePlugins.cpp:568]: Const bool?

Comment (TheLastRar) [reply pcsx2/gui/AppCorePlugins.cpp]: Changed to const

**Comment by lightningterror** [comment]
Needs rebase.

**Comment by TheLastRar** [comment]
Rebase done

**Review by tadanokojin — APPROVED** [review]
