### PR TITLE
GS/TC: Avoid no size targets being made

### LINKED ISSUE #9883: [BUG]: Taiko no Tatsujin (Drum Master) - Intro Video Invisible in D3D12 and Vulkan.
### Describe the Bug

When starting Taiko no Tatsujin (Drum Master) - SLPS2022-1, the Into Video plays only when using Software rendering, and is invisible when using D3D12 or Vulkan rendering.
Strangely enough, switching to software mode while the intro is playing, and then back to D2D12 or Vulkan results in the video displaying normally.

https://github.com/PCSX2/pcsx2/assets/136824455/98e11a7d-a058-4c07-9964-482026c925a3

### Reproduction Steps

1. Set D3D12 or Vulkan renderer.
2. Start Taiko no Tatsujin (SLPS2022-1)
3. Note intro video is missing (black screen, music plays)
4. Switch to software mode while video is playing
5. Video appears
6. Switch back to D3D12 or Vulkan
7. Video remains working correctly.

### Expected Behavior

Video should be visible on D3D12 or Vulkan when selected as the startup renderer.

### PCSX2 Revision

1.7.4967

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5900 HX

### GPU

Integrated Radeon

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Avoids targets with no size being made in the texture cache

### Rationale behind Changes
Sometimes the PCRTC circuits get enabled with rubbish sizes, this confuses the texture cache, and it was ending up with targets covering the entire GS memory.

Also sets the end block to match the start block on new targets, rather than the end of memory, just in case it does somehow not update it, it won't span the entire memory.

### Suggested Testing Steps
Test the FMVS on Taiko no Tatsujin - Tatacon de Dodon ga Don

Fixes #9883

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -2023,6 +2023,9 @@ GSTextureCache::Target* GSTextureCache::CreateTarget(GIFRegTEX0 TEX0, const GSVe
 		GL_CACHE("TC: Lookup %s(Color) %dx%d FBMSK %08x, miss (0x%x, TBW %d, %s) draw %d", is_frame ? "Frame" : "Target",
 			size.x, size.y, fbmask, TEX0.TBP0, TEX0.TBW, psm_str(TEX0.PSM), g_gs_renderer->s_n);
 	}
+	// Avoid making garbage targets (usually PCRTC).
+	if (GSVector4i::loadh(size).rempty())
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2027]: Maybe but it at the start of the function?

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2027]: That is the start of the function?

Comment (lightningterror) [reply pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2027]: I meant before the logs, or do we want them to paste?

**Review by kamfretoz — APPROVED** [review]
