### PR TITLE
UI: Fix build with achievements disabled

### LINKED ISSUE #8457: [BUG]: Can't compile with Achievements disabled
### Describe the Bug

If i turn off the USE_ACHIEVEMENTS option the compilation fails

### Reproduction Steps

set USE_ACHIEVEMENTS to OFF

### Expected Behavior

for it to be compiled with USE_ACHIEVEMENTS set to OFF

### PCSX2 Revision

1.7.4263

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Artix

### PR DESCRIPTION
**Pull request by TellowKrinkle**
### Description of Changes
Makes the no achievements config build again
Fixes #8457

### Rationale behind Changes
Successfully building is good

### Suggested Testing Steps
@DNDEBUG @LeCharlatan please test

### CODE REVIEW

**Comment by DNDEBUG** [comment]
it works

File: pcsx2/Frontend/CommonHotkeys.cpp [hunk 1]
```diff
@@ -43,7 +43,12 @@ void CommonHost::Internal::ResetVMHotkeyState()
 
 static void HotkeyAdjustTargetSpeed(double delta)
 {
-	const double min_speed = Achievements::ChallengeModeActive() ? 1.0 : 0.1;
+#ifdef ENABLE_ACHIEVEMENTS
```
Comment (stenzek) [inline pcsx2/Frontend/CommonHotkeys.cpp:46]: This bit shouldn't be needed - `ChallengeModeActive()` returns false when it's not compiled in: https://github.com/PCSX2/pcsx2/blob/280a41806f8a212597deac50a466fb052729c19e/pcsx2/Achievements.h#L60-L63

**Review by stenzek — CHANGES_REQUESTED** [review]

**Review by stenzek — APPROVED** [review]
