### PR TITLE
GS-HW: Check what channel is being read during a possible split shuffle

### LINKED ISSUE #8503: [REGRESSION]: 50 Cent Bulletproof - channel shuffle
### Describe the Bug

Green hue in background except characters; regression from https://github.com/PCSX2/pcsx2/pull/8336

### Reproduction Steps

v1.7.4227 on hardware renderer when you start game.

### Expected Behavior

The whole screen shouldn't be green.

### PCSX2 Revision

v1.7.4227

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7-9750H

### GPU

RTX 2060M

### GS Settings

/

### Emulation Settings

/

### GS Window Screenshots

/

### Logs & Dumps

[50CentGsdump.zip](https://github.com/PCSX2/pcsx2/files/11105640/50CentGsdump.zip)

50 Cent - Bulletproof_SLUS-21315_20230329231035

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Check what channel is being read during split shuffle detection.

### Rationale behind Changes
50 Cent Bulletproof was misdetecting this effect as it does 2 shuffles, one for the green channel, the one for the red, but it was being detected as the same shuffle, making the screen very green! So now we change that the first UV's for each shuffle match up.

### Suggested Testing Steps
Test 50 Cent (I've checked GS dumps).

50Cent:
Master:
image

PR:
image

Fixes #8503

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -877,6 +877,10 @@ bool GSRendererHW::IsSplitTextureShuffle()
 	// X might be offset by up to -8/+8, but either the position or UV should be aligned.
 	GSVector4i aligned_rc = pos_rc.min_i32(tex_rc).blend32<12>(pos_rc.max_i32(tex_rc));
 
+	// Different channel being shuffled, so needs to be handled separately (misdetection in 50 Cent)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:880]: Maybe swap this with where frame_psm is set as an optimization?

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:880]: I could put it further up, yeah.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 2]
```diff
@@ -863,6 +863,10 @@ bool GSRendererHW::IsSplitTextureShuffle()
 		return false;
 	}
 
+	// Different channel being shuffled, so needs to be handled separately (misdetection in 50 Cent)
+	if (m_vertex.buff[m_index.buff[0]].U != m_v.U)
+		return false;
+
 	// Check that both the position and texture coordinates are page aligned, so we can work in pages instead of coordinates.
 	// For texture shuffles, the U will be offset by 8.
 	const GSLocalMemory::psm_t& frame_psm = GSLocalMemory::m_psm[m_context->FRAME.PSM];
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:872]: This could've been moved a bit down, anyway it's fine, gonna shove it in a pr I'm working on.

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:872]: why bother moving it down? there's no need for it to be any lower.

Comment (lightningterror) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:872]: On the next return it's not used so we might set it for nothing.

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:872]: set what for nothing? I don't understand, if something is wrong it'll fail no matteer where you put it
