### PR TITLE
SIF: Correct junk data behaviour. Fixes True Crime Streets of LA

### LINKED ISSUE #6589: [BUG]: Winter Time daylight savings option doesn't function
### Describe the Bug

Selecting Winter Time in the BIOS fails to actually swap properly to winter time, causing some games (such as PDC Darts 2008) to TLB miss for no discernible reason.

### Reproduction Steps

go in to your bios and try to set the daylight savings to winter time, it'll still say summer time.

### Expected Behavior

_No response_

### PCSX2 Revision

tested 1.6-1.7.3061

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 3900X

### GPU

RTX 208T

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

image

### Logs & Dumps

_No response_

### LINKED ISSUE #8482: [BUG]: PAD - SIO - True Crimes L.A. requires second pad
### Describe the Bug

the game won't start without second controller emulated. 

### Reproduction Steps

try to start a game. 

### Expected Behavior

games starts like normal

### PCSX2 Revision

1.7.4274

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Fixes the SIF junk behaviour to accurately match what the PS2 console does.

### Rationale behind Changes

To Save repeating myself here's the comment I made in the code.

If there is not enough data produced from the IOP, it will always use the previous full quad word to
fill in the missing data.
One thing to note, when the IOP transfers the EE tag, it transfers a whole QW of data, which will include
the EE Tag and the next IOP tag, since the EE reads 1QW of data for DMA tags.

So the data used will be as follows:
Less than 1QW = Junk data is made up of the EE tag + address (64 bits) and the following IOP tag (64 bits).
More than 1QW = Junk data is made up of the last complete QW of data that was transferred in this packet.

Data is always offset in to the junk by the amount the IOP actually transferred, so if it sent 2 words
it will read words 3 and 4 out of the junk to fill the space.

PS2 test results:
Example of less than 1QW being sent with the only data being set being 0x69

addr 0x1500a0 value 0x69              <-- actual data (junk behind this would be the EE tag)
addr 0x1500a4 value 0x1500a0      <-- EE address
addr 0x1500a8 value 0x8001a170  <-- following IOP tag
addr 0x1500ac value 0x10              <-- following IOP tag word count

Example of more than 1QW being sent with the data going from 0x20 to 0x25.

addr 0x150080 value 0x21 <-- start of previously completed QW
addr 0x150084 value 0x22
addr 0x150088 value 0x23
addr 0x15008c value 0x24 <-- end of previously completed QW
addr 0x150090 value 0x25 <-- end of recorded data
addr 0x150094 value 0x22 <-- from position 2 of the previously completed quadword
addr 0x150098 value 0x23 <-- from position 3 of the previously completed quadword
addr 0x15009c value 0x24 <-- from position 4 of the previously completed quadword

### Suggested Testing Steps
Test some normal games but also test True Crime Streets of L.A. with controller 2 connected or disconnected (shouldn't matter anymore), and PDC Darts Championship 2008 (PAL) with the BIOS daylight savings set to Winter Mode

Fixes #8482 True Crime Streets of L.A.
Fixes #6589 PDC Darts Championship 2008
Fixes Street Racing Syndicate garage crash on version 1.03 of the game.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Just had a shower thought on my way to bed, I think I can explain the < 1qw behaviour. I suspect its actually transferring 1qw for the EE tag in to the fifo, so that will make up

EE tag
EE addr
Iop tag
Iop word count

And this would be the aligned qw transferred, which is what we're seeing here. So that would mean the behaviour between both is exactly the same and the world is happy again.

I'll change the code tomorrow to act exactly like that, but there won't be any compatibility changes once I do, so this is still good to test

**Comment by refractionpcsx2** [comment]
Additionally this fixes the PDC Darts Championship 2008 crash if your BIOS is set to Winter Time :)

File: pcsx2/Sif.h [hunk 1]
```diff
@@ -68,22 +62,62 @@ struct sifFifo
...
+	//	addr 0x15009c value 0x24 <-- from position 4 of the previously completed quadword
+
 	void writeJunk(int words)
 	{
 		if (words > 0)
 		{
-			if ((FIFO_SIF_W - size) < words)
-				DevCon.Warning("Not enough Junk space in SIF0 FIFO!\n");
+			u32 transferredWords = 4 - words;
+			u32 prevQWPos = (writePos - (4 + transferredWords)) & (FIFO_SIF_W - 1); // position is in words.
```
Comment (lightningterror) [inline pcsx2/Sif.h:104]: These two constant.

**Comment by JordanTheToaster** [comment]
Fixes Street Racing Syndicate locking up with VIF spam in the Volkswagen garage.

image
