### PR TITLE
GS: Disallow flipped GS->GS transfer when destination overwrites source

### LINKED ISSUE #2399: Armored Core 2: Garbage texture instead of animated texture
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
 Default

***Plugins used:***
 Default

***Description of the issue:***
The corridor right after the final enemy of the game is supposed to have an energy wave running along the walls effect like so
https://youtu.be/7U2ZUgk8ubE?t=522
Instead in PCSX2 it appears like this even using the SW renderer.
gsdx_20180421145502
[Armored core 2 garbage texture corridor.zip](https://github.com/PCSX2/pcsx2/files/1934565/Armored.core.2.garbage.texture.corridor.zip)
The effect itself appears to be part of the texture

***How to reproduce the issue:***
1.Go into the corridor that opens right after defeating the final boss.

***Last known version to work:***
 None 

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Disallows GS Local to Local transfers to reverse the direction of copies if the destination overwrites source data.

### Rationale behind Changes
On the console the copies are page buffered, so this isn't a problem, this is exactly the same issue as #5601 fixed, but for reversed coordinates.

As far as I can understand, these directions don't do anything beyond try to guarantee a page break for upcoming draws to make sure the cache is correctly updated, it serves little purpose beyond this.

### Suggested Testing Steps
Test Armored Core 2, the pulsing light tunnel on the last level, but also the lights on top of the builds in the first level intro.
Also check Tekken 5 and Wild ARMs Alter Code F to make sure they're fine from the transfer list changes (Tekken shows less uploads, which is nice)

### Did you use AI to help find, test, or implement this issue or feature?
No

Fixes #2399 Armored Core 2 garbled textures.

GS Dump that shows it broken on master but not the PR (all original dumps are broken already)
[Armored Core 2_SLPS-25007_20260108033737.gs.zip](https://github.com/user-attachments/files/24486710/Armored.Core.2_SLPS-25007_20260108033737.gs.zip)

Master:
image

PR:
image

### CODE REVIEW

File: pcsx2/GS/GSState.cpp [hunk 1]
```diff
@@ -2584,7 +2594,7 @@ void GSState::Move()
 			// Copying from itself to itself (rotating textures) used in Gitaroo Man stage 8
 			// What probably happens is because the copy is buffered, the source stays just ahead of the destination.
 			// No need to do all this if the copy source/destination don't intersect, however.
-			const bool intersect = !(GSVector4i(sx, sy, sx + w, sy + h).rintersect(GSVector4i(dx, dy, dx + w, dy + h)).rempty());
+
```
Comment (lightningterror) [inline pcsx2/GS/GSState.cpp]: Small nitpick, extra rows.

File: pcsx2/GS/GSState.cpp [hunk 2]
```diff
@@ -2519,21 +2519,31 @@ void GSState::Move()
...
 	int xinc = 1;
 	int yinc = 1;
 
 	if (m_env.TRXPOS.DIRX)
 	{
-		sx += w - 1;
-		dx += w - 1;
-		xinc = -1;
+		// Only allow it to reverse if the destination is behind the source.
+		if (!intersect || (sx <= dx && (sx == dx || ((!m_env.TRXPOS.DIRY && sy >= dy) || (m_env.TRXPOS.DIRY && sy < dy)))))
```
Comment (lightningterror) [inline pcsx2/GS/GSState.cpp:2531]: Could merge it with the above condition.

File: pcsx2/GS/GSState.cpp [hunk 3]
```diff
@@ -2519,21 +2519,31 @@ void GSState::Move()
...
+			xinc = -1;
+		}
 	}
 	if (m_env.TRXPOS.DIRY)
 	{
-		sy += h - 1;
-		dy += h - 1;
-		yinc = -1;
+		// Only allow it to reverse if the destination is behind the source.
+		if (!intersect || (sy <= dy && (sy == dy || ((!m_env.TRXPOS.DIRX && sx >= dx) || (m_env.TRXPOS.DIRX && sx < dx)))))
```
Comment (lightningterror) [inline pcsx2/GS/GSState.cpp:2541]: This too.

File: pcsx2/GS/GSState.cpp (hunk 2 above)
Comment (refractionpcsx2) [reply pcsx2/GS/GSState.cpp:2531]: There's already enough brackets, there's no need to merge it.

File: pcsx2/GS/GSState.cpp (hunk 3 above)
Comment (refractionpcsx2) [reply pcsx2/GS/GSState.cpp:2541]: This too.
