### PR TITLE
GameDB/Patching: Add dynamic EE JIT patching

### LINKED ISSUE #354: Ratchet & Clank 2 - Megaturret Doesn't Work Correctly
Core issue?

Issue title: Ratchet & Clank 2 (PAL/Australia) Megaturret Not Working

-PCSX2 version: 1.2.1 Stable

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx (SW or HW), SPU2-X, Lilypad, Linuz or Gigaherz CDVD,rest null plugins. Same issue under ZeroGS - ruling out Graphics.

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The turrets from the Megaturret Glove (the upgraded Miniturrent Glove) just bounce up and down with their starting sound and animation looping. They don't work (shoot anything).

-How to replicate: Upgrade the Miniturret Glove to the Megaturret glove and use it.

-Last known version to work: Never worked (checked back to 0.9.7). Also checked most recent testing build.

-PC specifications: 
CPU: Intel Core i5 2500K @ 4.3Ghz 
GPU: Gigabyte Radeon 6950 1GB
OS: Windows 7 x64 SP1

-Other comments: Aside from this issue, the game runs fine under Software Mode. No settings/gamefixes seem to make a difference. 2 other people have posted the issue in the past with no resolution (but they stopped following up the issue pretty quickly). These people seemed to have 64-bit Windows and PAL-Region games, like me. I have not tried the NTSC release.

I've filled out the required info as I understand it and welcome any ideas or requests for more information.

Thanks.

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Reimplement dynamic EE JIT patching as was first attempted in #4541, but better and actually generic for use with any game.

### Rationale behind Changes
We needed dynamic patching to fix some bugs with Ratchet & Clank 2, specifically the Mega Turret problem.

### Suggested Testing Steps
Test Ratchet & Clank 2 PAL and see if the Mega Turret works. You can also mess with the GameDB and add your own.

To add your own the format is like this

```
  dynaPatches:
    - pattern:
        - { offset: 0x0, value: 0x0280202d }
        - { offset: 0x4, value: 0x3c0140d0 }
        - { offset: 0x8, value: 0x44810800 }
        - { offset: 0x10, value: 0x46000836 }
      replacement:
        - { offset: 0x4, value: 0x3c013f80 }
 ```

The important ones here are the pattern and replacement. 

The pattern is the sequence of EE instructions it needs to match in order to apply the patch, each code will be tested at an offset from the current program counter being compiles.

The replacement is the code which will be applied as a patch to the EE code, as with the pattern, it will be applied as an offset from the program counter being tested.

You can add multiple patches for different things in the game by duplicating all the code except the `dynaPatches:` line, as - signifies an array entry.

Closes #354 although the real solution is Soft Floats, this'll do for now.

### CODE REVIEW

**Comment by kakashi314** [comment]
Very good idea! we may also be able to use it as a speedhack. but that's for another day.

File: pcsx2/Patch.cpp [hunk 1]
```diff
@@ -33,8 +33,10 @@
 // the only consumer, so it's not made public via Patch.h
 // Applies a single patch line to emulation memory regardless of its "place" value.
 extern void _ApplyPatch(IniPatch* p);
+extern void _ApplyDynaPatch(DynamicPatch patch, u32 address);
```
Comment (stenzek) [inline pcsx2/Patch.cpp:36]:
```suggestion
extern void _ApplyDynaPatch(const DynamicPatch& patch, u32 address);
```

File: pcsx2/Patch.cpp [hunk 2]
```diff
@@ -33,8 +33,10 @@
...
 
 static std::vector<IniPatch> Patch;
+static std::vector< DynamicPatch> DynaPatch;
```
Comment (stenzek) [inline pcsx2/Patch.cpp:39]:
```suggestion
static std::vector<DynamicPatch> DynaPatch;
```

File: pcsx2/Patch.cpp [hunk 3]
```diff
@@ -286,3 +289,18 @@ void ApplyLoadedPatches(patch_place_type place)
 			_ApplyPatch(&i);
 	}
 }
+
+void ApplyDynamicPatches(u32 pc)
+{
+	for (auto dynpatch : DynaPatch)
```
Comment (stenzek) [inline pcsx2/Patch.cpp:295]:
```suggestion
	for (const auto& dynpatch : DynaPatch)
```

File: pcsx2/Patch.cpp [hunk 4]
```diff
@@ -286,3 +289,18 @@ void ApplyLoadedPatches(patch_place_type place)
...
+	{
+		_ApplyDynaPatch(dynpatch, pc);
+	}
+}
+
+void LoadDynamicPatches(const std::vector<DynamicPatch>& patches)
+{
+	for (auto it = begin(patches); it != end(patches); ++it) {
```
Comment (stenzek) [inline pcsx2/Patch.cpp:303]:
```suggestion
	for (const DynamicPatch& it : patches)
```

File: pcsx2/Patch.h [hunk 5]
```diff
@@ -34,10 +34,9 @@
 // - The 0 cheats - cheats are enabled but nothing found/loaded from the "cheats" folder.
 // - The 6 widescreen patches are 6 pnach-style patch lines loaded either from cheats_ws folder or from cheats_ws.zip
 
-
```
Comment (stenzek) [inline pcsx2/Patch.h:37]: I think you mentioned this, but is it possible to avoid pulling in the console header by changing the files where Patch.h is included instead?

File: pcsx2/Patch_Memory.cpp [hunk 6]
```diff
@@ -590,6 +590,22 @@ void _ApplyPatch(IniPatch *p)
 	}
 }
 
+void _ApplyDynaPatch(DynamicPatch patch, u32 address)
+{
+	for (auto pattern : patch.pattern)
```
Comment (stenzek) [inline pcsx2/Patch_Memory.cpp:595]:
```suggestion
	for (const auto& pattern : patch.pattern)
```

File: pcsx2/Patch_Memory.cpp [hunk 7]
```diff
@@ -590,6 +590,22 @@ void _ApplyPatch(IniPatch *p)
...
+	{
+		if (*(u32*)PSM(address + pattern.offset) != pattern.value)
+			return;
+	}
+
+	PatchesCon->WriteLn("Applying Dynamic Patch to address 0x%08X", address);
+	// If everything passes, apply the patch.
+	for (auto replacement : patch.replacement)
```
Comment (stenzek) [inline pcsx2/Patch_Memory.cpp:603]:
```suggestion
	for (const auto& replacement : patch.replacement)
```

File: pcsx2/Patch.h (hunk 5 above)
Comment (refractionpcsx2) [reply pcsx2/Patch.h:37]: It was pulling the console stuff from the gamedatabase, but that was a circular include :(
