### PR TITLE
GSDX: set a safe limit to Framebuffer width

### LINKED ISSUE #1224: [Regression] Resident Evil 4 PAL 50hz frame buffer size spam
Description:
ssakash's  commit "Detect RT size based on display and frame registers." from pcsx2-v1.5.0-dev-407 seems to cause a regression in Resident Evil 4's 50hz(PAL) mode. It makes the game to constantly switch frame buffer size and spam the console with:
"Frame buffer size set to  448x512 (1344x1536)
Frame buffer size set to  512x512 (1536x1536)"

Options and plugins all default, except using HW renderer with above native resolution

How to replicate:
Use pcsx2-v1.5.0-dev-407-gedef3ad or later. Select one of the hardware renderers using higher than native resolution, and boot the PAL version of Resident Evil 4 without turning on Progressive Scan.

Last known version to work:
v1.5.0-dev-405-g8839632

### PR DESCRIPTION
**Pull request by ssakash**
There are likely few games (RE4) which constantly change the FBW register value causing the framebuffer width to be updated at every interval. Adding a safe limit (512) similar to frame buffer height would prevent such constant changes of the framebuffer width when FBW changes once again to an even lower value. 

Might fix #1224 

Build download link: [here](https://ci.appveyor.com/api/buildjobs/ddu3msnyjdtwfgp8/artifacts/pcsx2-v1.5.0-dev-415-g900ed88-master-615-vs2015-Win32-AppVeyor.7z)

### CODE REVIEW

**Comment by ssakash** [comment]
@turtleli 

do you know why travis-ci fails the build process ?
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by turtleli** [comment]
Nope. Could be a temp thing, I'll restart the build later and see if it fixes itself.

File: plugins/GSdx/GSRendererHW.cpp [hunk 1]
```diff
@@ -55,7 +55,8 @@ void GSRendererHW::SetScaling()
 	// Framebuffer width is always a multiple of 64 so at certain cases it can't cover some weird width values.
 	// 480P , 576P use width as 720 which is not referencable by FBW * 64. so it produces 704 ( the closest value multiple by 64).
 	// In such cases, let's just use the CRTC width.
-	int fb_width = max((int)m_context->FRAME.FBW * 64, crtc_width);
+	auto search_fb_width = minmax({(int)m_context->FRAME.FBW * 64, crtc_width , 512});
+	int fb_width = search_fb_width.second;
```
Comment (gregory38) [inline plugins/GSdx/GSRendererHW.cpp]: May I suggest to use std::max instead. I think it could work with ilist. Otherwise just uses 2 max.

As a side note, I think it could be a good idea to cache the fb_* value in the object. And ensure that new size is always bigger than previous size. (Or you can use m_width and m_height).

Something like that
```
int upscaled_fb_h = max ( fb_height * m_upscale_multiplier, m_height).
good_rt_size = (m_height == upscaled_fb_h) && ... 
```

Comment (ssakash) [inline plugins/GSdx/GSRendererHW.cpp]: done, though I don't see the advantage on having it as a member variable. I liked the old code better :\

File: plugins/GSdx/GSRendererHW.cpp [hunk 2]
```diff
@@ -45,23 +45,27 @@ GSRendererHW::GSRendererHW(GSTextureCache* tc)
 		m_userhacks_align_sprite_X = 0;
 	}
 
+		m_fb_width = max((int)m_context->FRAME.FBW * 64, 512);
```
Comment (gregory38) [inline plugins/GSdx/GSRendererHW.cpp]: I know that my previous comment wasn't very clear. Sorry.

Actually, I think we can only cache the m_width/m_height variable. Besides, I'm afraid that it won't be legal to read context information here (aka the init).

So you can move back those lines in SetScaling. This way variable can be local.

Comment (ssakash) [inline plugins/GSdx/GSRendererHW.cpp]: > Besides, I'm afraid that it won't be legal to read context information here (aka the init).

oops, sorry ! Strange that I didn't hit any exceptions while checking the code.

File: plugins/GSdx/GSRendererHW.cpp [hunk 3]
```diff
@@ -49,19 +49,20 @@ GSRendererHW::GSRendererHW(GSTextureCache* tc)
...
 	// from physical units of the display rectangle in case the game uses a heigher value of height.
-	int fb_height = (fb_width < 1024) ? max(512, crtc_height) : 1024;
-	bool good_rt_size = m_width == (fb_width * m_upscale_multiplier) && m_height == (fb_height * m_upscale_multiplier);
-	bool initialized_register_state = ((m_context->FRAME.FBW * 64) > 1) && (crtc_height > 1);
+	int fb_height = (fb_width < 1024) ? max(512, crtc_size.y) : 1024;
+
+	int upscaled_fb_w = fb_width * m_upscale_multiplier;
+	int upscaled_fb_h = fb_height * m_upscale_multiplier;
+	bool good_rt_size = m_width == upscaled_fb_w && m_height == upscaled_fb_h;
+	bool initialized_register_state = ((m_context->FRAME.FBW * 64) > 1) && (crtc_size.y > 1);
```
Comment (gregory38) [inline plugins/GSdx/GSRendererHW.cpp]: is `initialized_register_state` still useful? I mean you will have a minimum size of 512x512 now.

```
bool good_rt_size = m_width == upscaled_fb_w && m_height == upscaled_fb_h;
```
For me size is good if current size is equal or bigger than new computed value. So m_width >= upscaled_fb_w && ...

Comment (ssakash) [inline plugins/GSdx/GSRendererHW.cpp]: > is initialized_register_state still useful? I mean you will have a minimum size of 512x512 now.

Removed it, it's useless now for the reason you had stated.

> For me size is good if current size is equal or bigger than new computed value. So m_width >= upscaled_fb_w && ...

Done, though do note that in this case if game uses a bigger buffer at 3X native and if user changes back to 2X native then it'll still keep using the buffer size required for 3X instead of rescaling it to minimum required for 2X native. due to ``m_width >= upscaled_fb_w && ...`` check.

Comment (gregory38) [inline plugins/GSdx/GSRendererHW.cpp]: Are you sure. Object ought to be completely deleted when we change options and fully reinitilialized.

Comment (ssakash) [inline plugins/GSdx/GSRendererHW.cpp]: I feel so stupid :/ 

Apologies for my earlier statement.
