### PR TITLE
Debugger: Check for successful QString conversion in MemoryViewerWidget.cpp before writing

### LINKED ISSUE #10745: [BUG]: Non-hexadecimal keys write 0 in Memory Viewer
### Describe the Bug

Pressing `G` key in Memory view writes `0` (nibble) to current cursor.
- `G` key is hotkey for "Go to address", but it somehow writes 0 to emulated memory.

### Reproduction Steps

1. Start PCSX2
2. Run a game
3. Open Debugger
4. Pause the game
5. Select non-0 nibble in Memory viewer
6. Press `G` key

### Expected Behavior

`G` key should just open "Go to address" without modifying emulated memory.

### PCSX2 Revision

v1.7.5531

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### Logs & Dumps

https://github.com/PCSX2/pcsx2/assets/91955473/9aa152e5-b5e3-45a5-92be-53c00daf0064

### PR DESCRIPTION
**Pull request by TheTechnician27**
### Description of Changes
Checks the status of a QString conversion of the keypress being entered into the hex nibble of the memory viewer widget before they're entered to ensure they're valid.

### Rationale behind Changes
Before, pressing a key other than 0–9 or a–f in the hex viewer would result in a failed QString conversion resulting in a 0. This fixes #10745 by @Berylskid. Credit to @Daniel-McCarthy for pointing out that the function call was failing because the QString conversion was failing and for noting that the status of this conversion was stored in pressHandled, which I hadn't realized.

### Suggested Testing Steps
Go to the debugger while in a game, go to the hex viewer at the bottom, and try entering usual values into the hex viewer. Then try to add an unusual one (not 0–9 a–f) and see what happens.

### CODE REVIEW

**Review by Berylskid — APPROVED** [review]
Tested cmake clang build on my Win11, and it works flawlessly

**Review by kamfretoz — APPROVED** [review]

**Review by F0bes — APPROVED** [review]
LGTM. Just wanted to add, the comment doesn't add much. Maybe "Checks if the key pressed is base 16" would be better. We also don't need to know the result if it fails, we never use it in that case ^_^

**Comment by TheTechnician27** [comment]
> LGTM. Just wanted to add, the comment doesn't add much. Maybe "Checks if the key pressed is base 16" would be better. We also don't need to know the result if it fails, we never use it in that case ^_^

If it's alright with you, I'll change it to "Check if key pressed is base-16 before insertion (QString conversion fails otherwise).".

Basically telling the reader _how_ this is checking that it's base-16, since at a glance, a reader might not know the conversion has this quirk. From there, if they wanted to know what it returns, you're right that they could just look up the QString documentation.

**Comment by F0bes** [comment]
> > LGTM. Just wanted to add, the comment doesn't add much. Maybe "Checks if the key pressed is base 16" would be better. We also don't need to know the result if it fails, we never use it in that case ^_^
> 
> If it's alright with you, I'll change it to "Check if key pressed is base-16 before insertion (QString conversion fails otherwise).".
> 
> Basically telling the reader _how_ this is checking that it's base-16, since at a glance, a reader might not know the conversion has this quirk. From there, if they wanted to know what it returns, you're right that they could just look up the QString documentation.

Sure.

**Comment by TheTechnician27** [comment]
AAaaaaaah I made a typo on the comment now. One second.

**Review by Daniel-McCarthy — APPROVED** [review]

File: pcsx2-qt/Debugger/MemoryViewWidget.cpp [hunk 1]
```diff
@@ -277,9 +277,11 @@ bool MemoryViewTable::KeyPress(int key, QChar keychar)
 
 		if (keyCharIsText)
 		{
-			InsertIntoSelectedHexView(((u8)QString(QChar(key)).toInt(&pressHandled, 16)));
+			// Check if key pressed is hex before insertion (QString conversion fails otherwise)
+			u8 keyPressed = (u8)QString(QChar(key)).toInt(&pressHandled, 16);
 			if (pressHandled)
 			{
+				InsertIntoSelectedHexView(keyPressed);
```
Comment (refractionpcsx2) [inline pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: Hmm should the assigning (and declaration I guess) of keyPressed not be inside the if? like, what is pressHandled is null? The conversion will fail/throw an error potentially.  Also there's not much point in having it outside the if, if it's not used elsewhere.

You could also make it const.

Comment (TheTechnician27) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: > Hmm should the assigning (and declaration I guess) of keyPressed not be inside the if? like, what is pressHandled is null? The conversion will fail/throw an error potentially if it's not checked for assignment first. Also there's not much point in having it outside the if, if it's not used elsewhere.
> 
> You could also make it const.

If you're referring to the function call being inside of the 'if' block, that's because this would make that block dead code (it will never evaluate to true, as pressHandled is the status bit of our QString conversion). If you mean putting it in the condition itself, we could say ```if (u8 keyPressed = (u8)QString(QChar(key)).toInt(&pressHandled, 16) >= 0 && pressHandled)```, and this should work since we'll evaluate the conditional left to right and thus the assignment completes by the time 'pressHandled' is evaluated, but it feels far less readable.

That being said, I could make it const; after all, it won't be being used again. Would you like me to go ahead and do that, ref?

Comment (refractionpcsx2) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: oh that function is assigning 16 to pressHandled? my bad.

Comment (Daniel-McCarthy) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: The function that converts the key from QString toInt assigns the boolean reference passed in to a true or false depending on if the conversion worked (It won't if it's a non-hex string character). So it's setting the boolean the following if statement uses.

Personally I think it'd be less confusing to create a new boolean with a name that clarifies that it's validating the success of the conversion like `ok`, `isOK`, `isValidHex` but is probably fine.

Comment (TheTechnician27) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: > oh that function is assigning 16 to pressHandled? my bad.

My understanding of the passed &pressHandled is that it acts as a status bit for the conversion, while 16 acts as the numerical base. QString::toInt documentation can be seen [here](https://doc.qt.io/qt-6/qstring.html#toInt). Previously what we were doing is writing to the hex viewer by default no matter if the conversion succeeded or failed (it just returns 0 on failure) and then entering the conditional statement depending on the success/failure of the QString conversion.

Comment (F0bes) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: > The function that converts the key from QString toInt assigns the boolean reference passed in to a true or false depending on if the conversion worked (It won't if it's a non-hex string character). So it's setting the boolean the following if statement uses.
> 
> Personally I think it'd be less confusing to create a new boolean with a name that clarifies that it's validating the success of the conversion like `ok`, `isOK`, `isValidHex` but is probably fine.

It needs to set press handled because that communicates to the caller that this function handled the press.

**Review by F0bes — APPROVED** [review]

File: pcsx2-qt/Debugger/MemoryViewWidget.cpp (hunk 1 above)
Comment (Daniel-McCarthy) [reply pcsx2-qt/Debugger/MemoryViewWidget.cpp:284]: I see, good call. Makes sense with that context.

**Review by Mrlinkwii — APPROVED** [review]
