### PR TITLE
GS-HW: Expand target on EE write and improve overlap check

### LINKED ISSUE #5350: [BUG]: Castlevania: Curse of Darkness [NTSC-U] cutscene issues with subtitles in Hardware mode
### Describe the Bug

Castlevania: Curse of Darkness has an issue with the cutscenes if you are on hardware mode and have subtitles on, where the cutscene stutters after making a new line of subtitles appear.  

Example: https://youtu.be/7LnYmNGBvk8

### Reproduction Steps

Just be in hardware mode and have subtitles on.

### Expected Behavior

_No response_

### PCSX2 Revision

pcsx2-v1.7.2242-windows-64bit-AVX2

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7-10750H

### GPU

RTX 3070 laptop

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Allows the appending of targets from EE writes and improves the overlap check to make sure the given texture does actually overlap, not that the block point matches.

### Rationale behind Changes
Castlevania Curse of Darkness updates the FMV/Subtitles in chunks, drawing its border from the EE, and t his was getting missed causing the picture to be stretched, but also the overlap check was causing incorrect targets to be written to, causing the screen to flash whenever the subtitles changed since that target was then being missed later on.

### Suggested Testing Steps
Test games (especially FMVs), make sure nothing flickers or looks off.

Fixes #5350

Before:
image

After:
image

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -700,6 +700,45 @@ void GSTextureCache::ScaleTargetForDisplay(Target* t, const GIFRegTEX0& dispfb,
...
+			dst = t;
+			break;
+		}
+	}
+	
+	if (dst)
+	{
+		GSVector2i rect_scaled = GSVector2i(r.z * g_gs_renderer->GetUpscaleMultiplier(), r.w * g_gs_renderer->GetUpscaleMultiplier());
+		int upsc_width = std::max(rect_scaled.x, dst->m_texture->GetWidth());
+		int upsc_height = std::max(rect_scaled.y, dst->m_texture->GetHeight());
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:732]: All 3 can be const.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 2]
```diff
@@ -700,6 +700,45 @@ void GSTextureCache::ScaleTargetForDisplay(Target* t, const GIFRegTEX0& dispfb,
 	GetTargetHeight(t->m_TEX0.TBP0, t->m_TEX0.TBW, t->m_TEX0.PSM, static_cast<u32>(needed_height));
 }
 
+// Expands targets where the write from the EE overlaps the edge of a render target and uses the same base pointer.
+void GSTextureCache::ExpandTarget(const GIFRegBITBLTBUF& BITBLTBUF, const GSVector4i& r)
+{
+	GIFRegTEX0 TEX0;
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:707]: Extra line.
