### PR TITLE
x86emitter: Don't use xgetbv

### LINKED ISSUE #3647: Linux x86_64 build error on some hardware
***PCSX2 version:***
development builds v1.7.0-dev-20200830

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
When compiling PCSX2 on some build farm, some nodes will fail but others not:

The error is:

```
[   68s] /usr/lib64/gcc/x86_64-suse-linux/10/include/xsaveintrin.h:60:1: error: inlining failed in call to 'always_inline' 'long long int _xgetbv(unsigned int)': target specific option mismatch
[   68s]    60 | _xgetbv (unsigned int __A)
[   68s]       | ^~~~~~~
[   68s] /home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20200830/common/src/x86emitter/cpudetect.cpp:300:20: note: called from here
[   68s]   300 |         if ((xgetbv(0) & 6) == 6) // XFEATURE_ENABLED_MASK[2:1] = '11b' (XMM state and YMM state are enabled by OS).
[   68s]       |                    ^
[   68s] make[2]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/build.make:116: common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o] Error 1
[   68s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20200830/build'
[   68s] make[1]: *** [CMakeFiles/Makefile2:620: common/src/x86emitter/CMakeFiles/x86emitter.dir/all] Error 2
```

***How to reproduce the issue:***

***Last known version to work:***

***PC specifications:***
I don't know what CPU the build farm node is using...

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Fixes #3647

### CODE REVIEW

**Comment by beaumanvienna** [comment]
What about https://github.com/beaumanvienna/pcsx2/blob/4ea72891cd348f862ff0c561dc812000d61841f9/cmake/BuildParameters.cmake#L214 and https://github.com/beaumanvienna/pcsx2/blob/4ea72891cd348f862ff0c561dc812000d61841f9/cmake/BuildParameters.cmake#L220

**Comment by gregory38** [comment]
It would be nice to add a comment saying. That
"In theory we should check AVX OS support with xgetbv instructions. However all OSes from 10y ago support it. And xgetbv brings compiler flags mess" (I let you rephrase in nice English ;)

File: common/src/x86emitter/cpudetect.cpp [hunk 1]
```diff
@@ -297,12 +297,10 @@ void x86capabilities::Identify()
 
     if ((Flags2 >> 27) & 1) // OSXSAVE
     {
-        if ((xgetbv(0) & 6) == 6) // XFEATURE_ENABLED_MASK[2:1] = '11b' (XMM state and YMM state are enabled by OS).
-        {
-            hasAVX = (Flags2 >> 28) & 1; //avx
-            hasFMA = (Flags2 >> 12) & 1; //fma
-            hasAVX2 = (SEFlag >> 5) & 1; //avx2
-        }
+        // Note: In theory, we should use xgetbv to check OS support, but all OSes we officially run under support it, and it requires extra compiler flags to use the intrinsic for it
```
Comment (lightningterror) [inline common/src/x86emitter/cpudetect.cpp:300]: I'd split the comment in 2-3 lines to avoid horizontal scrolling.

**Review by lightningterror — APPROVED** [review]
