### PR TITLE
Qt: Fix a few memory card issues

### LINKED ISSUE #6299: [BUG]: Memcards menu bugged while in-game
### Describe the Bug

Memcard menu is bugged when in game

### Reproduction Steps

Open pcsx2, open a game, open memcard option and refresh

### Expected Behavior

Memcards recognized lol

### PCSX2 Revision

v.1.7.2855

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 5600x

### GPU

RTX 3060ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

image
this is ar tonelico

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Fixes cards showing up as "missing" in Qt's settings dialog if you opened the dialog after starting a game.

Fix empty/unplugged card detecting as folder (mostly cosmetic in log, it gets disabled, so it won't do anything anyway).

Cycle/autoeject memory cards when files change: Hopefully should fix card changes not getting picked up in some games.

Add swap memory card button: Self-explanatory.

### Rationale behind Changes

Fixing issues in Qt.

### Suggested Testing Steps

Test general memory card functionality, make sure nothing regressed.

Fixes #6299

### CODE REVIEW

File: common/FileSystem.cpp [hunk 1]
```diff
@@ -595,60 +596,71 @@ std::string Path::Combine(const std::string_view& base, const std::string_view&
...
+	switch (share_mode)
+	{
+		case FileSystem::FileShareMode::DenyNone:
+			share = FILE_SHARE_READ | FILE_SHARE_WRITE;
+			break;
+		case FileSystem::FileShareMode::DenyRead:
+			share = FILE_SHARE_WRITE;
+			break;
+		case FileSystem::FileShareMode::DenyWrite:
+			share = FILE_SHARE_WRITE;
```
Comment (CookiePLMonster) [inline common/FileSystem.cpp:614]: Intended? Looks like a mistake.

**Review by CookiePLMonster — CHANGES_REQUESTED** [review]

**Comment by stenzek** [comment]
> If you hit refresh on the memory card screen after booting a game your memory cards will show as "Formatted : No"

Should be fixed now. I noobed out with file share modes.

**Review by JordanTheToaster — APPROVED** [review]
