### PR TITLE
GS/HW: Rewrite invalidation function

### LINKED ISSUE #3351: Everybody's / Hot Shot series shadows issues
***PCSX2 version:***
v1.5.0-dev-3389-g6e22efe79

***PCSX2 options:***
Default, tried all GSDX hacks, all rounding/clamping modes. 

***Plugins used:***
Default that came with this version of pcsx2. SSE2, and AVX2 version of GSDX tested

***Description of the issue:***
This issue include 3 games, Hot Shot Tennins, and Hot Shot Golf 3/4 But gs dump came from Everybody's Golf / HST 4

Shadows aren't displayed in hardware mode. Causing major slowdown, making game unplayable in hardware mode at all. Is confirmed that is shadow issue, patch to remove them on EE side, make game work smooth again.

Hardware:
hardware

Software:
software

***How to reproduce the issue:***
Go in-game on any court / track

***Last known version to work:***
None, didn't tested below 1.4.0

***PC specifications:***
i5 4570, GTX1060 3GB, 8 GB ram

[snaps.zip](https://github.com/PCSX2/pcsx2/files/4568160/snaps.zip)

### LINKED ISSUE #8883: [BUG]: Radiata broken shadows in certain areas of the game
### Describe the Bug

Some shadows are broken in parts of the game. Target Partial Invalidation use to fix the issue now nothing seems to fix it. 

### Reproduction Steps

Start a new game and watch the camera pan by the fire place and observe the shadows. Or try the save state and gs dump. 

### Expected Behavior

Shadows should look fine like they always use to. 

### PCSX2 Revision

1.7.4521

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Deafault

### Emulation Settings

Default

### GS Window Screenshots

Screenshot (116)
Screenshot (115)

### Logs & Dumps

[Dump.zip](https://github.com/PCSX2/pcsx2/files/11524071/Dump.zip)

[SLUS-21262 (47B9B2FD).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/11524072/SLUS-21262.47B9B2FD.01.p2s.zip)

### LINKED ISSUE #9132: [BUG]: Wrestle Kingdom - health gages break
### Describe the Bug

the health gages break in game
does it in hardware
Wrestle Kingdom_SLPM-66401_20230630154343

### Reproduction Steps

start game
choose FREE FIGHT
play and lose
rematch (first option)
the health bars are screwd up

### Expected Behavior

Wrestle Kingdom_SLPM-66401_20230630154844

### PCSX2 Revision

1.7.4666

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[Wrestle Kingdom_SLPM-66401_20230630154343.gs.zip](https://github.com/PCSX2/pcsx2/files/11923165/Wrestle.Kingdom_SLPM-66401_20230630154343.gs.zip)

### LINKED ISSUE #9791: [BUG]: Dragon Quest VIII: graphical issue on cave walls.
### Describe the Bug

I just noticed it into the first cave walls so can't say it's a more widespread issue or not, but here it is

Dragon Quest VIII - L'Odissea del Re maledetto_SLES-53974_20230813235632

See those rectangles under the water. Those appear at native resolution too and in every renderer, only software renderer doesn't have this issue. 

I tested some options and it seems that setting CPU sprite render size to 1 and blended sprite triangles fixes it. 

### Reproduction Steps

Go to the first cave ingame and notice those weird crystal like rectangles near the cave walls.

### Expected Behavior

Clean cave walls textures. 

### PCSX2 Revision

pcsx2 1.7.4915

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

Gsdump

[Dragon Quest VIII - L'Odissea del Re maledetto_SLES-53974_20230813235632.zip](https://github.com/PCSX2/pcsx2/files/12330530/Dragon.Quest.VIII.-.L.Odissea.del.Re.maledetto_SLES-53974_20230813235632.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Overhauls a bunch of the GPU invalidation to try and make it suck less.

### Rationale behind Changes
It wasn't brilliant and broke down in many places.

### Suggested Testing Steps
Test anything you like, reports of broken games are welcome (and GS dumps) but this is WIP for now.

### TODO's
- [x] Remove the "Partial Target Invalidation" option from the UI, this option no longer does anything.
- [x] Remove above entries from GameDB

### Fixed things:

Fixes Indiana Jones as originally noted here #8971.
Fixes https://github.com/PCSX2/pcsx2/issues/9143 MGS3 garbage.
Fixes #8883 Radiata Stories fireplace shadows.
Fixes regression on Dark Cloud 2 faces.
Fixes Kung Fu Panda FMV's.
~~Fixes DNA - Dark Native Apostle shadows (now match SW)~~ This was still broken, but fixed in another PR which merged.
~~Fixes subtle bug in True Crime NYC~~ Fixed by another PR which merged.
Improves Z invalidation (required for FFX once #9302 merges).
Fixes #9791 by deleting old targets which are no longer valid.
Fixes problem with the "Winner" screen in Naruto Ultimate Ninja 3 (problem was exposed by v1.7.4882).
Improves reliability of Dragon Quest 8 rendering.
Improves Dog's Life, stop Jake turning in to a clown randomly.
Fixes #3351 shadows in Everybody's Golf/Tennis.
Mostly corrects the black screen in Katamari 2 player split screen #8353.
Fixes #9132 Wrestle Kingdom health bars breaking when doing a rematch.

### Broken things (currently):

~~Hitman Blood Money - Shows some rainbow texture in bottom right~~ Added hack, explained in [comments](https://github.com/PCSX2/pcsx2/pull/9315#issuecomment-1656810774)

### Broken and won't be fixed:
TOCA 3 reflections - It tries to read a misaligned target, so this is technically broken on master too, it just looks worse here, but the game is kinda broken anyway.
ATV Offroad Fury 2 - Will hang going ingame if you use hardware mode, this has *never* really worked, it just by some fluke didn't completely die. The game does complex moving between the frame and z buffer, then downloads it, this doesn't work in PCSX2, so the game doesn't know how to handle it. I recommend you use software mode for this game until it can be fixed/worked around.

### Dump runner shows broken but is fine normally:

MGS 3 - Depth of Field blur is missing in runner but is fine when run normally
Ape Escape 3 - Runner shows corrupted sky, looks fine normally

### Glamour shots:

Kung Fu Panda
Master:
image
PR:
image

Dark Cloud 2
Master:
image
PR:
image

Radiata Stories
Master:
image
PR:
image

Indiana Jones
Master:
image
PR:
image

### CODE REVIEW

**Comment by bigol83** [comment]
Mgs3 garbage fixed confirmed.
This makes DQVIII black side lines upscaling issue worse. In master they appear in some angles, with this PR they are there everytime.

**Comment by refractionpcsx2** [comment]
That's an upscaling problem, we'll just have to deal with that.

**Comment by CookiePLMonster** [comment]
Fixes a regression in The Getaway introduced in https://github.com/PCSX2/pcsx2/pull/8289#issuecomment-1639908477.

**Comment by refractionpcsx2** [comment]
I've added a GSC hack for Hitman - Blood Money (PAL only, NTSC is fine as it has room outside of the framebuffer, thanks to the 448 height) as the problem isn't this PR, but the problem is a failed channel shuffle which normally backs up the RGB of the last two pages of the framebuffer, then restores them on top of the uploaded texture, it's not really needed so skipped it for now until we fix the shuffle/copy properly.

This is the sequence of events:
Frame buffer = 0x2400->3200
Copies the colour out of the framebuffer for both pages (at 0x31c0 and 0x31e0)
TBP0:0x31c0 PSMT8 (red)  -> FBP (*32):0x3f40 CT32 alpha
TBP0:0x31e0 PSMT8 (red)  -> FBP (*32):0x3f60 CT32 alpha
TBP0:0x31c0 PSMT8 (green)-> FBP (*32):0x3f80 CT32 alpha
TBP0:0x31e0 PSMT8 (green)-> FBP (*32):0x3fa0 CT32 alpha
TBP0:0x31c0 PSMT8 (blue) -> FBP (*32):0x3fc0 CT32 alpha
TBP0:0x31e0 PSMT8 (blue) -> FBP (*32):0x3fe0 CT32 alpha

Upload to 0x31c0 -> 0x31ef 2 Pages CT32 (this goes in to 384,416->512,448 of framebuffer)

The *only* part kept of this, is the alpha.

Copy back
TBP0:0x3f40 PSMT8H -> FBP (*32):0x31c0 red
TBP0:0x3f60 PSMT8H -> FBP (*32):0x31e0 red
TBP0:0x3f80 PSMT8H -> FBP (*32):0x31c0 green
TBP0:0x3fa0 PSMT8H -> FBP (*32):0x31e0 green
TBP0:0x3fc0 PSMT8H -> FBP (*32):0x31c0 blue
TBP0:0x3fe0 PSMT8H -> FBP (*32):0x31e0 blue

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -370,6 +377,414 @@ void GSTextureCache::DirtyRectByPage(u32 sbp, u32 spsm, u32 sbw, Target* t, GSVe
...
+			in_rect.z = (in_rect.z + (src_info->pgs.x - 1)) & ~(src_info->pgs.x - 1);
+			in_rect.y = in_rect.y & ~(src_info->pgs.y - 1);
+			in_rect.w = (in_rect.w + (src_info->pgs.y - 1)) & ~(src_info->pgs.y - 1);
+		}
+	}
+
+	// Match the space for the width of the buffer, based on 64 pixels (1 page) for all formats, except PSMT8/4 which is half.
+	// So multiply the others when comparing, so we don't lose "off by 1 width" comparison.
+	int adjusted_src_width = (src_info->bpp >= 16) ? src_width * 2 : src_width;
+	int adjusted_dst_width = (dst_info.bpp >= 16) ? dst_width * 2 : dst_width;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:637]: Both can be constants.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 2]
```diff
@@ -846,10 +1261,16 @@ GSTextureCache::Source* GSTextureCache::LookupSource(const GIFRegTEX0& TEX0, con
...
 			if (t->m_used)
 			{
 				// Skip over targets that we're only keeping around for the alpha, when the RGB is now being used for depth.
-				if (!t->HasValidBitsForFormat(psm))
+				if (!t->HasValidBitsForFormat(psm) || !t->Overlaps(bp, bw, psm, r))
+					continue;
+
+				// If the BP is block offset it's unlikely to be a target, but a target can be made by a HW move, so we need to check for a match.
+				// Good for Baldurs Gate Dark Alliance (HW Move), bad for Tomb Raider Legends (just offset).
+				if(((bp & (BLOCKS_PER_PAGE - 1)) != (t->m_TEX0.TBP0 & (BLOCKS_PER_PAGE - 1))) && (bp & (BLOCKS_PER_PAGE - 1)))
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1273]: Space after if.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 3]
```diff
@@ -1351,7 +1772,7 @@ GSTextureCache::Target* GSTextureCache::LookupTarget(GIFRegTEX0 TEX0, const GSVe
 					continue;
 				}
 				list.MoveFront(i.Index());
-
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1775]: Whitespace.

**Comment by bigol83** [comment]
Checked the latest PR updates and now this happens in Dragon Quest VIII

Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230813132654

It's the video that plays after the tutorial battle when the party goes to the first town. It looks like that. Checked latest Master too and it's not an issue with that.

**Comment by refractionpcsx2** [comment]
aw man, are you serious? FML :(

**Comment by bigol83** [comment]
Sorry. 😢

**Comment by bigol83** [comment]
Tested it again with latest updates and it is fixed. Just played a bit more until the first cave and there are no regressions compared to Master now.

**Comment by refractionpcsx2** [comment]
Okay I'm done with this, testing would be appreciated, it's some pretty huge changes.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 4]
```diff
@@ -370,167 +384,334 @@ void GSTextureCache::DirtyRectByPage(u32 sbp, u32 spsm, u32 sbw, Target* t, GSVe
...
+				sbp += h_page_offset << 5;
 			}
 		}
-		else if (static_cast<int>(src_pgw) == rect_pages.width())
-		{
-			const u32 totalpages = rect_pages.width() * rect_pages.height();
-			const bool full_rows = in_rect.width() == static_cast<int>(src_pgw * src_page_size.x);
-			const bool single_row = in_rect.x == 0 && in_rect.y == 0 && totalpages <= dst_pgw;
-			const bool uneven_pages = (horizontal_offset || (totalpages % dst_pgw) != 0) && !single_row;
+		int vertical_offset = (inc_vertical_offset / src_info->pgs.y) * src_pg_width;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:499]: Constant.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 5]
```diff
@@ -370,167 +384,334 @@ void GSTextureCache::DirtyRectByPage(u32 sbp, u32 spsm, u32 sbw, Target* t, GSVe
...
+	const bool block_matched_format = matched_format && block_aligned_rect;
+	const bool req_depth_offset = (src_info->depth > 0 && !page_aligned_rect);
+
+	// If there is block offset left over, try to adjust to that.
+	if (block_matched_format && (block_offset || req_depth_offset))
+	{
+		if (block_offset > 0 || req_depth_offset)
+		{
+			int xblocks = in_rect.width() / src_info->bs.x;
+			int yblocks = in_rect.height() / src_info->bs.y;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:517]: These two as well.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 6]
```diff
@@ -370,167 +384,334 @@ void GSTextureCache::DirtyRectByPage(u32 sbp, u32 spsm, u32 sbw, Target* t, GSVe
...
 
-			const SurfaceOffset so = ComputeSurfaceOffset(sok);
-			if (so.is_valid)
-				AddDirtyRectTarget(t, so.b2a_offset, t->m_TEX0.PSM, t->m_TEX0.TBW, rgba);
-			return;
-		}
+	// Match the space for the width of the buffer, based on 64 pixels (1 page) for all formats, except PSMT8/4 which is half.
+	// So multiply the others when comparing, so we don't lose "off by 1 width" comparison.
+	int adjusted_src_width = (src_info->bpp >= 16) ? src_width * 2 : src_width;
+	int adjusted_dst_width = (dst_info->bpp >= 16) ? dst_width * 2 : dst_width;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:581]: And these.

**Comment by bigol83** [comment]
The FMV issue is back. 😆

Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230815001452

**Comment by refractionpcsx2** [comment]
Goddamnit, I thought I'd tried that 😩

**Comment by refractionpcsx2** [comment]
okay thanks to a bit of jiggling and refactoring by Stenzek, the DQ8 situation is solved and he got rid of a bug I made for myself xD

**Comment by bigol83** [comment]
So, just tested a bit, both on start and in cave in Dragon Quest VIII. All is good. Video after tutorial battle plays as it should, no graphical issue on cave walls. Also checked MGS3 to confirm that the garbage when skipping cutscene was still fixed, and indeed it still is. 

Great PR and great job.

**Comment by refractionpcsx2** [comment]
Excellent :) I  do have some more changes coming to fix Valkyrie Profile 2, but this is gonna be a bunch of major changes so it might need checking again xD

**Comment by bigol83** [comment]
I noticed that stenzek DqVIII Pr still has the cave walls graphical issue, is it normal, or something i need to specifiy in his PR?

**Comment by RedDevilus** [comment]
That's a different part that will combine with this PR to further fix DGQ8. As that one is master with those codechangea without validation code. So if they get both merged. Should be fine.

**Comment by bigol83** [comment]
> That's a different part that will combine with this PR to further fix DGQ8. As that one is master with those code changes without validation code. So if they get both merged. Should be fine.

Ah, ok.

**Comment by refractionpcsx2** [comment]
What a day, I've spent nearly the last 24 hours on this, but I think I've worked out all the regressions and got Valkyrie Profile 2 not-broken.

As a bonus this seems to have been fixed on the dumps at least.

Area 51:
Master:
image
PR:
image


If this new commit sucks, I will revert it, so I'm going to keep it separate.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 7]
```diff
@@ -2054,6 +2054,13 @@ void GSRendererHW::Draw()
 						ds_end_bp, m_cached_ctx.ZBUF.PSM);
 				}
 
+				GSUploadQueue clear_queue;
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2057]: What's happening here? Wouldn't we want to remove contained transfers from the queue, not add more to it?

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 8]
```diff
@@ -2197,10 +2204,18 @@ void GSRendererHW::Draw()
...
 
-		src = tex_psm.depth ? g_texture_cache->LookupDepthSource(TEX0, env.TEXA, MIP_CLAMP, tmm.coverage, possible_shuffle, m_vt.IsLinear(), m_cached_ctx.FRAME.Block()) :
-								g_texture_cache->LookupSource(TEX0, env.TEXA, MIP_CLAMP, tmm.coverage, (GSConfig.HWMipmap >= HWMipmapLevel::Basic || GSConfig.TriFilter == TriFiltering::Forced) ? &hash_lod_range : nullptr, possible_shuffle, m_vt.IsLinear(), m_cached_ctx.FRAME.Block());
+		src = tex_psm.depth ? g_texture_cache->LookupDepthSource(TEX0, env.TEXA, MIP_CLAMP, tmm.coverage, possible_shuffle, m_vt.IsLinear(), m_cached_ctx.FRAME.Block(), req_color, req_alpha) :
+								g_texture_cache->LookupSource(TEX0, env.TEXA, MIP_CLAMP, tmm.coverage, (GSConfig.HWMipmap >= HWMipmapLevel::Basic || GSConfig.TriFilter == TriFiltering::Forced) ? &hash_lod_range : nullptr,
+															possible_shuffle, m_vt.IsLinear(), m_cached_ctx.FRAME.Block(), req_color, req_alpha);
 
+		if (src && !src->IsFromTarget() && GSUtil::GetChannelMask(src->m_TEX0.PSM) == 0xf && TEX0.TBP0 != m_cached_ctx.FRAME.Block() && TEX0.TBP0 != m_cached_ctx.ZBUF.Block())
+		{
+			// Kill any possible targets we missed, they might be wrong now.
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2216]: Doing this when it hits the source map seems a bit questionable. Maybe it'd be better in CreateSource().

But I'm still wondering why it's a thing. Shouldn't invalidation take care of removing any targets?

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 9]
```diff
@@ -2781,7 +2797,11 @@ void GSRendererHW::Draw()
 	// Temporary source *must* be invalidated before normal, because otherwise it'll be double freed.
 	g_texture_cache->InvalidateTemporarySource();
 
-	//
+	// Set the RT format back to 32bits after the shuffle.
+	if (rt && m_texture_shuffle && rt->m_32_bits_fmt && GSLocalMemory::m_psm[rt->m_TEX0.PSM].bpp == 16)
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2801]: Shouldn't the RT not be having the format changed in the first place?

Unless it's a new target, I guess. In which case, we could gate this with `TEX0.TBP0 != FRAME.Block()`.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp (hunk 7 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2057]: The problem is, this was happening and killing the target, then doing a draw with the alpha masked, so there was no way to know the alpha was valid.  What I'm thinking however, is adding a variable to the GSUploadQueue so it doesn't actually upload anything, just marks that there was a clear in that format.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp (hunk 8 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2216]: Targets don't always get completely overridden, for example it will make a 640x224 texture to do some sort of screen copy thing, then it will toss that out by writing a 128x128 texture over it. Do we keep the old target around? I don't think we should, it'll cause nothing but problems, but invalidation won't know that.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp (hunk 9 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2801]: Uhhh, I can't remember the scenario, but this has always been a problem xD I think it was a new target, but this has been safe, so far.

But I can gate it, if you want.   I'll run a dump with some logging to check the TBP & FBP first to see what games are hitting it.

File: pcsx2/GS/GSState.cpp [hunk 10]
```diff
@@ -3679,10 +3682,13 @@ GSState::TextureMinMaxResult GSState::GetTextureMinMax(GIFRegTEX0 TEX0, GIFRegCL
 		{
 			st += GSVector4(-0.5f, 0.5f).xxyy();
 			
+			GSVector4 rect_start = m_vt.m_min.t;
+			rect_start.x = std::floor(rect_start.x);
+			rect_start.y = std::floor(rect_start.y);
```
[the remark this answers is not in the document]
Comment (refractionpcsx2) [reply pcsx2/GS/GSState.cpp:3687]: well what do you know, I didn't realise there was a floor function lol.

I'll add that

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp (hunk 7 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: Okay I did some modification so it only stores it on zero clears and it uses it to skip preloading the RT rather than the usual use of the transfer list

**Comment by MarioSonic2987** [comment]
Fixes missing level name when you open the map in Sly Raccoon (or Sly Cooper and the Thievius Raccoonus) in HW.

**Master**:

image

**PR**:

image

**Comment by refractionpcsx2** [comment]
nice! thanks :)

**Comment by iMineLink** [comment]
Amazing rewrite!!

**Comment by refractionpcsx2** [comment]
Thanks :D It's a bit messier than I hoped, but it works pretty well lol

**Comment by coornio** [comment]
It appears that Dark Cloud 2 is not 100% fixed by this. When starting a new playthrough, during the cutscene of Cedric meeting with Mayor Need for the first time, sometime after the first boss fight (Linda), for that very first scene where the camera pans along to show the mayor, his face turns black and back to normal after a couple seconds. I unfortunately didn't catch a savestate prior to it, so I'll need to perform another start to find it again.

**Comment by refractionpcsx2** [comment]
if you could, that'd be great

**Comment by bigol83** [comment]
> It appears that Dark Cloud 2 is not 100% fixed by this. When starting a new playthrough, during the cutscene of Cedric meeting with Mayor Need for the first time, sometime after the first boss fight (Linda), for that very first scene where the camera pans along to show the mayor, his face turns black and back to normal after a couple seconds. I unfortunately didn't catch a savestate prior to it, so I'll need to perform another start to find it again.

I can't reproduce this issue, i have the PAL version. 

Is this the scene you are talking about?

https://github.com/PCSX2/pcsx2/assets/38129260/33ab55b7-d947-4b10-815d-a6b82aa0835b

**Comment by coornio** [comment]
> > It appears that Dark Cloud 2 is not 100% fixed by this. When starting a new playthrough, during the cutscene of Cedric meeting with Mayor Need for the first time, sometime after the first boss fight (Linda), for that very first scene where the camera pans along to show the mayor, his face turns black and back to normal after a couple seconds. I unfortunately didn't catch a savestate prior to it, so I'll need to perform another start to find it again.
> 
> I can't reproduce this issue, i have the PAL version.
> 
> Is this the scene you are talking about?
> Dark.Chronicle_SCES-51190_20231028215607.mp4

I wanna say yes, judging by the audio, as there's no video at all, likely intentionally for small size?
Either way, I will try a fresh game tomorrow and see if I can't get it to trigger again.

**Comment by bigol83** [comment]
Wait a few seconds, it will show the video. At least i see it on my side.

**Comment by coornio** [comment]
Yeah the video is still broken when I try to view it, just audio. Nevertheless, I got back to the point in question.

https://www.mediafire.com/file/hznkfebkuenoe7k/Dark+Cloud+2_SCUS-97213_20231029122031.gs.zst/file
Dark Cloud 2_SCUS-97213_20231029122031

Here's also a memcard save. Load up, go inside and speak to Cedric to start the fight with Linda, pummel her and proceed to the next floor, and the cutscene will play.
[test.zip](https://github.com/PCSX2/pcsx2/files/13197781/test.zip)

**Comment by bigol83** [comment]
I can't check ingame since i don't have the NTSC version but only PAL version. But downloading the gsdump i can see the issue too. 

Anyway, here is how it shows on my side with PAL version, it has no issues.

https://github.com/PCSX2/pcsx2/assets/38129260/7f6f06ec-3a3b-498f-a8d8-ce9370e4f5d5
