### PR TITLE
GS/HW: Detect shuffles using quads

### LINKED ISSUE #8203: [BUG]: Glitchy cutscene screen in tokyo xrteme racer drift 2
### Describe the Bug

the screen completely breaks when a racer cutscene occurs

### Reproduction Steps

just play the game until a cutscene pops up, it usually happens the most with racer cutscenes

### Expected Behavior

broken screen
Screenshot (861)

### PCSX2 Revision

1.7.4117

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

ryzen 5 3600

### GPU

gtx 1650 super

### GS Settings

widesceen
fmv widescreen
enable widescreen
anti blur
vsync
enable no interlace
disable interlace offset

6x native
af 16x
blending high
texture preloading ful

### Emulation Settings

mtvu
cheats

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Detect triangle quads used for shuffles.

### Rationale behind Changes
We only checked for sprites before, so this fixes that.  We do still treat it like sprites when processing further on, but it doesn't seem to matter, so YOLO.

### Suggested Testing Steps
Test Toyko Xtreme Racer Drift 2, nothing else showed in dump run.

Fixes #8203

Hard to see as it's a fade, but this is Toyko Xtreme Racer Drift 2
Master:
Tokyo_Xtreme_Racer_Drift_2_SLUS-21394_20230217234730_frame3
PR:
Tokyo_Xtreme_Racer_Drift_2_SLUS-21394_20230217234730_frame3

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -2680,6 +2680,7 @@ void GSRendererHW::Draw()
 				src->m_from_target->UnwrappedEndBlock() > m_cached_ctx.FRAME.Block()) ||
 				(m_cached_ctx.FRAME.Block() < src->m_from_target_TEX0.TBP0 && draw_end > src->m_from_target_TEX0.TBP0));
 
+			const bool sprite_or_quad = draw_sprite_tex || (m_vt.m_primclass == GS_TRIANGLE_CLASS && ((m_index.tail % 6) == 0 && TrianglesAreQuads(true)));
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2683]: I'm a little concerned about the performance impact of doing this on every draw. I know it's messier, but if you moved this directly into the condition on line 2694, it'd at least short circuit exit in most cases.

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: Alright, I've rearranged it so it's the very last thing it attempts to check when seeing if it's a shuffle

**Review by JordanTheToaster — APPROVED** [review]

**Comment by GitHub-Khi** [comment]
WWE SmackDown! vs. Raw 2006 and WWE SmackDown! vs. Raw 2007 seem to have these broken shuffle problems as well, or am i thinking in the wrong direction? (One of the several issues from [#3636](https://github.com/PCSX2/pcsx2/issues/3636))

Hollywood Hulk Hogan Entrance & Matrix Effect Finisher:
[WWE SmackDown! vs. Raw 2006_SLUS-21286_20240427105631.zip](https://github.com/PCSX2/pcsx2/files/15137691/WWE.SmackDown.vs.Raw.2006_SLUS-21286_20240427105631.zip)
[WWE SmackDown! vs. Raw 2006_SLUS-21286_20240427105737.zip](https://github.com/PCSX2/pcsx2/files/15137692/WWE.SmackDown.vs.Raw.2006_SLUS-21286_20240427105737.zip)

Hollywood Hulk Hogan Entrance:
[WWE SmackDown! vs. Raw 2007_SLUS-21427_20240427110033.zip](https://github.com/PCSX2/pcsx2/files/15137693/WWE.SmackDown.vs.Raw.2007_SLUS-21427_20240427110033.zip)

**Comment by JordanTheToaster** [comment]
> WWE SmackDown! vs. Raw 2006 and WWE SmackDown! vs. Raw 2007 seem to have these broken shuffle problems as well, or am i thinking in the wrong direction? (One of the several issues from [#3636](https://github.com/PCSX2/pcsx2/issues/3636))
> 
> Hollywood Hulk Hogan Entrance & Matrix Effect Finisher: [WWE SmackDown! vs. Raw 2006_SLUS-21286_20240427105631.zip](https://github.com/PCSX2/pcsx2/files/15137691/WWE.SmackDown.vs.Raw.2006_SLUS-21286_20240427105631.zip) [WWE SmackDown! vs. Raw 2006_SLUS-21286_20240427105737.zip](https://github.com/PCSX2/pcsx2/files/15137692/WWE.SmackDown.vs.Raw.2006_SLUS-21286_20240427105737.zip)
> 
> Hollywood Hulk Hogan Entrance: [WWE SmackDown! vs. Raw 2007_SLUS-21427_20240427110033.zip](https://github.com/PCSX2/pcsx2/files/15137693/WWE.SmackDown.vs.Raw.2007_SLUS-21427_20240427110033.zip)

Unrelated to this.

**Comment by GitHub-Khi** [comment]
I see. I just thought because the current problems in these games looks pretty similar.

**Comment by refractionpcsx2** [comment]
I'm looking in to those now, they are shuffle problems, but a different one, which gets broken by an old hack.  I'm making sure removing the old hack doesn't regress anything, I'll PR that separately.
