### PR TITLE
GS-HW: Improve FBW=1 clear for Singstar, NARC, Brave, State of Emergency 2 games

### LINKED ISSUE #3180: FBW-based Screen Clear Issue
**Games Tested:**
- [x] Evil Dead: Fist Full of Boomstick ([dump](https://dumps.pcsx2.net/index.php/s/6gmFTEzojKDixfr))
- [x] Tom And Jerry: War of The Whiskers ([dump](https://dumps.pcsx2.net/index.php/s/wATsw9Bt6K3GAmc))
- [x] Narc ([dump](https://dumps.pcsx2.net/index.php/s/9a9ttHbL35Nw4c9))
- [x] State of Emergency 2 ([dump](https://dumps.pcsx2.net/index.php/s/sSa6WyR4FgJktkF))
- [x] Singstar ([dump](https://github.com/PCSX2/pcsx2/files/5234657/gsdx_20200916145406.gs.zip))

**Games Not Tested (but potentially have the same issue):**
- State of Emergency
- Brave: The Search for Spirit Dancer
- The Powerpuff Girls: Relish Rampage

Example of the Issue:
image

**Cause:**
Caused by a screen clear where the game attempts to clear a 32-bit GS texture by setting the frame buffer width to 1 and then drawing a 64x2048 quad with flat shading in order to clear the buffer to a specific color (often a pink color).

Basically because of how GS memory works, it is possible on the GS to write to the framebuffer with FBW of 1 and then starting writing again with a larger FBW value. However since the cache does not emulate this behavior, what results is a larger line on the left hand of the screen.
_00454_f5001_rt1_03200_C_32

Here is an example of the incoming vertices:
```
VERTEX COORDS (XYZ)
	v0: 0.0000, 0.0000, 0
	v1: 64.0000, 2048.0000, 0

VERTEX COLOR (RGBA)
	v0: 000, 000, 000, 000
	v1: 239, 061, 239, 061
```

Here is an example FRAME register setting for the clear:
```
FRAME
	FBP (*32):0x2e00
	FBW:1
	PSM:0x0
	FBMSK:0x0
```

Here is an example of the FRAME register setting for a latter draw:
```
FRAME
	FBP (*32):0x2e00
	FBW:10
	PSM:0xa
	FBMSK:0x0
```

Previously, Superman Returns was the only game known to have this issue.

### LINKED ISSUE #5444: [BUG]: SLUS 21127 (Brave: The Search for Spirit Dancer) showing green lines along geometry
### Describe the Bug

ps2 brave

As you can see, there are green lines along the geometry in a specific distance, travelling with the camera. This is a regression as it did not happen in older builds, but I did not bisect or check which version works again.

I would rate the severity as minor. It does not harm gameplay but it is annoying to look at.

ps2 brave sun 2

Sometimes, you can also see the sun through solid rock, which is also a regression and may or may not be related, but it appears green-ish in color at certain angles, too which is why I am also putting these screenshots here, just to be safe.

ps2 brave sun

Sun without the green skeleton-thingy. It was super hard to capture the sun doing that.

### Reproduction Steps

These issues are all reproducible in the very first stage of the game. Just escape from the bear (trivial) and run and jump around a bit. Especially if you jump near the cave leading to the first cave painting, you will see the sun for a fraction for a second which almost looked like some indicator but it is not.

You can also face the cave entry and just move the camera a bit.

The green lines are also reproducible in the opening scene where you can see the squirrel.

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.2300-1 (git master)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 1600af

### GPU

AMD rx 570 (OC version with 8 GB of VRAM)

### GS Settings

Config files taken from `~/.config/PCSX2/inis`, I had to change the extension to txt because github does not like ini files apparently.

[GSdx.txt](https://github.com/PCSX2/pcsx2/files/7975082/GSdx.txt)
[GS.txt](https://github.com/PCSX2/pcsx2/files/7975083/GS.txt)

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7975070/emuLog.txt)

The repeated GTK warnings are me opening the graphics settings and playing around, also switching to Vulkan and back because it did not change anything except lower the framerate dramatically. Also tried changing blending accuracy (even if it is set to Full) because Jak II had very similar issues with stretched shadows, but it did not change anything.

gs_20220201015939
[gs_20220201015939.gs.gz](https://github.com/PCSX2/pcsx2/files/7975200/gs_20220201015939.gs.gz)

For the green line thing only, not the sun. I had to unxz the gs dump and gzip it instead because github also dislikes xz

### LINKED ISSUE #5845: [BUG]: NARC (SLUS-20730): Broken shadow.
### Describe the Bug

Shadow has large puppet line attached to the models. The game is known to only work properly in SW renderer, thus the issue only affected hardware renderers.

### Reproduction Steps

Booting the game in any of the hardware renderers.

### Expected Behavior

Shadows should be cast properly, with no puppet-like line attached to the player model. much like in SW renderer.

### PCSX2 Revision

v1.7.2579

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Debian testing

### CPU

Intel Core i5-4460

### GPU

Intel HD Graphics 4600

### GS Settings

Screenshot from 2022-04-11 10-00-54
Screenshot from 2022-04-11 10-00-57

### Emulation Settings

Screenshot from 2022-04-11 10-01-24

### GS Window Screenshots

HW renderer
Screenshot from 2022-04-10 17-17-51
SW renderer.
Screenshot from 2022-04-10 17-17-54

### Logs & Dumps

[gs_20220410172118_NARC _NTSC-U__SLUS-20730.zip](https://github.com/PCSX2/pcsx2/files/8460746/gs_20220410172118_NARC._NTSC-U__SLUS-20730.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adjusts the clear behaviour when the draw actually happens to not suck so much.  The loading screen is still broken, but this fixes all the menus etc.

Also Extends the clears to handle one which is alpha blended , which gets used for shadows in games such as Brave, Narc, State of Emergency 2.

### Rationale behind Changes
It sucked so much, didn't handle a whole load of cases.

### Suggested Testing Steps
Test games that do double half clear, like Burnout, Superman, Haunting Ground, maybe? idk, not sure what other ones do FBW=1

Do note this is basically hacks and heuristics to get around how the game reacts with the hardware texture cache, which does not handle this properly and fundamentally can't because of how the hardware renderer works.  Hopefully it's safe enough however.

Fixes #3180 best we can until a drastic change is made to the HW renderer, or some much heavier heuristics. But this seem to be safe enough for now.
Fixes #5845
Fixes #5444

### CODE REVIEW

**Comment by RedDevilus** [comment]
Before/Master:
image
image


After/PR:
image
image
image


Reference with software renderer:
SingStar Pop Hits_SCES-54570_20230203034955

**Comment by seta-san** [comment]
Meta issue
https://github.com/PCSX2/pcsx2/issues/3180

**Comment by refractionpcsx2** [comment]
Also Fixes Brave and Tom & Jerry

Brave:

Master:
image

PR:
image

Tom & Jerry:

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
Narc also fixed (but will require Mipmap + trilinear adding to the DB also for some other jankness)

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
And State of Emergency

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
Narc:

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
Brave:

Master:
image

PR:
image

**Review by lightningterror — APPROVED** [review]
Tested dumps, looks good.

**Comment by seta-san** [comment]
was my dump from Enders checked? https://github.com/PCSX2/pcsx2/issues/3180#issuecomment-742749129

**Comment by JordanTheToaster** [comment]
> was my dump from Enders checked? [#3180 (comment)](https://github.com/PCSX2/pcsx2/issues/3180#issuecomment-742749129)

It looked fine on master to me.

**Comment by seta-san** [comment]
okay. zoe looked like it had the issue.
gsdx_20201210133535
101763187-0ea9f900-3aa4-11eb-8c42-f151b09ac71a

**Comment by refractionpcsx2** [comment]
I checked the zoe dump, it was already fine on master

**Comment by seta-san** [comment]
> I checked the zoe dump, it was already fine on m

cool. i wonder what they stripe on the left is then.

**Comment by refractionpcsx2** [comment]
Oh I only had the top dump. But yeah, dunno, could be similar but not the same

**Comment by seta-san** [comment]
> Oh I only had the top dump. But yeah, dunno, could be similar but not the same

the top one has the same stripe. it's just harder to see.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -4370,17 +4384,20 @@ bool GSRendererHW::OI_BlitFMV(GSTextureCache::Target* _rt, GSTextureCache::Sourc
...
+}
 
-bool GSRendererHW::IsConstantDirectWriteMemClear()
+bool GSRendererHW::IsConstantDirectWriteMemClear(bool include_zero)
 {
 	// Constant Direct Write without texture/test/blending (aka a GS mem clear)
 	if ((m_vt.m_primclass == GS_SPRITE_CLASS) && !PRIM->TME // Direct write
-		&& (!PRIM->ABE || IsOpaque() || m_context->ALPHA.IsCdOutput()) // No transparency
-		&& (m_context->FRAME.FBMSK == 0) // no color mask
+		&& (m_context->FRAME.FBMSK == 0 || (include_zero && m_vt.m_max.c.eq(GSVector4i(0)))) // no color mask
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:4396]: `GSVector4i::zero()` (so it calls `_mm_setzero_epi32()` instead of `_mm_set1_epi32`).. it'll probably optimize to it anyway though

**Review by stenzek — APPROVED** [review]
