### PR TITLE
GS: Compensate for misaligned partial 24bit local->host transfers

### LINKED ISSUE #8146: [BUG]: Messed up background color on the Pause menu (Keroro Gunso - Mero Mero battle Royale, SLPS-25399)
### Describe the Bug

In Keroro Gunso - Mero Mero Battle Royale, during a match in-game if you pause the game, on the lower 3/4 half of the background the colors looks all wrong, this only happens when the game is paused. Tested with both SW and HW mode, the glitch persist. To provide a bit of context, the glitch has been there for ages, even dating back to the 1.6 version. According to @refractionpcsx2, this could be a GS Download issue.

Here's the screenshot:
Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214113828

And video recording:

https://user-images.githubusercontent.com/14798312/218643717-2cf807ce-a62e-4548-a90e-b5d59ad4b2e2.mp4

### Reproduction Steps

1. Boot up the game.
2. Go to any match in-game.
3. Once you're in the match, pause the game.
4. Observe the lower part of the background color (should be very noticeable).

### Expected Behavior

The color shouldn't look wrong

Screenshot during normal gameplay:
Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214102750

### PCSX2 Revision

v1.7.4080

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

Most settings are default apart from dithering being disabled, setting blending accuracy to full (tested with Basic, doesn't affect the issue),16:9 aspect ratio and changes to Internal Resolution. Vulkan are the renderer in use.

Display:
Screenshot_20230214_114703

Rendering:
Screenshot_20230214_114746

### Emulation Settings

The only changes are enabling Cheats, Optimal Frame Pacing and Scale to Host Refresh Rate

Screenshot_20230214_114848

### GS Window Screenshots

Screenshot_20230214_115156

### Logs & Dumps

Here is the GS Dump (You might have to extract it first):
[Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214102750.zip](https://github.com/PCSX2/pcsx2/files/10728903/Keroro.Gunsou.-.Mero.Mero.Battle.Royale_SLPS-25399_20230214102750.zip)

### LINKED ISSUE #8441: [BUG]: We love katamari (SLPS-25467) |  A color of bottom of the screen during screen trantision is glitched.
### Describe the Bug

A color of bottom of the screen during screen trantision is glitched.
this happen with Both renderer, and no Hardware fixes works.
Minna Daisuki Katamari Damacy_SLPS-25467_20230319230301

### Reproduction Steps

If you have an savedata, select collection (Blue katamari)
you have to beat tutorial if you don't have it.

### Expected Behavior

a

### PCSX2 Revision

Nightly - v1.7.4252

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[WLK_sc_un_gli.zip](https://github.com/PCSX2/pcsx2/files/11011231/WLK_sc_un_gli.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Compensates for misaligned transfers which generally happen with 24bit transfers when the transfer is split.

### Rationale behind Changes
In Keroro Gunso and We Love Katamari it downloads the 24 bit framebuffer in 2 parts, but it ends the first transfer 1 channel in to the 3 channel pixel, meaning it's offset strangely when it does the second part of the transfer.  So to compensate for this we do the whole pixel it ends on, then do an offset on the second part of the transfer, this stops the colours being incorrect as a bar across the bottom.

### Suggested Testing Steps
Test Keroro Gunso - Mero Mero Battle Royale pause screen and We Love Katamari Damacy transition in to the collection.

Keroro Gunso:  (There is another issue I need to solve with HW mode where the download fails first time, need to investigate)
Master:
image

PR:
image

We Love Katamari:
Master:
image

PR:
image

Fixes #8146
Fixes #8441

### CODE REVIEW

File: pcsx2/GS/GSLocalMemoryMultiISA.cpp [hunk 1]
```diff
@@ -1005,16 +1005,23 @@ void GSLocalMemoryFunctions::ReadImageX(const GSLocalMemory& mem, int& tx, int&
 
 		case PSM_PSMCT24:
 		case PSM_PSMZ24:
-			readWriteHelper(mem.vm32(), tx, ty, len / 3, 1, sx, w, off.assertSizesMatch(GSLocalMemory::swizzle32), [&](auto& pa, int x)
+		{
+			u32 length = len / 3;
+			u32 aligned_length = (len + 2) / 3;
```
Comment (lightningterror) [inline pcsx2/GS/GSLocalMemoryMultiISA.cpp:1010]: Both can be constants.

**Comment by kamfretoz** [comment]
Tested Keroro Gunso again this PR again, and it seems that its still somewhat broken :(

Screenshot_20230320_091640

**Review by lightningterror — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
As I said in the OP "There is another issue with hardware mode", however that wasn't it... that looks like the second half of the transfer just didn't happen, wtf...

**Comment by SeruranBlue** [comment]
I tested We Love Katamari and it is fixed.

**Comment by refractionpcsx2** [comment]
Thanks for testing!
