### PR TITLE
CDVD: Reload game data when swapping discs to reflect new name.

### LINKED ISSUE #8275: [BUG]: Save State doesn't work when swapping a disc
### Describe the Bug

This used to work with older versions of pcsx2 well before the UI change for sure.
This is how i noticed this issue, when starting code breaker 10 selecting cheats and swapping the disc the save state that is created isn't the crc of the swapped disc no it's the crc of  code breaker 10 (5207cca3 (5207CCA3).01) so when you start the game the game crashes when you try to lead the save state.

### Reproduction Steps

Starting code braker swapping the disc and creating a save state.
restarting the emulator selecting the game and try to load a save state the emulator will crash.

### Expected Behavior

Before the UI change it didn't crate the first boot crc save state file it created the swapped disc state file.

### PCSX2 Revision

1.7.4150

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Reloads disc information when a disc swap occurs

### Rationale behind Changes
Some people were asking for it so they could see what disc they were on (and discord rich presence ofc).
Also if you do a savestate after swapping disc, it wouldn't let you reload it unless you restart the game.

Funny side effect on Monster Rancher 4 when using Saucer Discs is that it will show the name for the game you insert if there are any, but it shouldn't load any new patches, but it will load gamefixes which might cause it to crash, but it's the best I could do.  However if a game requires a patch, you won't be able to load it with codebreaker, I'm sorry but I can't risk loading patches, it could completely break games like Monster Rancher.

### Suggested Testing Steps
Test games with disc swaps and make sure the name etc changes and savestates are related to the disc you have in.

Fixes #8275

### CODE REVIEW

File: pcsx2/VMManager.cpp [hunk 1]
```diff
@@ -746,23 +746,26 @@ void VMManager::UpdateRunningGame(bool resetting, bool game_starting)
 	Console.WriteLn(Color_StrongGreen, fmt::format("  Serial: {}", s_game_serial));
 	Console.WriteLn(Color_StrongGreen, fmt::format("  CRC: {:08X}", s_game_crc));
 
-	UpdateGameSettingsLayer();
-	ApplySettings();
+	if (!swapping_disc)
+	{
+		UpdateGameSettingsLayer();
```
Comment (stenzek) [inline pcsx2/VMManager.cpp:751]: Are you sure about this? If the disc being swapped to has a different serial, we'd probably want to apply the latter's gamesettings/ini.

Comment (refractionpcsx2) [reply pcsx2/VMManager.cpp]: I'd already fixed that but forgot to push it lol

**Review by stenzek — APPROVED** [review]
Code LGTM, untested
