### PR TITLE
GS: Ignore 24bit on DATE and Handle Reversed Color and Z

### LINKED ISSUE #473: Power Drome Z Buffer Clear
http://forums.pcsx2.net/Thread-Bug-Report-Power-Drome-NTSC-U-SLUS-20978
http://forums.pcsx2.net/Thread-GSdx?page=474 
http://forums.pcsx2.net/Thread-Power-Drome-SLUS-20978-U

### LINKED ISSUE #5078: [BUG]: Need For Speed Undercover (SLUS-21801) - Purple ground in software mode
### Describe the Bug

When using SW renderer, the ground will have shades of purple, doesn't happen on either HW renderer

### Reproduction Steps

Go into any quick race or career mode, as soon as you start driving a car you'll see it

### Expected Behavior

Ground shouldn't have purple colours, as it doesn't on PS2

### PCSX2 Revision

dev-2083

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 5600x

### GPU

GTX 1050 Ti

### GS Settings

image
(Auto flush on or off makes no difference, it's just to improve performance)

### Emulation Settings

Default preset

### GS Window Screenshots

image

### Logs & Dumps

[gs_20211128112047.gs.zip](https://github.com/PCSX2/pcsx2/files/7613419/gs_20211128112047.gs.zip) GS Dump
[SLUS-21801 - (7029F4DB).zip](https://github.com/PCSX2/pcsx2/files/7613422/SLUS-21801.-.7029F4DB.zip) Save State jumping right to the gameplay

### LINKED ISSUE #5125: [BUG]: Some "Jikkyou Powerful Pro Yakyuu" games - 3D rendering issues in certain screen
### Describe the Bug

In ``Jikkyou Powerful Pro Yakyuu 11 Chou Ketteiban``(SLPM-65825) and ``12 Ketteiban``(SLPM-66217), 3D character model rendering is weird in certain screens.
In the baseball game, every 3D models seems to be fine, but when in some 2D screen, the character model is covered with pink almost entirely (See screenshots below).

Both of SW and HW mode have this problem.
Team select screens in ``Jikkyou Powerful Pro Yakyuu 9`` and ``10`` don't have the similar issue.

### Reproduction Steps

Run ``Jikkyou Powerful Pro Yakyuu 11 Chou Ketteiban`` or ``12 Ketteiban``, and go to:

- Team select screen in ``Game`` mode.
- Batting/Pitching form select screen in ``Success`` mode.
- Uniform edit screen in ``Arrange/Edit`` mode.

Maybe ``Jikkyou Powerful Pro Yakyuu 11`` and ``12`` have the same issue.

### Expected Behavior

Rendering correctly.

### PCSX2 Revision

v1.7.2112

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i7-8700

### GPU

GTX 1070

### GS Settings

Default settings.
Changing mipmapping and blending accuracy setting made nothing.

### Emulation Settings

Preset: 2

### GS Window Screenshots

``Jikkyou Powerful Pro Yakyuu 12 Ketteiban``, SW mode.
Team Select:
powerpros12
 
Team Edit / Uniform Edit:
powerpros12uniform

Form Select:
powerpros12formselect

### Logs & Dumps

GSDumps:
[PowerProsRenderingIssue.zip](https://github.com/PCSX2/pcsx2/files/7683432/PowerProsRenderingIssue.zip)

### LINKED ISSUE #5240: [BUG]: Snoopy vs. the Red Baron - Z-Fighting issues, various HW rendering issues
### Describe the Bug

Both renderers exhibit Z-Fighting issues as shown in this video (skip ahead about 18 seconds, then watch the top screen).
https://user-images.githubusercontent.com/50224630/147812151-39034eea-667f-4edf-80fa-04201b6d6657.mp4
I have tried my best to get GSdumps of the issue. Holding ctrl + shift + f8 doesn't work on linux at the moment, so I simply made as many individual gsdumps as I could. EE/VU clamping options did not fix the issue.
[zfighting.zip](https://github.com/PCSX2/pcsx2/files/7795672/zfighting.zip)

Beyond that, several HW renderer issues are present.
- Top and bottom of the screen aren't turned black when the opening FMV starts
gs_20211230163327
[gs_20211230163327.gs.zip](https://github.com/PCSX2/pcsx2/files/7795673/gs_20211230163327.gs.zip)
- Black vertical bars appear over the screen during some transitions in the main menu
gs_20211230164057
[gs_20211230164057.gs.zip](https://github.com/PCSX2/pcsx2/files/7795682/gs_20211230164057.gs.zip)
- The skybox is too dark/faded 
SW (Correct):
gs_20211230222626
[gs_20211230222626.gs.zip](https://github.com/PCSX2/pcsx2/files/7795688/gs_20211230222626.gs.zip)
HW (Incorrect):
gs_20211230222704
[gs_20211230222704.gs.zip](https://github.com/PCSX2/pcsx2/files/7795689/gs_20211230222704.gs.zip)
- Garbage appears on the bottom and middle of the screen during 2 player
SW (Correct): 
gs_20211230223245
[gs_20211230223245.gs.zip](https://github.com/PCSX2/pcsx2/files/7795697/gs_20211230223245.gs.zip)
HW (Incorrect):
gs_20211230223238
[gs_20211230223238.gs.zip](https://github.com/PCSX2/pcsx2/files/7795698/gs_20211230223238.gs.zip)

Additionally, the game needs mipmapping set to at least Basic (Fast) . CRC is 213DCAC9.

Furthermore, the opening few screens (the initial black screen, the memory card check screen, and the logo screens) run extremely poorly, especially considering very little is going on. This is especially painful on software, where I hit 22% speed, far less than the rest of the game, which already runs very poorly, as the game seems to be somewhat intensive in general. According to Tellow,
> Game looks to be running at 900fps internally
> They must have forgotten to cap fps
> Combined with our lack of GS backpressure (PCSX2 doesn't emulate the amount of time it takes the PS2's GS to process large triangles) results in ridiculously high amounts of work
> You can get it going fairly fast if you throw enough cores at it

Regardless, I figured that they were worth noting here, along with the rest of the game's extremely poor performance. Attached are GSdumps and a blockdump. 

[Screens.zip](https://github.com/PCSX2/pcsx2/files/7795721/Screens.zip)

### Reproduction Steps

Start the game and play.

### Expected Behavior

Expected behavior was outlined in the first section.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2183 Compiled on Dec 30 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #5570: [BUG]: Power Drome - missing character model from vehicles.
### Describe the Bug

the vehicles are driving without a pilot. only noticed the issue when testing https://github.com/PCSX2/pcsx2/pull/5569 

### Reproduction Steps

play the game

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.2390

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

both software and hardware renderer

### Emulation Settings

_No response_

### GS Window Screenshots

gs_20220226010002

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
After PS2 tests, it was discovered that draws are ignored if the FRAME format is 24bit (Color or depth).  Also added support for behaviour where setting FRAME to a Z format forces the ZBUF to use color swizzling.  Added HLE clear for Powerdrome and Snoopy Vs the Red Baron

Also clamping Frame buffer width between 1 and 32, as 0 is invalid and treated as 1.  this is incorrect but PCSX2 can't handle FBW 0, there is likely GSOffset/memory handling problems related to this, but clamping it works better than not.

### Rationale behind Changes
These behaviours weren't handled, they are now handled.

### Suggested Testing Steps
Test listed fixed games, make sure nothing else is broken.

Fixes pink players in team selection on Jikkyou Powerful Pro Yakyuu 12 - Fixes #5125
Fixes multicoloured Cow in Barnyard when using Software Mode
Fixes Powerdrome and Snoopy Vs Red Baron "Double half clear", they do the same thing, but one more ridiculous than the other.  Fixes #5240 Fixes #473 Fixes #5570
Fixes the purple ground in Need for Speed Undercover in software Fixes #5078

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Eyecandy:

Snoopy Vs Red Baron:

Master:
image

PR:  (Kind of stupid cos it's a black screen because it's a clear, but some goes on other screens
image

Powerdrome:

Master:
image

**Comment by Tokman5** [comment]
I confirmed the pink player issues on both of ``Jikkyou Powerful Pro Yakyuu 11`` and ``12`` have been fixed.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -1953,15 +1962,34 @@ void GSRendererHW::OI_DoubleHalfClear(GSTexture* rt, GSTexture* ds)
 			}
 		}
 	}
+	// Striped double clear done by Powerdrome and Snoopy Vs Red Baron, it will clear in 32 pixel stripes half done by the Z and half done by the FRAME
+	else if(rt && !ds && m_context->FRAME.FBP == m_context->ZBUF.ZBP && (m_context->FRAME.PSM & 0x30) != (m_context->ZBUF.PSM & 0x30) && (m_context->FRAME.PSM & 0xF) == (m_context->ZBUF.PSM & 0xF) && (u32)(GSVector4i(m_vt.m_max.p).z) == 0)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:1966]: Formatting, space after else if.

**Comment by refractionpcsx2** [comment]
Also fixes the purple floor in NFS Undercover in software mode

Master:
image

PR:
image

**Comment by gregory38** [comment]
Interesting, did you test both datm setting for 24 bits date ?

**Comment by F0bes** [comment]
Yes

**Comment by refractionpcsx2** [comment]
DATM had no effect. DATE outright stops it drawing.

**Comment by gregory38** [comment]
Yeah, indeed unexpected behavior. Good job.

**Comment by refractionpcsx2** [comment]
This PR also fixed the bug we had with The Sims The Urbz, most noticable on the Maxis Logo

1.7.2391:
image

image

PR: 
image

image
