### PR TITLE
Debugger: Fix 'run-to-cursor' context action ft. warning fixes

### LINKED ISSUE #9230: [BUG]: Debugger - Run to cursor when paused causes infinite loop
### Describe the Bug

If you pause the emulation and go in to the debugger (I think this happens with pause in the debugger too), then right click somewhere in the assembly view, and choose "Run to cursor", the emulator will hang, since it is paused and never actually executes.

### Reproduction Steps

Pause emulator while running a game
Go to debugger
Right click on an instruction in the assembly after the currently running instruction
Choose "Run to cursor"
Feel sad that it hung

### Expected Behavior

Not hang, probably just not do anything.

### PCSX2 Revision

v1.7.4724

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### Logs & Dumps

loadelf: fname cdrom0:¥SLES_543.70;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_543.70;1
0 00100000 00358f9c ..............
[    5.2626] (VMManager) Pausing...
[    5.2632] (Cubeb): G:\ps2\gitrepo\pcsx2\3rdparty\cubeb\src\cubeb_wasapi.cpp:1760:000002461A0E27D0: Stop and join render thread: 0000000000000C78 (0), phase=0
[    5.2637] (Cubeb): G:\ps2\gitrepo\pcsx2\3rdparty\cubeb\src\cubeb_wasapi.cpp:1794:stop_and_join_render_thread: Closing thread.
[   18.6494] (VMManager) Resuming...
[   18.6499] QMetaObject::invokeMethod: Dead lock detected
EE/iR5900-32 Recompiler Reset

### PR DESCRIPTION
**Pull request by F0bes**
### Description of Changes
Fixes #9230
Decided to add some stuff as well
Fixes `-Wunused-variable` warnings
Fixes `-Wdeprecated-enum-enum-conversion` warning
Fixes `-Wsign-compare` warning
Fixes `-Wignored-qualifiers` warning

### Rationale behind Changes
Debugger function was broken and caused a deadlock (not good)
Warnings are not desirable and should be addressed 

### Suggested Testing Steps
Does the `run-to-cursor` context menu action work?
Does the memory search function still work?

### CODE REVIEW

File: pcsx2-qt/Debugger/CpuWidget.cpp [hunk 1]
```diff
@@ -589,7 +589,7 @@ static std::vector<u32> searchWorkerByteArray(DebugInterface* cpu, u32 start, u3
 		bool hit = true;
 		for (qsizetype i = 0; i < value.length(); i++)
 		{
-			if (cpu->read8(addr + i) != value[i])
+			if ((char)cpu->read8(addr + i) != value[i])
```
Comment (refractionpcsx2) [inline pcsx2-qt/Debugger/CpuWidget.cpp:592]: Can you use a static_cast? just the more modern way of doing stuffs :)

**Comment by refractionpcsx2** [comment]
Seems to not infinite loop anymore, so that's good.

It does seem to set a breakpoint when you do "run to cursor" which is not really the behaviour I'd expect. Is that a limitation of the current system, or can you remove the breakpoint in this scenario once it hits it? That'd probably be a good enough solution.

**Comment by F0bes** [comment]
> Seems to not infinite loop anymore, so that's good.
> 
> It does seem to set a breakpoint when you do "run to cursor" and it never gets removed which is not really the behaviour I'd expect. Is that a limitation of the current system, or can you remove the breakpoint in this scenario once it hits it? That'd probably be a good enough solution.

Yeah the feature for temporary breakpoints was already there. Just didn't mark it as such. That's been addressed.
