### PR TITLE
GS-TC: On invalidate of the alpha of 32bit, drop back to 24bit

### LINKED ISSUE #909: [Bug Report] ops2m demo 33 - Primal [PAL]
**_PCSX2 versions used:**_ pcsx2-v1.3.1-1256-gbbd74e5 (latest dev build)
**_Emulation settings:**_ "Safest" preset, MTVU hack not used.
**_Plugins used:**_ GSdx AVX2, cddvdGigaherz
**_Plugin settings:**_ CRC Hack Level "None"
#### Hardware Specifications

**_CPU:**_ Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
**_GPU:**_ NVIDIA GeForce GTX 970 (Driver: NVIDIA 358.50)
#### Description

D3D9, D3D11 and OGL **HARDWARE** renderers are not able to draw anything on the screen. Instead it's all black.
Only the software renderer is able to draw ~~something~~ the expected scene.
OpenCL renderer remains untested.
#### Screenshots

Software renderer output
image:1
#### GS dump

http://forums.pcsx2.net/attachment.php?aid=57681

### LINKED ISSUE #6959: Shadow Hearts Covenant broken fusion effect
### Describe the Bug

When using fusion in battle the spherical effect around the character is not rendered properly. The issue has been present for as long as I can remember. Since I started using PCSX2 back in 2014 so it isn't a new issue. 

### Reproduction Steps

Run game in hw mode and use a fusion pay close attention to how the effect looks in hw mode vs sw mode.

### Expected Behavior

Effect should render like sw mode. 

### PCSX2 Revision

v1.7.3264

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default

### Emulation Settings

default

### GS Window Screenshots

Screenshot (4)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/9456558/snaps.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
If the alpha channel of a C32 texture gets overwritten, instead of erasing the whole texture, make it a 24bit texture so it no longer uses alpha.

### Rationale behind Changes
This was previously erasing it and destroying the RGB data along with it, which in Shadow Hearts later got reused, but instead of getting this data since it was gone, it got garbage from memory.  This is a heuristic so it *might* break something, but hopefully it's safe.

### Suggested Testing Steps
Test Shadow Hearts as per the issue below, test general games. GS Dump runner seemed to not affect anything.

Fixes #6959 Shadow Hearts Covenant broken fusion effect
Fixes #909 Primal black screen in HW mode.
Mobile Suit Gundam - One Year War also shows some improvement, but is still unfortunately unplayable in hardware.

Master:
image

PR:
image

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -1376,11 +1376,22 @@ void GSTextureCache::InvalidateVideoMem(const GSOffset& off, const GSVector4i& r
...
 					if (can_erase)
 					{
-						i = list.erase(j);
-						GL_CACHE("TC: Remove Target(%s) %d (0x%x)", to_string(type),
-							t->m_texture ? t->m_texture->GetID() : 0,
-							t->m_TEX0.TBP0);
-						delete t;
+						// If it's a 32bit value and only the alpha channel is being killed
+						// instead of losing the RGB data, drop it back to 24bit.
+						if (rgba._u32 == 0x8 && t->m_TEX0.PSM == 0x0)
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:1381]: Can we use the `PSM_` enumeration instead of the magic numbers here? Makes it much more readable.

**Comment by prafullpcsx2** [comment]
This fixes Primal in HW mode.

https://github.com/pcsx2/pcsx2/issues/909

**Comment by RedDevilus** [comment]
Seems to also fix Magazine Demo 30 for Primal:
- Before (Hardware renderer):
Official PlayStation 2 Magazine Demo 30_SCED-51489_20230228212424
- After (Hardware renderer):
Official PlayStation 2 Magazine Demo 30_SCED-51489_20230228212628
Official PlayStation 2 Magazine Demo 30_SCED-51489_20230228212530

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]
