### PR TITLE
Qt: Prompt user to enable HC mode on achievement login

### LINKED ISSUE #10355: [BUG]: Retroachievements leaderboard counter collides with leaderboard symbol
### Describe the Bug

As you can see in the image, the retroachievements leaderboard in the bottom right corner counts your points. If it is more than 3 digits, it will not position correctly and instead overlap with the icon.
image
(For the sake of following the instructions, I did also test with native resolution, but since the bug is not related to emulation, it obviously didn't fix it)

### Reproduction Steps

You need to be logged in with retroachievements and leaderboards need to be turned on.
Play Guitar Hero Encore - Rocks the '80s (USA) and play any song in career mode (or any other supported game that has a leaderboard counting values of 1000 or higher).

### Expected Behavior

Counter positions correctly on the right side of the icon no matter the amount of digits.

### PCSX2 Revision

PCSX2 Nightly - v1.7.5255

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Ports of https://github.com/stenzek/duckstation/commit/07fac1fb19553a43d6b25ea0104097cad5b43046 and https://github.com/stenzek/duckstation/commit/dc6bb357d427178ce5b2f1e4c4aaeec26616ced0.

### Rationale behind Changes

Prevents users assuming that hardcore mode is on by default.

Potentially fixes #10355.

### Suggested Testing Steps

Test logging in with achievements+hardcore disabled, look for prompts.

### CODE REVIEW

File: pcsx2/Achievements.cpp [hunk 1]
```diff
@@ -1983,7 +1981,7 @@ void Achievements::DrawGameOverlays()
 
 			TinyString width_string;
 			width_string.append(ICON_FA_STOPWATCH);
-			for (u32 i = 0; i < indicator.display_length; i++)
+			for (u32 i = 0; i < indicator.text.length(); i++)
 				width_string.append('0');
```
Comment (CookiePLMonster) [inline pcsx2/Achievements.cpp:1985]:
```suggestion
			width_string(indicator.text.length(), '0');
```

Comment (stenzek) [reply pcsx2/Achievements.cpp:1985]: It's not a std::string. Probably should add that to TinyString though.
