### PR TITLE
GS: Properly detect 16bit format on Texture Shuffle + Convert

### LINKED ISSUE #4661: [BUG] SLUS-20724 Firefighter FD18
**Describe the bug**
Graphical glitching in game while playing.  Assets seem to vanish such as the fire, or other in game assets for example in the parking garage the cars will vanish too at times.  This was tested on multiple machines exhibiting the same bug in the same place.  Hitting f9 resolves the issue.

**To Reproduce**
This bug is repeatable by using the following steps on two different stages:

1.  Stage 3-2 play to mission 3 Parking Garage (There is no way to legit start at stage 3-2 mission 3 without using a save state). 
  a. Player will enter the parking garage at start of mission.
  b.  Spray the hose around and move camera and graphical glitches are visible.

2. Stage 4-2 Mission 2 Boss Battle
  a.  During the boss fight the boss vanishes
  b.  The fire vanishes as well.

**Expected behavior**
Have assets visible and not invisible or be missing.

**GS Settings**
Default settings

**Emulation Settings**
Default Settings

**GS Window Screenshots**
gsdx_20210812111938

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.6.0
 -   OS: Windows 10 
 -   CPU:   i7-9700 CPU   
 -   GPU:   Nvidia GeForce RTX 2070

**Logs and Dumps**
GSdump:    http://www.filedropper.com/gsdumpfirefighterfd18
MemCard:  [Mcd001_FirefighterFD18_SLUS-20724.zip](https://github.com/PCSX2/pcsx2/files/6977025/Mcd001_FirefighterFD18_SLUS-20724.zip)
sstate:        [sstate_FirefighterFD18_SLUS-20724.zip](https://github.com/PCSX2/pcsx2/files/6977027/sstate_FirefighterFD18_SLUS-20724.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Fixes the detection of 16bit format on shuffle and format convert

### Rationale behind Changes
It was being misdetected as 16bit instead of 32bit when a shuffle happened due to texture shuffles explicitly forcing the texture to 32bit, causing issues.

### Suggested Testing Steps
Test games, make sure post processing isn't broken.

Fixes #4661 but does need Half screen hw renderer fix also (now in Master)

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 1]
```diff
@@ -576,7 +576,7 @@ GSTextureCache::Target* GSTextureCache::LookupTarget(const GIFRegTEX0& TEX0, con
 			dst = CreateTarget(TEX0, new_size.x, new_size.y, type, clear);
 			dst->m_32_bits_fmt = dst_match->m_32_bits_fmt;
 			ShaderConvert shader;
-			bool fmt_16_bits = (psm_s.bpp == 16 && GSLocalMemory::m_psm[dst_match->m_TEX0.PSM].bpp == 16);
+			bool fmt_16_bits = (psm_s.bpp == 16 && GSLocalMemory::m_psm[dst_match->m_TEX0.PSM].bpp == 16 && !dst->m_32_bits_fmt);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:579]: Bonus, make it a const.

**Comment by stenzek** [comment]
Dunno if it's worth mentioning where that `m_32_bits_fmt` flag comes from (shuffles get forced to 32bit regardless of PSM). But noting it here for future reference anyway.
