### PR TITLE
Qt: Some description works and other misc UI improvements

### LINKED ISSUE #6937: [BUG]: Several options in ui do not say what they do when hovered over with mouse
### Describe the Bug

There are several options in the ui graphics section which have no explanation. All other options do. These are easily found in the tabs for advanced and texture replacement within the graphics section. All other check boxes have a description of the option. 

### Reproduction Steps

Hover mouse over certain options in the described sections of the ui.

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.3256

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR attempts to fill missing description in certain sections of the settings.

See commit list for more information.

Fixes #6937 

Preview:
Screenshot_20231110_221415

### Rationale behind Changes

Missing Description Bad.

### Suggested Testing Steps

Make sure i don't break other stuff.

### CODE REVIEW

**Comment by kamfretoz** [comment]
Should be ready for testing. 

List of Changes: 
- Added:
	- Audio -> Timestretch Settings -> Sequence Length, Seekwindow Size, Overlap.
Screenshot_20231217_201201
	- Advanced -> VU0/1 Clamping & Rounding Mode.
Screenshot_20231217_201225
	- Added a small warning to the Advanced Graphics tab.
Screenshot_20231217_201330

File: pcsx2-qt/Settings/AdvancedSettingsWidget.cpp [hunk 1]
```diff
@@ -70,9 +70,11 @@ AdvancedSettingsWidget::AdvancedSettingsWidget(SettingsWindow* dialog, QWidget*
 	SettingWidgetBinder::BindWidgetToBoolSetting(sif, m_ui.pineEnable, "EmuCore", "EnablePINE", false);
 	SettingWidgetBinder::BindWidgetToIntSetting(sif, m_ui.pineSlot, "EmuCore", "PINESlot", 28011);
 
-	dialog->registerWidgetHelp(m_ui.eeRoundingMode, tr("Rounding Mode"), tr("Chop/Zero (Default)"), tr(""));
+	dialog->registerWidgetHelp(m_ui.eeRoundingMode, tr("Rounding Mode"), tr("Chop / Zero (Default)"), tr("Changes how PCSX2 handles rounding while emulating the Emotion Engine's Floating Point Unit (EE FPU). "
```
Comment (IlDucci) [inline pcsx2-qt/Settings/AdvancedSettingsWidget.cpp:73]: The spaces in "Chop/Zero" here and in the other mode are back from the dead.

File: pcsx2-qt/Settings/AdvancedSettingsWidget.cpp [hunk 2]
```diff
@@ -70,9 +70,11 @@ AdvancedSettingsWidget::AdvancedSettingsWidget(SettingsWindow* dialog, QWidget*
...
+	"Because the various FPUs in the PS2 are non-compliant with international standards, some games may need different modes to do math correctly. The default value handles the vast majority of games; <b>modifying this setting when a game is not having a visible problem can cause instability.</b>"));
 
-	dialog->registerWidgetHelp(m_ui.eeClampMode, tr("Clamping Mode"), tr("Normal (Default)"), tr(""));
+	dialog->registerWidgetHelp(m_ui.eeClampMode, tr("Clamping Mode"), tr("Normal (Default)"), tr("Changes how PCSX2 handles keeping floats in a standard x86 range. "
```
Comment (IlDucci) [inline pcsx2-qt/Settings/AdvancedSettingsWidget.cpp:76]: I suppose this is techy-enough to scare non-techy users? What would be the target goal for this string and its copies here?

File: pcsx2-qt/Settings/AudioSettingsWidget.cpp [hunk 3]
```diff
@@ -123,12 +123,15 @@ AudioSettingsWidget::AudioSettingsWidget(SettingsWindow* dialog, QWidget* parent
 		tr("Determines the latency from the buffer to the host audio output. This can be set lower than the target latency to reduce audio "
 		   "delay."));
 
-	dialog->registerWidgetHelp(m_ui.sequenceLength, tr("Sequence Length"), tr("30 ms"), tr(""));
+	dialog->registerWidgetHelp(m_ui.sequenceLength, tr("Sequence Length"), tr("30 ms"), tr("This is the default length of a single processing sequence in milliseconds which determines the how the original sound is chopped in the time-stretch algorithm. "
```
Comment (IlDucci) [inline pcsx2-qt/Settings/AudioSettingsWidget.cpp:126]: Typo here: "which determines how the..." Also, should we need to quickly define what kind of sequence is this?

File: pcsx2-qt/Settings/AudioSettingsWidget.cpp [hunk 4]
```diff
@@ -123,12 +123,15 @@ AudioSettingsWidget::AudioSettingsWidget(SettingsWindow* dialog, QWidget* parent
...
+	"Larger values mean fewer sequences are used in processing. In principle a larger value sounds better when slowing down the tempo, but worse when increasing the tempo and vice versa. "));
 
 	//: Seek Window: the region of samples (window) the audio stretching algorithm is allowed to search.
-	dialog->registerWidgetHelp(m_ui.seekWindowSize, tr("Seek Window Size"), tr("20 ms"), tr(""));
+	dialog->registerWidgetHelp(m_ui.seekWindowSize, tr("Seek Window Size"), tr("20 ms"), tr("The seeking window default length in milliseconds is for the algorithm that seeks the best possible overlapping location. "
```
Comment (IlDucci) [inline pcsx2-qt/Settings/AudioSettingsWidget.cpp:130]: I find the wording of "in milliseconds is for the algorithm"... a bit odd.

File: pcsx2-qt/Settings/AudioSettingsWidget.cpp [hunk 5]
```diff
@@ -123,12 +123,15 @@ AudioSettingsWidget::AudioSettingsWidget(SettingsWindow* dialog, QWidget* parent
...
 
-	dialog->registerWidgetHelp(m_ui.overlap, tr("Overlap"), tr("10 ms"), tr(""));
+	"This determines from how wide a sample window the algorithm can use to find an optimal mixing location when the sound sequences are to be linked back together."));
```
Comment (IlDucci) [inline pcsx2-qt/Settings/AudioSettingsWidget.cpp:132]: Possible typo here: "This determines how wide a sample window..."? Possible odd wording here as well.

**Review by Mrlinkwii — APPROVED** [review]

File: pcsx2-qt/Settings/AdvancedSettingsWidget.cpp (hunk 1 above)
Comment (kamfretoz) [reply pcsx2-qt/Settings/AdvancedSettingsWidget.cpp:59]: Sorry about that, i missed it when trying to resolve the merge conflict.

File: pcsx2-qt/Settings/AdvancedSettingsWidget.cpp (hunk 2 above)
Comment (kamfretoz) [reply pcsx2-qt/Settings/AdvancedSettingsWidget.cpp:62]: I mean, the general idea is for most user to not even mess around the Advanced settings anyway, they were meant **for those who know what they are doing.** 

As for the string copies, they were the duplicated on both VU0/1 because they did pretty much the same thing.

For the general goal is to explain what the option do in the first place.

File: pcsx2-qt/Settings/AudioSettingsWidget.cpp (hunk 3 above)
Comment (kamfretoz) [reply pcsx2-qt/Settings/AudioSettingsWidget.cpp:112]: I still need to find a way to simplify the explanation, the thing is so many of this terms need to be explained in order for the entire description to make sense, and we don't have the luxury to fit a whole bunch of the texts.

Comment (kamfretoz) [reply pcsx2-qt/Settings/AudioSettingsWidget.cpp:112]: I suppose its good enough for now, most users don't even need to change any of this settings anyway, the default is already sufficient.

File: pcsx2-qt/Settings/AudioSettingsWidget.cpp (hunk 5 above)
Comment (kamfretoz) [reply pcsx2-qt/Settings/AudioSettingsWidget.cpp:118]: Same as the other string, it's simply impractical to fully explain all the details.

**Comment by kamfretoz** [comment]
The advanced graphics option tab is now hidden by default as most users don't need to mess around in there unless under very specific circumstances.

To show it enable `Tools -> "Show Advanced Settings"` option.

image

**Review by Mrlinkwii — APPROVED** [review]
