### PR TITLE
Lilypad: Fix Local Volume control CB function and few other stuffs

### LINKED ISSUE #629: [Lilypad] "Local volume control" option broken and cannot be disabled
Found this one by mistake (PCSX2 kept starting with default to system sound level). Basically, the "Local volume control" option in Lilypad cannot be disabled, when you uncheck the option and save, it just sets directive **Vista Volume=1** to **Vista Volume=100**  and option is still checked. Manually setting to 0 *disables it in GUI*.

Altho, I'm not sure if it still works as intended and not redundant anymore. Setting it to 1/0 has no difference and effect.

### PR DESCRIPTION
**Pull request by ssakash**
There was a wrong value change for vistaVolume in condition for when it is disabled, it sets 100 to the variable. hence when the checkbox gets unchecked, it eventually leads the Local volume control checkbox to be force enabled even when a user disables it at the dialog. the following patch corrects the behavior.

Partial fix for #629

### CODE REVIEW

**Comment by turtleli** [comment]
lilypad commit: Commit is Ok. Fixes the GUI side of the issue. A side note: the local volume control stuff is still broken and it's been broken for at least 5 years. The question is what to do with it. Fix? Remove?

MicroVU commit: `Console.Warning`? Also, changing only that one might mean that some warnings are red, and some are orange, which would be somewhat inconsistent. I'm not familiar with MicroVU stuff though.

**Comment by ssakash** [comment]
Lilypad commit: I think it should stay, so anyone could fix it in the future. 

MicroVU commit: not really, the other warnings usually affect the game in a certain way causing infinite loop (or) other crash behaviors. This warning is harmless and couldn't really be classified as an warning IMO. It got fixed already, though for some reasons ref said that it should stay. so using a different color just in case so that ref want to look at such instances of delay slot.

File: pcsx2/gui/FrameForGS.cpp [hunk 1]
```diff
@@ -402,7 +402,7 @@ static const uint TitleBarUpdateMs = 333;
 
 
 GSFrame::GSFrame(wxWindow* parent, const wxString& title)
-	: wxFrame(parent, wxID_ANY, title, g_Conf->GSWindow.WindowPos)
+	: wxFrame(NULL, wxID_ANY, title, g_Conf->GSWindow.WindowPos)
```
Comment (turtleli) [inline pcsx2/gui/FrameForGS.cpp]: This makes `parent` an unused parameter. Perhaps this could be done better?

File: pcsx2/x86/microVU_Compile.inl [hunk 2]
```diff
@@ -207,7 +207,7 @@ __ri void branchWarning(mV) {
 	incPC(-2);
 	if (mVUup.eBit && mVUbranch) {
 		incPC(2);
-		Console.Error("microVU%d Warning: Branch in E-bit delay slot! [%04x]", mVU.index, xPC);
+		Console.WriteLn(Color_Orange, "microVU%d Warning: Branch in E-bit delay slot! [%04x]", mVU.index, xPC);
```
Comment (turtleli) [inline pcsx2/x86/microVU_Compile.inl]: If the user needs to know about it but it's not of major concern then I think `Console.Warning` should be used.
If the user doesn't need to know about it then I think `DevCon.Warning` should be used.

**Comment by ssakash** [comment]
MicroVU: decided to go with DevCon.Warning, that seems more suitable for the scenario.

GSFrame: That parameter is pretty much pointless after the relationship to NULL, removed it. https://github.com/ssakash/pcsx2/commit/84ab1fb917b9cdeede2cea9576070a6b9b46de47

**Comment by turtleli** [comment]
Yes, that's what I was looking for. Perhaps squash the 2 GSFrame commits? I'll retest this later.

**Comment by ssakash** [comment]
sure.

**Comment by turtleli** [comment]
Thanks.

I edited your initial comment so the Lilypad issue doesn't autoclose - your commit only fixes the GUI side of things. Currently it's better to have local volume control off - Windows remembers the volume settings. Having local volume control on interferes with Windows.

Side note: consider naming your branches meaningfully. It makes it easier for others to know/remember what the branch is for.
