### PR TITLE
GS/HW: Implement RT in RT support

### LINKED ISSUE #267: Wrath Unleashed (NTSC-U) [SLUS-20840] Broken Graphics
This game has very miss colored graphics IN-GAME and some flashing makes the whole game uncontrollable due to so many properer textures.

My pcsx2 version is:
pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

### LINKED ISSUE #913: [BUG]: Honda Demo, TOCA Race Driver 2 and 3
**_PCSX2 versions used:**_ pcsx2-v1.3.1-1299-gb6d9ea8-windows-x86
**_Emulation settings:**_ "Safest" preset, no hacks.
**_Plugins used:**_ GSdx-AVX2, cddvdGigaherz
**_Plugin settings:**_ CRC Hack Level "None"
#### Hardware Specifications

**_CPU:**_ Intel® Core™ i5-4690K CPU @ 3.50GHz
**_GPU:**_ GeForce GTX 970 (Driver: NVIDIA 358.50)
#### Description

This is from demo disc SCED-52933 but it's also reported in the full versions. 
While using any HW renderer, in 3rd person view a translucent black box covers the player's car and its dynamic shadow appears to be broken.
Other cars passing through this box get their shadows turned into boxes too.
Setting the HW hack "Skip Draw" to 1 is a known workaround but it disables the player's car dynamic shadow and some other effects.
This bug is known in the wiki as "Broken Shadows".
#### Screenshots

Software mode
image:1

OGL HW renderer

image:2

OGL HW renderer with Skip Draw set to 1

image:3

**_GS dump**_ : http://forums.pcsx2.net/attachment.php?aid=57698

### LINKED ISSUE #3849: Suikoden 3 - Top half of screen has garbo
Source: https://forums.pcsx2.net/Thread-Bug-Report-1-6-0-Suikoden-3

image

Needs research for the reason of this problem.

Savestates with 1.7 build: 
https://mega.nz/file/FoZ0AJCC#PxH7OP0CZrqqfq38bEbmq5hBhfMxVqTcw3gX9Tan7cU

### LINKED ISSUE #3855: Drakengard: Channel Shuffle
Game has a broken channel shuffle
image

Steps to reproduce:
- obtain broken dogma weapon
- use it

Will upload dump later

### LINKED ISSUE #4251: [BUG] Hitman Blood Money graphical and performance issues
**Describe the bug**
Several graphical issues with opengl and d3d11. Performance becomes very slow at anything past 2x native.
pcsx2_2021-02-24_13-03-07
pcsx2_2021-02-24_13-04-28

Software mode doesn't have these graphical issues, but performance isn't great even with auto flush disabled. MTVU does seem to help though with d3d/opengl.
pcsx2_2021-02-24_13-06-18
pcsx2_2021-02-24_13-07-47

**To Reproduce**
Just booting up.

**Expected behavior**
Should look more accurate like how it does in software mode.

**GS Settings**
pcsx2_2021-02-24_13-28-52

**Emulation Settings**
pcsx2_2021-02-24_13-36-36

**System Info (please complete the following information):**
 - PCSX2 Revision: v1.7.0-dev-1009-gb088ee69c
 - OS: Windows 10
 - CPU: i7 4790
 - GPU: GTX 1060

**Logs and Dumps**
https://mega.nz/file/L0QABbYC#Es9VlSKSoU-s7Z4vSKf1rKMjRRsPO1owFFO048HnzfE

### LINKED ISSUE #4964: [BUG]: jak X splitscreen problem
### Describe the Bug

The second player screen is not shown in hardware mode, but only in software mode.

### Reproduction Steps

Start a race in 2 players mode.

### Expected Behavior

_No response_

### PCSX2 Revision

dev-1996-g6348fe7362

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

intel(R) Core(TM) I7 3770 CPU @ 3.40 Ghz

### GPU

nvidia Geforce gtx 1050 Ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

Hardware
image
Software
image

### Logs & Dumps

_No response_

### LINKED ISSUE #7942: [BUG]: Time Crisis 3: Visual Bugs
### Describe the Bug

At certain stages of the game a white square appears in the top left, sometimes two squares and sudden fps drops some of which remain for whole sections of the game. the first dump has severe fps drop to 10fps that remain for most of that level.

It runs these sections fine in software mode.

### Reproduction Steps

Play the game up to these sections on Vulkan. Software mode is fine.

### Expected Behavior

Expected behavior? These white squares shouldn't appear. 

### PCSX2 Revision

v1.7.3941

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

5800x3D

### GPU

GTX 3070

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

time crisis 3 gfx glitch
time crisis 3 gfx glitch 2

### Logs & Dumps

[Time Crisis 3 [with Guncon]_SLUS-20645_20230123120853.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10476291/Time.Crisis.3.with.Guncon._SLUS-20645_20230123120853.gs.zst.zip)
[Time Crisis 3 [with Guncon]_SLUS-20645_20230123122041.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10476293/Time.Crisis.3.with.Guncon._SLUS-20645_20230123122041.gs.zst.zip)

### LINKED ISSUE #8328: [BUG]: Stolen: HW bad lighting.
### Describe the Bug

the lighting between hardware in software is very off.
Stolen_SLUS-21099_20230303121400

### Reproduction Steps

just get in-game and switch between hardware and software rendering.

### Expected Behavior

Stolen_SLUS-21099_20230303121000

### PCSX2 Revision

1.7.4187

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[Stolen_SLUS-21099_20230303121000.gs.zip](https://github.com/PCSX2/pcsx2/files/10885076/Stolen_SLUS-21099_20230303121000.gs.zip)

### LINKED ISSUE #8574: [BUG]: Ridge Racer V HW Mode Colorful light problem
### Describe the Bug

In the NIGHT race (happens AT LEAST in the music player, because I kinda suck at RRV), lights are gone, or become colorful.

changing Tex In RT to Merge Target resolves this, but with Software CLUT Renderer it will happen again.

from what I have observed,
SW CLUT + TexInRT = Colorful light
SW CLUT only = Colorful light without car tex mess
TexInRT = Missing Lights, messy car tex

### Reproduction Steps

Run the game on HW, (Any mode), Open the music player on Option.
Set to Night for scene

### Expected Behavior

_No response_

### PCSX2 Revision

PR (#8571), as well as v1.7.4331

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

AMD Ryzen 7 5800U

### GPU

NVIDIA GeForce RTX 3060M

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #8869: [BUG]: Battlefield 2 - Modern combat 2 - 1e Flickering bug (v1.7.3859)
### Describe the Bug

The bug consist of heavy flickering graphics issues that happends for Battlefield 2 Modern Combat in multiplayer mode. This starts to happen for any hardware as renderer. Software renderer does work correctly without flickering! Our discord community all confirms they experience the same issue thats why i jumped in for investigation and a solution.

The flickering issues I manage to track down by testing version 1.7.3858 that has not the flickering issue. The version 1.7.3859 has the flickering issue.
By checking the [pull 7797](https://github.com/PCSX2/pcsx2/pull/7797) for version v1.7.3859. You see that Battlefield 2 got a specific patch [GSHwHack::OI_Battlefield2](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/GS/Renderers/HW/GSHwHack.cpp#L957).

By disable "beforeDraw" for "GSHwHack::OI_Battlefield2" in the "GameIndex.yaml", I manage to stop the 1e flickering issue. Because we disabled the Hardware fix in "beforeDraw" we triggered a old bug called "black main menu". This basically didn't draw the full main menu on the screen that caused for a large black screen. With the "GSHwHack::OI_Battlefield2" it patched the width and height of that image.

After debugging this "GSHwHack::OI_Battlefield2" patch i manage to understand better how it worked. Thats why i changed the code to not let it trigger anymore in multiplayer.
```
bool GSHwHack::OI_Battlefield2MP(GSRendererHW& r, GSTexture* rt, GSTexture* ds, GSTextureCache::Source* t)
{
	if (rt && t && RCONTEXT->FRAME.Block() == 0 && RCONTEXT->TEX0.TBP0 == 0x1000)
	{
		const GSVector4i rc(0, 0, std::min(rt->GetWidth(), t->m_texture->GetWidth()), std::min(rt->GetHeight(), t->m_texture->GetHeight()));
		g_gs_device->CopyRect(t->m_texture, rt, rc, 0, 0);

		r.m_tc->InvalidateTemporarySource();
		return false;
	}

	return true;
}
```
Basically i patch the code that it only can trigger false when he detect the main menu. If he is not in the main menu he return true and no patch is applied on the GS.

In the orginal "GSHwHack::OI_Battlefield2" [line 959](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/GS/Renderers/HW/GSHwHack.cpp#L959) you see it has a extra if statement to return true. I didnt fully get the reason behind this desision. Because of this it returns to much false returns. This was the main cause of this flicker issue in multiplayer.

My idea is to split this into 2 patches: "GSHwHack::OI_Battlefield2SP"(default) and "GSHwHack::OI_Battlefield2MP". This way our BF2:MC online community can switch what patch to choose in "GameIndex.yaml" file. I notice right now that the BF2:MC community keeps on a lower PCSX2 version because of this issue.

### Reproduction Steps

- Change settings:
  Graphic:
   Renderer: Direct3D 12
   Adapter: RTX 3080
  Network & HDD
    Enable network
    Ethernet device Type: Sockets
    Ethernet device: Ethernet

 - Start the game, click in the main menu: Play online
 - Create a new adapter with DNS IP(45.7.228.197).
 - Login with your account or your create one.
 - Join a random server
 
 Once you joined the game the flickering starts happening.

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.3859

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

AMD Ryzen 9 5900X

### GPU

RTX 3080

### GS Settings

SLUS-21026:
  name: "Battlefield 2 - Modern Combat"
  region: "NTSC-U"
  compat: 5
  gsHWFixes:
    autoFlush: 1 # Post-processing.
    halfPixelOffset: 2 # Offset post-processing.
    texturePreloading: 1 # Spikes all over the place otherwise.
    getSkipCount: "GSC_Battlefield2" # Depth clear.
    beforeDraw: "OI_Battlefield2" # Framebuffer copy, fixes rendering for bottom part of screen.

### Emulation Settings

settings

### GS Window Screenshots

Ingame
The screenshot doesn't show it correctly, but the screen keeps flickering,..

BlackMainMenu
This is how the "Black main menu" looks like. It is filled for 90% unrendered screen.

### Logs & Dumps

Battlefield 2 - Modern Combat_SLUS-21026_20230517121505

GS Dump: https://mega.nz/file/Acpx2KbZ#ipJWX53b0KDEPQ1C-sE0ZHVlvIE9p1uDGzrl3ESt0HE

### LINKED ISSUE #8995: [BUG]: Tekken 5 Burning Temple Issue Vulkan / GS HW vs Software
### Describe the Bug

The Burning Temple issue appears to be missing the raster heat distortion effect in Vulkan vs software mode despite Full blending accuracy

### Reproduction Steps

Play Tekken, Practice Mode for Burning Temple level, switch renderers

### Expected Behavior

Wavey heat-distortion effect in Vulkan

### PCSX2 Revision

1.7.4587

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5900HS

### GPU

RTX 3050Ti

### GS Settings

image
image

### Emulation Settings

image

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #9888: [BUG]: Conflict - Desert Storm flickering in HW renderers
### Describe the Bug

game flickers in HW renderers 

### Reproduction Steps

boot the game with hardware renderers 

### Expected Behavior

no flickering 

### PCSX2 Revision

v1.7.4967

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu ,  but also happens on windows

### CPU

Intel Xeon E5-1620 v3 (8) @ 3.600GHz

### GPU

NVIDIA Quadro K2200

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #10164: [BUG]: Manhunt 2 (SLUS-21613) Transparent Rectangle in the Top-Left Corner & Low Performance
### Describe the Bug

A transparent rectangle can be seen in the top-left corner of the screen in Manhunt 2. I've noticed something similar in some bug reports in other games while browsing through the repo (notably the infamous green rectangle in the PS2 demo of Underground 2), but here it's just transparent.

Performance also seems to be poor in this game currently, at least in Vulkan at 3x resolution. No more than 25fps game speed in the starting area alone, and the controls feel quite wonky and unresponsive as a result. The boot up sequence is also quite slow (the memory card screen doesn't even go past 6fps (Game speed) for me lol. That's... entirely unprecedented. This is also considerably worse than both the PSP version of the game and the original Manhunt).

The good news is, at least the game doesn't seem to crash shortly after starting a new session anymore. In fact, I was hoping to report a crash here initially, but it looks like that got ironed out since... around the time of the summer, I think?

gdfgfdd

### Reproduction Steps

Just start a new game and observe the rectangle in the top-left corner of the screen. It's always there.

### Expected Behavior

No rectangle, and better performance (haven't tried Software to see how it fares in that regard).

### PCSX2 Revision

v1.7.5144

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i5-6402P

### GPU

GTX 950

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #10399: [BUG]: Hitman Contracts: Several Issues
### Describe the Bug

Graphics: The main menu displays a gray box.  This box persists throughout most of the game unless software mode is activated, which degrades game performance;

Save/Load crashes: Saving or loading the game often results in the game crashing;

Crash on a specific level: loading the level "The Wang Fou Incident" causes the emulator to crash, it stops responding and shuts down.

### Reproduction Steps

Enter the game, save, load, load the level The Wang Fou Incident

### Expected Behavior

Ideally, the game would work like Hitman 2, with gameplay close to 100%

### PCSX2 Revision

1.7.5285

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

AMD Ryzen 5 4600G

### GPU

RADEON VEGA GRAPHICS

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #10471: [BUG]: SWAT Global Strike Team - miscolored textures in split screen
### Describe the Bug

In split screen mode, the 2nd player's screen has miscolored shadows/textures when running in the HW renderer.

### Reproduction Steps

Boot game into cooperative mode, load a level.

### Expected Behavior

Shadows/texture should appear normal in both screens

### PCSX2 Revision

v1.7.5336

### Operating System

Windows 11

### CPU

Ryzen 7900X

### GPU

RTX 4090

### GS Settings

Defaults

### Emulation Settings

Defaults

### GS Window Screenshots

SWAT - Global Strike Team_SLUS-20433_20231225115228

### Logs & Dumps

[SWAT - Global Strike Team_SLUS-20433_20231225115228.zip](https://github.com/PCSX2/pcsx2/files/13766831/SWAT.-.Global.Strike.Team_SLUS-20433_20231225115228.zip) (rename to .gs.xz)

### LINKED ISSUE #10763: [BUG]: Urban Reign: Graphical Glitch from blur effect (ex when winning a mission)
### Describe the Bug

This is pretty similiar to a bug I know troubled this game before on hardware mode, when a bunch of rainbow squares would pop up on the screen when for example you'd beat a mission. Apparently this was "fixed" however the issue is still present on hardware mode in a different way - its a bit odd and I did not have time to make a screenshot of it, but it basically looked like some black squares appearing on part of the screen and I think there was even text(?) there, odd

### Reproduction Steps

Pretty easy, you can see it happen even on the first mission - it will happen during the intro cutscene and when you win the mission, I'm pretty sure it happens when the game is trying to activate a blur effect

### Expected Behavior

The game should have a blur effect for a moment, not graphical glitches on the screen

### PCSX2 Revision

1.7.5537

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Intel Core i5 9300H @ 2.40GHz

### GPU

3071MB NVIDIA GeForce GTX 1050 (Lenovo)

### GS Settings

Nothing changed in the default graphics settings besides raising the resolution to 1080p, vulkan renderer

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #10982: [BUG]: WRC 3 Incorrect fog layer in hardware mode
### Describe the Bug

The fog layer on the left hand side should cover the entire screen but in hardware mode only covers half of the rocky outcrop.

Hardware:
WRC 3_SCES-51684_20240327225715

Software:
WRC 3_SCES-51684_20240327225719

### Reproduction Steps

Run the provided GS dump and see the issue to the left.

### Expected Behavior

The fog to be more foggy.

### PCSX2 Revision

v1.7.5645

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 5600x

### GPU

RTX 2070 Super

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[A_Foggy_Issue.zip](https://github.com/PCSX2/pcsx2/files/14782019/A_Foggy_Issue.zip)

### LINKED ISSUE #11085: [BUG]: Death by Degrees graphical bug
### Describe the Bug

Graphics are broken in Lana Lei boss fight.

unknown_2024 04 15-21 36
unknown_2024 04 15-21 37

### Reproduction Steps

Play until you reach the Lana Lei boss fight.

### Expected Behavior

How it should be:
unknown_2024 04 15-21 40

### PCSX2 Revision

v1.7.5703

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i3-13100F

### GPU

RX 6600XT - v24.3.1

### GS Settings

I was first playing Upscaled to 1080p when I encountered the bug. Switching to Native didn't fix the problem either.

### Emulation Settings

Default.

### GS Window Screenshots

Default.

### LINKED ISSUE #11416: [BUG]: Battlefield 2 – Modern Combat filter fails to render
### Describe the Bug

During the first mission of Battlefield 2 – Modern Combat, there is a blue-ish filter which fails to render over the screen. The filter appears correctly in software mode. See also: #11417 (different issue); same dump.

### Reproduction Steps

Play the first stage of Battlefield 2 – Modern Combat on a hardware renderer.

### Expected Behavior

Filter should appear.

### PCSX2 Revision

v1.7.5906

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

### CPU

Ryzen 7 5800X

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

_No response_

### Logs & Dumps

[Battlefield 2 - Modern Combat_SLUS-21026_20240617165053.zip](https://github.com/user-attachments/files/15877699/Battlefield.2.-.Modern.Combat_SLUS-21026_20240617165053.zip)

### LINKED ISSUE #11417: [BUG]: Battlefield 2 – Modern Combat moonlight shows through buildings
### Describe the Bug

During the first mission of Battlefield 2 – Modern Combat, moonlight shows through buildings at certain angles. Jordan and I have attempted to fix this with settings to no avail. See also: #11416 (different issue; same dump).

### Reproduction Steps

Play the first mission of Modern Combat and look at the moon through a building at a certain angle.

### Expected Behavior

The moon should not shine through buildings.

### PCSX2 Revision

v1.7.5906

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

### CPU

Ryzen 7 5800X

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

_No response_

### Logs & Dumps

[Battlefield 2 - Modern Combat_SLUS-21026_20240617165053.zip](https://github.com/user-attachments/files/15877699/Battlefield.2.-.Modern.Combat_SLUS-21026_20240617165053.zip)

### LINKED ISSUE #11870: [BUG]: King Kong Peter Jacksons - Broken Texture shuffle
### Describe the Bug

King Kong Peter Jacksons experiences a broken texture shuffle effect.
Shuffle isn't being picked up from draw 127 to draw 265.

Draw 127 should be picking up RG->BA shuffle.

Extra draw info on 127:
```
m_same_group_texture_shuffle 0, tex_psm.bpp 16, memory psm bpp 16
shuffle_coords 1, rt->m_32_bits_fmt 0, src->m_32_bits_fmt 0, m_copy_16bit_to_target_shuffle 0
draw_sprite_tex 1, m_vt.m_primclass 3, TrianglesAreQuads 1
```
Both the target and source aren't picked up as 32bit, it's picking the wrong targets.
[00127_context.txt](https://github.com/user-attachments/files/17237738/00127_context.txt)
[00127_vertex.txt](https://github.com/user-attachments/files/17237739/00127_vertex.txt)

### Reproduction Steps

Run the gs dump.

### Expected Behavior

Texture shuffle effect is rendered properly.

### PCSX2 Revision

v2.1.181

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 7600

### GPU

GTX 1070

### GS Settings

Default.

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

Rename .zip to .xz
[King_Kong_Peter_Jacksons_-_The_Official_Game_of_the_Movie_SLUS-21311_20230207223726.gs.zip](https://github.com/user-attachments/files/17237743/King_Kong_Peter_Jacksons_-_The_Official_Game_of_the_Movie_SLUS-21311_20230207223726.gs.zip)

### LINKED ISSUE #11965: [BUG]: Split-screen Graphical Bugs For The Second Player in Delta Force: Black Hawk Down with Night Vision
### Describe the Bug

When using night vision on the second player's screen it becomes impossible for the second player to see anything due to a visual bug. Under certain lighting conditions the shadows seen by the second player are also bugged.

### Reproduction Steps

This bug occurs in co-op for the second player when using night vision and at random in the shadows throughout the campaign. This occurs on both Linux and Windows 11 regardless of what renderer is selected.

### Expected Behavior

The visual quality should be identical to the first or top player.

### PCSX2 Revision

v2.1.226

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

AMD 3600

### GPU

NVIDIA 4060 TI

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

what night vision should look like:
Image

what it looks like for the second player:
Image

what the shadow glitch looks like for the second player:
Image
Image

### Logs & Dumps

_No response_

### LINKED ISSUE #12215: [BUG]: The green sage's eyes (iris) are missing in HW mode. Jak and Daxter [SCUS-97124]
### Describe the Bug

Image

### Reproduction Steps

Just play the game and look at Samos' eyes. Here's a dump

[Jak and Daxter - The Precursor Legacy_SCUS-97124_20250118185029.gs.zip](https://github.com/user-attachments/files/18465170/Jak.and.Daxter.-.The.Precursor.Legacy_SCUS-97124_20250118185029.gs.zip)

### Expected Behavior

For his eyes to be present. 

Image

### PCSX2 Revision

v2.3.110

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

AMD Ryzen 7 7800X3D

### GPU

Nvidia RTX 4090

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adds support for render target inside render target draws and shuffles, where games point to an offset inside a previously drawn target, usually to update single pages, or offset half way through a picture.

### Rationale behind Changes
We didn't support this and relied on exact start address matches, and a bunch of games do it.

### Suggested Testing Steps
Test games which had "top left corner" bugs or weird half screen problems.

Known to fix:
Battlefield 2 - Fixes things the CRC hack was chopping out, also required fixing how sources get invalidated
Big Mutha Truckers - No longer requires a CRC hack for half screen shuffle
Call of Duty - World at War - Final Fronts - lighting closer matches software
Conflct Desert Storm - Flickering fixed
Death by Degrees - lighting and fog effects post processing (top left corner) are fixed (CRC can be removed)
Delta Force - Black Hawk Down - Fixes player 2 night vision
Drakengard - Post shuffle effect on death
Driv3r - Doesn't need such a cacophony of fixes, just CSBW 4/2 + Tex in RT, plus fixes the sun glares.
Haunting Ground - Quite possibly no longer needs CRC hack
Hitman Blood Money - Post processing and shadows fixed (still needs CRC for weird corner uploading thing, but may be more fixable these days)
Hitman Contracts - Graphics completely fixed
Ghost in the Shell - Stand Alone Complex - No longer requires CRC hack and fixes channel shuffle
Jak X - Combat Racing - Player 2 now visible
Peter Jackson's King Kong- The Official Game of the Movie - pretty much fixed with rt in rt
Manhunt 2 - Post Process (top left corner) lighting fixed
Onimusha - Warlords - fmvs seem to not flicker (game currently uses SW FMV)
Ridge Racer V - Less hacks required, intro can now be upscaled
Sniper Elite - Second player lighting overlay fixed
Stolen - All graphics processing is fixed, lighting, etc. Speed is also not terrible
Spiderwick Chronicles - Half screen problem in book fixed
Suikoden III - Half screen black and white effect fixed
SWAT - Global Strike Team - Player 2 colours corrected
Taiko no Tatsujin Bang Tap - Lighting overlay (top left corner) fixed
Tekken 5 - Fire effect can now be used upscaled and half screen fire effect problem is fixed
TOCA Race Driver 2 - shadows fixed
Time Crisis 3 - Post processing looks correct now
Tomb Raider - Legends - Fixes for post lighting effects not covering the screen in some levels and goggles
Urban Reign - Post bloom/blur effect
Wild Arms 5 - No longer requires Framebuffer Conversion hack ,meaning sepia scenes now upscale properly
Wrath Unleashed - Fixes colours
WRC 3 - Half screen fog effect fixed.

Improves but doesn't currently fix:
Pachipara
Raw Danger
Steambot Chronicles

All the above games will likely need a further CRC to fix the remaining issues due to a weird shuffle and manual deswizzling of depth.

Note: This is gated behind Tex in RT and will break some games if left on, be it on your own head!

Fixes #11417 - Battlefield 2
Fixes #11416 - Battlefield 2
Fixes #8869 - Battlefield 2
Fixes #11085 - Death by Degrees
Fixes #3855 - Drakengard
Fixes #10399 - Hitman - Contracts
Fixes #4251 - Hitman - Blood Money
Fixes #12215 - Jak green sage's eyes
Fixes #4964 - Jak X - Combat Racing
Fixes #11870 - King Kong
Fixes #10164 - Manhunt 2
Fixes #8574 - Ridge Racer V coloured light problem
Fixes #8328 - Stolen
Fixes #3849 - Suikoden 3
Fixes #10471 - SWAT Global Strike Team
Fixes #8995 - Tekken 5
Fixes #7942 - Time Crisis 3
Fixes #913 - TOCA Race Driver 2
Fixes #267 - Wrath Unleashed
Fixes #10982 - WRC 3
Fixes #9888 - Conflict Desert Storm
Fixes #11965 - Delta Force - Black Hawk Down
Fixes #10763 - Urban Reign

### Screenshots

Battlefield 2:
Master:
image
PR:
image

Call of Duty - World at War:
Master:
image
PR:
image

Death by Degrees (in native as the fog doesn't upscale well, even with fixes):
Master:
image
PR:
image
Upscaled on PR just to show:
Edit: This is no longer the case thanks to Align to Native wtih Texture Offsets.
image

Delta Force - Black Hawk Down:
Master:
image
PR:
image

Drakengard:
Master:
image
PR:
image

Hitman - Blood Money:
Master:
image
PR:
image

Hitman - Contracts:
Master:
image
PR:
image

Ghost in the Shell:
Master:
image
PR:
image

Jak and Daxter - The Precursor Legacy:
Master:
image
PR:
image

Jak X - Modern Combat Racing:
Master:
image
PR:
image

Peter Jackson's King Kong:
Master:
image
PR:
image

Manhunt 2:
Master:
image
PR:
image

Ridge Racer V (Intro, to show upscaling now works):
Master:
image
PR:
image

Sniper Elite:
Master:
image
PR:
image

Stolen:
Master (Had to take this twice because it flashes black ever other frame:
image
PR:
image

Spiderwick Chronicles:
Master:
image
PR:
image

Suikoden III:
Master:
image
PR:
image

SWAT - Global Strike Team:
Master:
image
PR:
image

Taiko no Tatsujin Bang Tap (in Native res as it doesn't upscale well):
Master:
image
PR:
image

TOCA Race Driver 2:
Master:
image
PR:
image

TOCA Race Driver 3:
Master:
image
PR:
image

Time Crisis 3 (Native as it doesn't upscale great):
Master:
image
PR:
image

Tomb Raider Legends:
Master:
image
PR:
image

Wild Arms 5 (To show it now upscales):
Master:
image
PR:
image

Wrath Unleashed:
Master:
image
PR:
image

WRC 3 (Fog on the left):
Master:
image
PR:
image

### CODE REVIEW

**Comment by TheTechnician27** [comment]
Fixes #11417.

**Comment by someother1n** [comment]
Fixes https://github.com/PCSX2/pcsx2/issues/1339#issuecomment-1277891875

Master:  
mstr

PR:
PR

**Comment by refractionpcsx2** [comment]
Yes, already got it fixed locally, just not pushed it yet :)

**Comment by refractionpcsx2** [comment]
I think this is now at a point where it can be tested properly.  Man that was a nightmare. Try everything you can, as there was a lot of changes to behaviour to try and compensate for other things working properly now or doing more things than they used to do, so any regressions will need to be dealt with.

**Comment by refractionpcsx2** [comment]
Just added some Tex in RT fixes for behaviour that's used in Ridge Racer V.  Turns out the PR made the lights for the street lamps and cars worse with the new changes, however it never worked in master before, either, but did give rainbow garbage on occasion.

The old version of the PR:
image

Master:
image

PR Now:
image

**Comment by JordanTheToaster** [comment]
Fixes #11965

**Comment by JordanTheToaster** [comment]
Fixes #9888

**Comment by JordanTheToaster** [comment]
Fixes #12215

File: pcsx2/GS/Renderers/HW/GSHwHack.cpp [hunk 1]
```diff
@@ -946,6 +872,10 @@ bool GSHwHack::OI_PointListPalette(GSRendererHW& r, GSTexture* rt, GSTexture* ds
 		&& r.m_cached_ctx.FRAME.FBMSK == 0 // No frame buffer masking.
 	)
 	{
+		int mask = (r.m_vt.m_max.p.xyxy() == r.m_vt.m_min.p.xyxy()).mask();
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSHwHack.cpp:875]: Can be const

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 2]
```diff
@@ -887,6 +950,12 @@ GSVector2i GSRendererHW::GetValidSize(const GSTextureCache::Source* tex)
 	// e.g. Burnout 3, God of War II, etc.
 	int height = std::min<int>(m_context->scissor.in.w, m_r.w);
 
+	// We can check if the next draw is doing the same from the next page, and assume it's a per line clear.
+	// Battlefield 2 does this.
+	int pages = ((GSLocalMemory::GetEndBlockAddress(m_cached_ctx.FRAME.Block(), m_cached_ctx.FRAME.FBW, m_cached_ctx.FRAME.PSM, m_r) + 1) - m_cached_ctx.FRAME.Block()) >> 5;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:955]: This too

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 3]
```diff
@@ -2737,22 +3018,156 @@ void GSRendererHW::Draw()
...
+			int horizontal_offset = ((static_cast<int>((m_cached_ctx.FRAME.Block() - rt->m_TEX0.TBP0)) / 32) % static_cast<int>(std::max(rt->m_TEX0.TBW, 1U))) * frame_psm.pgs.x;
+			// Used to reduce the offset made later in channel shuffles
+			m_target_offset = std::abs(static_cast<int>((m_cached_ctx.FRAME.Block() - rt->m_TEX0.TBP0)) >> 5);
+
+			if (vertical_offset < 0)
+			{
+				rt->m_TEX0.TBP0 = m_cached_ctx.FRAME.Block();
+				GSVector2i new_size = rt->m_unscaled_size;
+				// Make sure to use the original format for the offset.
+				int new_offset = std::abs((vertical_offset / frame_psm.pgs.y) * GSLocalMemory::m_psm[rt->m_TEX0.PSM].pgs.y);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3060]: This also

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 4]
```diff
@@ -2737,22 +3018,156 @@ void GSRendererHW::Draw()
...
+			}
+			// Z isn't offset but RT is, so we need a temp Z to align it, hopefully nothing will ever write to the Z too, right??
+			if (ds && vertical_offset && (m_cached_ctx.ZBUF.Block() - ds->m_TEX0.TBP0) != (m_cached_ctx.FRAME.Block() - rt->m_TEX0.TBP0))
+			{
+				
+				int z_vertical_offset = ((static_cast<int>(m_cached_ctx.ZBUF.Block() - ds->m_TEX0.TBP0) / 32) / std::max(rt->m_TEX0.TBW, 1U)) * GSLocalMemory::m_psm[m_cached_ctx.ZBUF.PSM].pgs.y;
+				int z_offset = vertical_offset;
+				GL_CACHE("RT in RT Z copy on draw %d z_vert_offset %d z_offset %d", s_n, z_vertical_offset, z_offset);
+				GSVector4i dRect = GSVector4i(0, z_offset * ds->m_scale, ds->m_unscaled_size.x * ds->m_scale, std::min(z_offset + m_r.w + 1, z_offset + ds->m_unscaled_size.y) * ds->m_scale);
+				int new_height = std::max(static_cast<int>(ds->m_unscaled_size.y * ds->m_scale), dRect.w);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3096]: Here as well, and the z offsets above.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 5]
```diff
@@ -2737,22 +3018,156 @@ void GSRendererHW::Draw()
...
+			t_size.x = rt->m_unscaled_size.x - horizontal_offset;
+			t_size.y = rt->m_unscaled_size.y - vertical_offset;
+
+			// Don't resize if the BPP don't match.
+			if (frame_psm.bpp == GSLocalMemory::m_psm[rt->m_TEX0.PSM].bpp)
+			{
+				if (m_r.w > rt->m_unscaled_size.y || m_r.z > rt->m_unscaled_size.x)
+				{
+					u32 new_height = std::max(m_r.w, rt->m_unscaled_size.y);
+					u32 new_width = std::max(m_r.z, rt->m_unscaled_size.x);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3152]: These two const as well.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 6]
```diff
@@ -3106,25 +3547,68 @@ void GSRendererHW::Draw()
...
+			{
+				update_rect.y /= 2;
+				update_rect.w /= 2;
+			}
+		}
+		// NFS Undercover does a draw with double width of the actual width 1280x240, which functions the same as doubling the height.
+		// Ignore single page/0 page stuff, that's just gonna get silly
+		else if (buffer_width > 64 && update_rect.z > buffer_width)
+		{
+			float multifactor = static_cast<float>(update_rect.z) / static_cast<float>(buffer_width);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3594]: Here too

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 7]
```diff
@@ -3402,15 +3916,31 @@ void GSRendererHW::Draw()
...
+		
+		if (ds && g_texture_cache->GetTemporaryZ())
+		{
+			if (m_cached_ctx.DepthWrite())
+			{
+				const int vertical_offset = ((static_cast<int>(m_cached_ctx.FRAME.Block() - rt->m_TEX0.TBP0) / 32) / std::max(static_cast<int>(rt->m_TEX0.TBW), 1)) * frame_psm.pgs.y;
+				const int z_vertical_offset = ((static_cast<int>(m_cached_ctx.ZBUF.Block() - ds->m_TEX0.TBP0) / 32) / std::max(rt->m_TEX0.TBW, 1U)) * GSLocalMemory::m_psm[m_cached_ctx.ZBUF.PSM].pgs.y;
+				const int z_offset = vertical_offset;
+				GL_CACHE("RT in RT Z copy back draw %d z_vert_offset %d z_offset %d", s_n, z_vertical_offset, z_offset);
+				GSVector4i dRect = GSVector4i(0, z_vertical_offset * ds->m_scale, ds->m_unscaled_size.x * ds->m_scale, std::min(z_vertical_offset + m_r.w + 1 - vertical_offset, ds->m_unscaled_size.y) * ds->m_scale);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3940]: Here too

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 8]
```diff
@@ -5267,15 +5888,45 @@ __ri void GSRendererHW::HandleTextureHazards(const GSTextureCache::Target* rt, c
...
 		copy_range = src_bounds;
 		copy_size = src_unscaled_size;
+
 		GSVector4i::storel(&copy_dst_offset, copy_range);
+		if (m_channel_shuffle && (tex_diff || frame_diff))
+		{
+
+			u32 page_offset = (m_cached_ctx.TEX0.TBP0 - src_target->m_TEX0.TBP0) >> 5;
+			u32 vertical_offset = (page_offset / src_target->m_TEX0.TBW) * GSLocalMemory::m_psm[src_target->m_TEX0.PSM].pgs.y;
+			u32 horizontal_offset = (page_offset % src_target->m_TEX0.TBW) * GSLocalMemory::m_psm[src_target->m_TEX0.PSM].pgs.x;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:5906]: All 3

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 9]
```diff
@@ -252,6 +253,163 @@ bool GSTextureCache::CanTranslate(u32 bp, u32 bw, u32 spsm, GSVector4i r, u32 db
...
+				const GSVector2i start_page = GSVector2i(page_offset % dst_pgw, page_offset / dst_pgw);
+				int page_count = (in_rect.height() / dst_page_size.y) * src_pgw;
+
+				// Round up to a whole row, it's better than the alternative.
+				// Busin 0 - Wizardry Alternative Neo moves with non even rows.
+				const int horizontal_offset = (page_count % dst_pgw);
+				if (horizontal_offset)
+					page_count += dst_pgw - horizontal_offset;
+
+				int new_height = (page_count / dst_pgw) * dst_page_size.y;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:382]: This too

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 10]
```diff
@@ -3178,40 +3620,50 @@ void GSTextureCache::InvalidateVideoMem(const GSOffset& off, const GSVector4i& r
...
 
-				if (GSUtil::HasSharedBits(bbp, psm, s->m_TEX0.TBP0, s->m_TEX0.PSM))
+				if ((GSUtil::HasSharedBits(psm, s->m_TEX0.PSM) && (end_bp > s->m_TEX0.TBP0 && start_bp < s->UnwrappedEndBlock()) && !s->m_target) ||
+					(GSUtil::HasSharedBits(bp, psm, s->m_from_target_TEX0.TBP0, s->m_TEX0.PSM) && s->m_target))
 				{
 					m_src.RemoveAt(s);
 				}
 			}
+
+			u32 bbp = bp + bw * 0x10;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:3649]: This tiny one as well :p

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 11]
```diff
@@ -3770,7 +4216,7 @@ bool GSTextureCache::Move(u32 SBP, u32 SBW, u32 SPSM, int sx, int sy, u32 DBP, u
 
 		dst = GetExactTarget(DBP, DBW, dpsm_s.depth ? DepthStencil : RenderTarget, DBP);
 	}
-
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:4219]: Tab

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 12]
```diff
@@ -7045,7 +7571,7 @@ std::shared_ptr<GSTextureCache::Palette> GSTextureCache::PaletteMap::LookupPalet
 			{
 				// Palette is unused
 				it = map.erase(it); // Erase element from map
-									// The palette object should now be gone as the shared pointer to the object in the map is deleted
+					// The palette object should now be gone as the shared pointer to the object in the map is deleted
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:7574]: Could remove 1 more tab so it looks pretty

**Review by lightningterror — COMMENTED** [review]
Need to bump shader cache too

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 13]
```diff
@@ -2737,22 +3018,156 @@ void GSRendererHW::Draw()
...
+			// Don't resize if the BPP don't match.
+			if (frame_psm.bpp == GSLocalMemory::m_psm[rt->m_TEX0.PSM].bpp)
+			{
+				if (m_r.w > rt->m_unscaled_size.y || m_r.z > rt->m_unscaled_size.x)
+				{
+					u32 new_height = std::max(m_r.w, rt->m_unscaled_size.y);
+					u32 new_width = std::max(m_r.z, rt->m_unscaled_size.x);
+
+					//DevCon.Warning("Resizing texture %d x %d draw %d", rt->m_unscaled_size.x, new_height, s_n);
+					rt->ResizeTexture(new_height, new_height);
```
[the remark this answers is not in the document]
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3155]: No, because it might only be drawing a couple of pixels.

[the remark this answers is not in the document]
Comment (lightningterror) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3155]: You can remove new_width then since it's not used.

[the remark this answers is not in the document]
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3155]: No, that was a typo, use your brain, LT :P

**Comment by Virtua64** [comment]
@refractionpcsx2  I did notice a minor glitch with the fog effect in WRC3 (demo) in HW mode.  While most areas look good now with this PR,  this appeared in this particular area of the course.  The fog effect appears now but has horizontal lines.  Also occurs at native resolution in HW mode.

SW mode: 
WRC 3  Demo _SCED-52137_sofware


PR (HW mode)
WRC 3  Demo _SCED-52137_20250211045749


GS dump:
[WRC 3 [Demo]_SCED-52137_20250211045749.gs.zip](https://github.com/user-attachments/files/18748307/WRC.3.Demo._SCED-52137_20250211045749.gs.zip)

**Comment by refractionpcsx2** [comment]
aw man, yeah I did see something like that but the other half during getting it working, hopefully it's nothing major...

**Comment by refractionpcsx2** [comment]
There we go, fixed.  Z regions for Tex in RT were completely broken, so that was cool :P 
image

**Comment by Virtua64** [comment]
@refractionpcsx2  Just a nitpick here, but maybe something you want to look at before the merge. Testing the most recent commit,  in RRV with HW mode, depending on the location and vicinity of the light, it still sometimes will briefly show that coloured light instead.

SW mode:
Ridge Racer V_SLUS-20002_20250221023728

HW mode:
Ridge Racer V_SLUS-20002_20250221023717


video:

https://github.com/user-attachments/assets/2a3fe80b-ce94-4f29-89a7-6a2abfa5bdce



GS dump:
[Ridge Racer V_SLUS-20002_20250221001301.gs.zip](https://github.com/user-attachments/files/18904776/Ridge.Racer.V_SLUS-20002_20250221001301.gs.zip)

**Comment by refractionpcsx2** [comment]
aw man, alright, I guess I'll look at it, thanks for the GS dump

**Comment by refractionpcsx2** [comment]
You sure this ever worked on this PR? I tried an old build from a couple of weeks ago and it was still broken then...

**Comment by Virtua64** [comment]
No, it never did work on this PR from what I tested.  Sorry, I just meant I noticed it today using the newest commit...

**Comment by refractionpcsx2** [comment]
Okay I've found the cause, working on a fix right now.

**Comment by refractionpcsx2** [comment]
Ridge Racer V should be fine now, it was just an edge case when the lights were on the edge of the screen.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 14]
```diff
@@ -1854,7 +2117,23 @@ GSTextureCache::Target* GSTextureCache::LookupTarget(GIFRegTEX0 TEX0, const GSVe
 						can_use = !t->m_dirty.GetTotalRect(TEX0, size).rintersect(size_rect).eq(size_rect);
 					}
 				}
+				else if (type == RenderTarget && (fbmask == 0xffffff && !t->m_was_dst_matched && TEX0.TBW != t->m_TEX0.TBW))
+				{
+					// When returning to being matched with the Z buffer in width, we need to make sure the RGB is up to date as it could get used later (Hitman Contracts).
+					auto& rev_list = m_dst[1 - type];
+					Target* dst_match = nullptr;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2124]: Not used.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 15]
```diff
@@ -2774,62 +3094,244 @@ void GSRendererHW::Draw()
...
+				}
+
+				rt->m_valid.y += new_offset;
+				rt->m_valid.w += new_offset;
+				rt->m_drawn_since_read.y += new_offset;
+				rt->m_drawn_since_read.w += new_offset;
+
+				if (rt->m_dirty.size())
+				{
+					for (int i = 0; i < rt->m_dirty.size(); i++)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3160]: Should change the int to size_t, -Wsign-compare warning.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 16]
```diff
@@ -2774,62 +3094,244 @@ void GSRendererHW::Draw()
...
+			{
+				// Z isn't offset but RT is, so we need a temp Z to align it, hopefully nothing will ever write to the Z too, right??
+				if (ds && vertical_offset && (m_cached_ctx.ZBUF.Block() - ds->m_TEX0.TBP0) != (m_cached_ctx.FRAME.Block() - rt->m_TEX0.TBP0))
+				{
+					const int z_vertical_offset = ((static_cast<int>(m_cached_ctx.ZBUF.Block() - ds->m_TEX0.TBP0) / 32) / std::max(rt->m_TEX0.TBW, 1U)) * GSLocalMemory::m_psm[m_cached_ctx.ZBUF.PSM].pgs.y;
+					if (g_texture_cache->GetTemporaryZ() != nullptr)
+					{
+						GSTextureCache::TempZAddress z_address_info = g_texture_cache->GetTemporaryZInfo();
+
+						if (ds->m_TEX0.TBP0 != z_address_info.ZBP || z_address_info.offset != (vertical_offset - z_vertical_offset))
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3189]: Complaining for these ones too `z_address_info.offset != (vertical_offset - z_vertical_offset)` u32 vs int.

**Review by lightningterror — COMMENTED** [review]
Need to bump shader cache too.

**Comment by refractionpcsx2** [comment]
sadge :( I'll look at it at some point, I'm kinda burnt out on this right now due to having to repeatedly fight with it. I'll wait for more testing so I can just fix a bunch of problems in one go (if more show up).

**Comment by seta-san** [comment]
Refraction, you’ve done a great job.

File: pcsx2/GS/Renderers/HW/GSTextureCache.h [hunk 17]
```diff
@@ -551,6 +559,12 @@ class GSTextureCache
 
 	/// Invalidates a temporary source, a partial copy only created from the current RT/DS for the current draw.
 	void InvalidateTemporarySource();
+	void SetTemporaryZ(GSTexture* temp_z);
+	GSTexture* GetTemporaryZ();
+	TempZAddress GetTemporaryZInfo();
+	void SetTemporaryZInfo(u32 address, u32 offset);
+	/// Invalidates a temporary Z, a partial copy only created from the current DS for the current draw when Z is not offset but RT is
```
Comment (JordanTheToaster) [inline pcsx2/GS/Renderers/HW/GSTextureCache.h:566]: Missing full stop.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 18]
```diff
@@ -2817,105 +3051,417 @@ void GSRendererHW::Draw()
...
+							update_valid.y += GSLocalMemory::m_psm[m_cached_ctx.FRAME.PSM].pgs.y;
+							update_valid.w += GSLocalMemory::m_psm[m_cached_ctx.FRAME.PSM].pgs.y;
+							rt->UpdateValidity(update_valid, true);
+						}
+					}
+				}
 			}
 		}
-
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3404]: Whitespace.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 19]
```diff
@@ -2326,7 +2816,7 @@ GSTextureCache::Target* GSTextureCache::LookupTarget(GIFRegTEX0 TEX0, const GSVe
 			}
 		}
 	}
-
+
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2819]: Here too.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 20]
```diff
@@ -2766,8 +3349,24 @@ GSTextureCache::Target* GSTextureCache::LookupDisplayTarget(GIFRegTEX0 TEX0, con
...
 					iter = std::vector<GSState::GSUploadQueue>::reverse_iterator(GSRendererHW::GetInstance()->m_draw_transfers.erase(iter.base() - 1));
 				}
-				else
-					++iter;
+				// Double buffers, usually FMV's, if checking for the upper buffer, creating another target could mess things up.
+				else if (GSLocalMemory::GetStartBlockAddress(iter->blit.DBP, iter->blit.DBW, iter->blit.DPSM, iter->rect) <= TEX0.TBP0 && transfer_end >= rect_end && iter->rect.width() == size.x)
+				{
+					GSTextureCache::Target* tgt = g_texture_cache->GetExactTarget(iter->blit.DBP, iter->blit.DBW, GSTextureCache::RenderTarget, iter->blit.DBP + 1);
+
+					if(tgt) // Make this target bigger.
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:3357]: Space after if.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 21]
```diff
@@ -6384,6 +7121,22 @@ void GSTextureCache::Target::Update(bool cannot_scale)
...
+
+	if (m_type == DepthStencil && g_texture_cache->GetTemporaryZ() != nullptr)
+	{
+		if (g_texture_cache->GetTemporaryZInfo().ZBP == m_TEX0.TBP0)
+		{
+			GSTextureCache::TempZAddress z_address_info = g_texture_cache->GetTemporaryZInfo();
+			if (m_TEX0.TBP0 == z_address_info.ZBP)
+			{
+				//GL_CACHE("RT in RT Updating Z copy on draw %d z_offset %d", s_n, z_address_info.offset);
+				GSVector4i dRect = GSVector4i(total_rect.x * m_scale, (z_address_info.offset + total_rect.y) * m_scale, (total_rect.z + (1.0f / m_scale)) * m_scale, (z_address_info.offset + total_rect.w + (1.0f / m_scale)) * m_scale);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:7133]: Const.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 22]
```diff
@@ -6384,6 +7121,22 @@ void GSTextureCache::Target::Update(bool cannot_scale)
 		m_alpha_range |= alpha_minmax.first != alpha_minmax.second;
 	}
 	g_gs_device->Recycle(t);
+
+	if (m_type == DepthStencil && g_texture_cache->GetTemporaryZ() != nullptr)
+	{
+		if (g_texture_cache->GetTemporaryZInfo().ZBP == m_TEX0.TBP0)
+		{
+			GSTextureCache::TempZAddress z_address_info = g_texture_cache->GetTemporaryZInfo();
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:7129]: This too.

File: pcsx2/GS/Renderers/HW/GSTextureCache.cpp [hunk 23]
```diff
@@ -6553,12 +7313,18 @@ bool GSTextureCache::Target::ResizeTexture(int new_unscaled_width, int new_unsca
 		g_gs_device->InvalidateRenderTarget(tex);
 	}
 
-	g_texture_cache->m_target_memory_usage = (g_texture_cache->m_target_memory_usage - m_texture->GetMemUsage()) + tex->GetMemUsage();
 
-	if (recycle_old)
-		g_gs_device->Recycle(m_texture);
+	if (!keep_old)
+	{
+		g_texture_cache->m_target_memory_usage =  (g_texture_cache->m_target_memory_usage - m_texture->GetMemUsage()) + tex->GetMemUsage();
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSTextureCache.cpp:7319]: One space less after =

**Review by lightningterror — COMMENTED** [review]
Some compiler warnings need to be resolved as well

https://github.com/PCSX2/pcsx2/actions/runs/13886790325/job/38852568366?pr=11461#step:13:715

**Comment by IamLupo** [comment]
I compiled and tested this branch. And there is something wrong in battlefield 2.

It looks like the "Hardware fixes -> skip draw range -> 0, 3" doesn't have to be set anymore. But when i jump out of a car the frame start flickering really heavily. Like there is still a edge case that this goes wrong.

Enabling "Hardware fixes -> skip draw range -> 0, 3" fixes the case again.

**Comment by refractionpcsx2** [comment]
aw man, really? Can you get a GS Dump as you get out of the car and it starts going crazy? Then I can look in to it. Thanks

**Comment by IamLupo** [comment]
> aw man, really? Can you get a GS Dump as you get out of the car and it starts going crazy? Then I can look in to it. Thanks

Oke, i did something stupid it looks like. When i tested it i used software mode first. Then i went online and realized i didn't use hardware mode. Then i changed to hardware mode and this caused that it worked. After it looks like the buggy flickering caused this.

Now i try a second time in hardware mode from the start, I cant reporduce this bug anymore. Like i am sorry i give you the wrong feedback. I didn't tested it correctly.

One little thing i notice in this branch is that i have the enable "Game Fixes" > "Use Software Renderer For FMVs" again. Earlier version i didn't had to do that anymore.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 24]
```diff
@@ -1019,12 +1103,14 @@ GSVector2i GSRendererHW::GetValidSize(const GSTextureCache::Source* tex)
 		if (tex_width_pgs == half_draw_width_pgs)
 		{
 			GL_CACHE("Halving width due to texture shuffle with double width, %dx%d -> %dx%d", width, height, width / 2, height);
-			width /= 2;
+			int src_width = tex ? (tex->m_from_target ? tex->m_from_target->m_valid.width() : tex->GetUnscaledWidth()) : (width / 2);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:1106]: Can be const.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 25]
```diff
@@ -1019,12 +1103,14 @@ GSVector2i GSRendererHW::GetValidSize(const GSTextureCache::Source* tex)
...
+			width = std::min(width / 2, src_width);
 		}
 		else
 		{
 			GL_CACHE("Halving height due to texture shuffle, %dx%d -> %dx%d", width, height, width, height / 2);
-			height /= 2;
+			int src_height = tex ? (tex->m_from_target ? tex->m_from_target->m_valid.height() : tex->GetUnscaledHeight()) : (height / 2);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:1112]: This too.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 26]
```diff
@@ -2118,25 +2242,95 @@ void GSRendererHW::Draw()
...
+						m_conf.scissor.z = std::min(m_conf.scissor.z, static_cast<int>((m_channel_shuffle_width * 64) * m_conf.cb_ps.ScaleFactor.z));
+				}
+				
+				m_last_rt->UpdateValidity(valid_area);
+
+				g_gs_device->RenderHW(m_conf);
+
+				if (GSConfig.DumpGSData)
+				{
+					std::string s;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2299]: You can move this lower.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 27]
```diff
@@ -4181,17 +4960,97 @@ __ri bool GSRendererHW::EmulateChannelShuffle(GSTextureCache::Target* src, bool
...
+
+		s[0].U = m_r.x << 4;
+		s[1].U = m_r.z << 4;
+		s[0].V = m_r.y << 4;
+		s[1].V = m_r.w << 4;
+		m_last_channel_shuffle_fbmsk = 0xFFFFFFFF;
 
-	m_r = GSVector4i(0, 0, 1024, 1024);
+		// If we're doing per page copying, then set the valid 1 frame ahead if we're continuing, as this will save the target lookup making a new target for the new row.
+		u32 frame_offset = m_cached_ctx.FRAME.Block() + (IsPageCopy() ? 0x20 : 0);
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:5031]: Const as well.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 28]
```diff
@@ -2817,29 +3055,143 @@ void GSRendererHW::Draw()
 
 	GSTextureCache::Target* rt = nullptr;
 	GIFRegTEX0 FRAME_TEX0;
+	const GSLocalMemory::psm_t& frame_psm = GSLocalMemory::m_psm[m_cached_ctx.FRAME.PSM];
+
+	m_in_target_draw = false;
+	m_target_offset = 0;
+
+	GSTextureCache::Target* ds = nullptr;
+	GIFRegTEX0 ZBUF_TEX0;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:3064]: Maybe also set it to 0?

File: pcsx2/GS/GSState.cpp [hunk 29]
```diff
@@ -3051,6 +3141,46 @@ bool GSState::SpriteDrawWithoutGaps()
...
+			const int dpY = v[i + 1].XYZ.Y - v[i].XYZ.Y;
+			
+			if (first_dpY != dpY)
+				return false;
+
+			const int newYStart = std::min(v[i + 1].XYZ.Y, v[i].XYZ.Y);
+			const int newXEdge = std::max(v[i + 1].XYZ.X, v[i].XYZ.X);
+			if (lastYEdge != newYStart)
+			{
+				if (newYStart != m_context->XYOFFSET.OFY)
```
Comment (lightningterror) [inline pcsx2/GS/GSState.cpp:3160]: Need to cast one of them, -Wsign-compare warning.

**Review by kamfretoz — APPROVED** [review]

**Comment by terremoth** [comment]
Absolute awesome work! Congrats and thanks!

**Comment by IamLupo** [comment]
This fixed the flashbang issue for Battlefield 2: Modern combat

Thanks!

pcsx2-v2.3.275-windows-x64-Qt:
  - fixed: flashbang

pcsx2-v2.3.274-windows-x64-Qt:
  - not fixed: flashbang
