### PR TITLE
GameDB/OSD/CI: Various fixes / Use pip install YAMLint

### LINKED ISSUE #13473: [BUG]: Next Generation Tennis [PAL] loading screen doesn't render properly in OpenGL/Vulkan
### Describe the Bug

The background and text fail to display properly in OpenGL/Vulkan.

Renderer set to Automatic<br>
Render set to Automatic (same results if I manually choose Vulkan or OpenGL)
<br><br>

Renderer set to Software<br>
Renderer set to Software
<br><br>

### Reproduction Steps

1. Run the game
2. Start a match
3. Pause the game using the [START] button

### Expected Behavior

I expected the overlay not to break the rendering completely.

### PCSX2 Revision

PCSX2 v2.4.0 (Flathub)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Fedora 42 Workstation

### CPU

24 × AMD Ryzen 9 7900X 12-Core Processor

### GPU

Nvidia GeForce RTX 4070 Ti

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[GameOverlayBug.zip](https://github.com/user-attachments/files/23281066/GameOverlayBug.zip)
It's very annoying, but I had to wrap it in a ZIP as GH doesn't like `.zst` files

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Fixes more games than I can honestly remember renames some stats in the OSD and uses the latest version of YAMLlint using pip install to speed up the GameDB CI job by around 50 seconds.

Fixes #13473 

### Rationale behind Changes
Broken game bad more readable OSD good faster CI good.

### Suggested Testing Steps
Make sure the CI passes and the new names for the OSD are acceptable.

### Did you use AI to help find, test, or implement this issue or feature?
No

### CODE REVIEW

File: pcsx2/GS/GS.cpp [hunk 1]
```diff
@@ -678,7 +678,7 @@ void GSgetStats(SmallStringBase& info)
 			prefix = 'K';
 		}
 
-		info.format("{} SW | {} SP | {} P | {} D | {:.2f} S | {:.2f} U | {:.2f} {}pps",
+		info.format("{} SW | {} SYNC | {} POLY | {} DRW | {:.2f} SWIZ | {:.2f} UNSWIZ | {:.2f} {}pps",
```
Comment (TheTechnician27) [inline pcsx2/GS/GS.cpp]: I think it's worth calling this a `SYNP` or `SYNPT` instead of `SYNC` based on the variable name, although someone like @refractionpcsx2 would know better. (For context, `SYN` is a common abbreviation of "sync" used in CS, especially in networking.) I also can't remember why you said it's called `POLY` in SW but `PRIM` in HW when they're both referencing `GSPerfMon::Prim`.

**Review by Mrlinkwii — APPROVED** [review]
looks good , would reccmend updating the website documentation when this is merged

File: bin/resources/GameIndex.yaml [hunk 2]
```diff
@@ -17845,7 +17890,7 @@ SLES-51434:
   gameFixes:
     - SoftwareRendererFMVHack # Fixes blackscreen when FMV.
   gsHWFixes:
-    recommendedBlendingLevel: 4 # Fixes menu transparancy effects and text.
+    minimumBlendingLevel: 4 # Fixes brightness menu transparancy effects and text.
```
Comment (lightningterror) [inline bin/resources/GameIndex.yaml:17893]: What's the performance impact, how many barriers/copies?

Comment (JordanTheToaster) [reply bin/resources/GameIndex.yaml:17893]: Goes from 0-4 barriers to 90-110 barriers.

File: bin/resources/GameIndex.yaml [hunk 3]
```diff
@@ -47758,7 +47941,10 @@ SLPM-66168:
   gameFixes:
     - EETimingHack # Fixes flickering.
   gsHWFixes:
+    minimumBlendingLevel: 2 # Improves brightness and banding.
```
Comment (lightningterror) [inline bin/resources/GameIndex.yaml:47944]: And this one?

Comment (JordanTheToaster) [reply bin/resources/GameIndex.yaml:47944]: 3-5 barriers to 23-30 barriers.
