### PR TITLE
GS/HW: Handle split shuffles with a width of 1

### LINKED ISSUE #2942: Need for Speed Hot Pursuit 2 "busted" screens are broken in HW mode
***PCSX2 version:***
v1.5.0-dev-3085-gd36d33daa 

***PCSX2 options:***

Default speedhacks etc. None seem to have any effect on this issue.

***Plugins used:***

Current development build of GSdx at time of posting. The problem occurs only in hardware mode, in both the OpenGL and DirectX renderers. None of the options seem to allow for correct rendering of the bugged effect.

***Description of the issue:***

The in-game scenes where you are busted by the police in Hot Pursuit mode do not render correctly. What is supposed to be rendered is a black and white CCTV-like image of the cop pulling you over. However, what actually gets rendered are scenes where the polygon models are visible with some shading, however, no textures are present. Software mode works fine.

gsdx_20190426160701

gsdx_20190426154746

It's probably also worth noting that VRAM usage during these scenes spikes sharply. At 3x IR, usual VRAM usage during the game is about 1.2GB. When a busted scene happens it goes up to ~3.5. 

GS Dumps attached.

[NFSHP2Busted.zip](https://github.com/PCSX2/pcsx2/files/3121818/NFSHP2Busted.zip)

***How to reproduce the issue:***

Play Hot Pursuit mode using a hardware renderer, get busted.

***Last known version to work:***

None, as far as I know. The same happens in 1.4 but with additional problems that have recently been fixed.

***PC specifications:***

i5 3570k, 16GB RAM, Nvidia GTX 1080, Windows 10

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Recreate the rendering rect for a split draw done 1 page at a time.

### Rationale behind Changes
The split shuffle couldn't handle 1 FBW wide splits before, and you ended up with a massive rect like 64x4096, which is obviously wrong.

### Suggested Testing Steps
Try random games as a smoke test, and test Need for Speed Hot Pursuit 2 as well.  Dump runner didn't show any other differences :(

Fixes #2942 NFS HP2 "Busted" screens.

Master:
image
PR:
image

### CODE REVIEW

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 1]
```diff
@@ -2252,7 +2311,7 @@ void GSRendererHW::Draw()
 			GL_INS("WARNING: Possible misdetection of effect, texture shuffle is %s", m_texture_shuffle ? "Enabled" : "Disabled");
 		}
 
-		if (m_texture_shuffle && IsSplitTextureShuffle())
+		if (m_texture_shuffle && IsSplitTextureShuffle(rt ? rt->m_TEX0.TBW : m_cached_ctx.FRAME.FBW))
```
Comment (stenzek) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2314]: I don't think rt should ever be null if texture_shuffle is true?

Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2312]: Probably not, it was more just to save my ass in case of it being null and crashing xD

I can remove the check

**Comment by DragonautMk** [comment]
It's funny that the master looks cool btw

**Comment by refractionpcsx2** [comment]
yeah it's like a silhouette :)

**Comment by refractionpcsx2** [comment]
I just noticed there's a strip down the left hand side which shouldn't be there, I'll fix that

**Review by Mrlinkwii — APPROVED** [review]

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 2]
```diff
@@ -373,7 +373,8 @@ void GSRendererHW::ConvertSpriteTextureShuffle(bool& write_ba, bool& read_ba)
 		// We can't use the draw rect exactly here, because if the target was actually larger
 		// for some reason... unhandled clears, maybe, it won't have been halved correctly.
 		// So, halve it ourselves.
-		const GSVector4i dr = GetSplitTextureShuffleDrawRect();
+		GSVector4i dr = m_r;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:376]: Const.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 3]
```diff
@@ -1902,7 +1919,45 @@ void GSRendererHW::Draw()
...
+		SetNewFRAME(m_split_texture_shuffle_start_FBP << 5, m_context->FRAME.FBW, m_cached_ctx.FRAME.PSM);
+
+		// TEX0 may also be just using single width with offsets also, so let's deal with that.
+		if (m_split_texture_shuffle_pages > 1 && !NextDrawMatchesShuffle())
+		{
+			if (m_context->FRAME.FBW != m_split_texture_shuffle_fbw && m_cached_ctx.TEX0.TBW == 1)
+			{
+				const GSLocalMemory::psm_t& frame_psm = GSLocalMemory::m_psm[m_cached_ctx.FRAME.PSM];
+				const GSLocalMemory::psm_t& tex_psm = GSLocalMemory::m_psm[m_cached_ctx.TEX0.PSM];
+				u32  pages_high = m_split_texture_shuffle_pages_high;
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:1933]: You can move pages_high and frame_psm in the if code block down.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp [hunk 4]
```diff
@@ -2132,7 +2187,9 @@ void GSRendererHW::Draw()
 
 	// Ensure draw rect is clamped to framebuffer size. Necessary for updating valid area.
 	const GSVector4i unclamped_draw_rect = m_r;
-	m_r = m_r.rintersect(t_size_rect);
+	// Don't clamp on shuffle, the height cache may troll us with the REAL height.
+	if(!m_texture_shuffle && m_split_texture_shuffle_pages == 0)
```
Comment (lightningterror) [inline pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2191]: Space after if.

File: pcsx2/GS/Renderers/HW/GSRendererHW.cpp (hunk 3 above)
Comment (refractionpcsx2) [reply pcsx2/GS/Renderers/HW/GSRendererHW.cpp]: just removed it, didn't need it.

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]
