### PR TITLE
QtHost: Fix Unicode command line arguments

### LINKED ISSUE #7054: [BUG]: Qt version use command line cannot start an image with a Chinese character filename
### Describe the Bug

QT version use command line cannot start an image with a Chinese character filename, but it's ok in wxWidgets version.

### Reproduction Steps

use command line:
start pcsx2x64-avx2.exe "伊苏4：太阳的假面.chd"

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.3312

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by CookiePLMonster**
### Description of Changes
Fixes a Windows issue where loading files from an Unicode path would fail when loading via commandline.

Fixes #7054

### Rationale behind Changes
Ęvęryóńę wąńtś thęir Uńićódę pąthś tó wórk.

### Suggested Testing Steps
Put a game ISO/CSO/CHD in a path containing Unicode characters not local to your code page (e.g. include Chinese characters when trying on an European system) and try to load that file from the command line.

### CODE REVIEW

File: pcsx2-qt/QtHost.cpp [hunk 1]
```diff
@@ -1471,7 +1471,7 @@ void QtHost::PrintCommandLineVersion()
 void QtHost::PrintCommandLineHelp(const char* progname)
 {
 	PrintCommandLineVersion();
-	std::fprintf(stderr, "Usage: %s [parameters] [--] [boot filename]\n", progname);
+	fmt::print(stderr, "Usage: {} [parameters] [--] [boot filename]\n", progname);
```
Comment (stenzek) [inline pcsx2-qt/QtHost.cpp:1474]: `#include "fmt/core.h"`

**Review by stenzek — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]
