### PR TITLE
CDVD: Synchronise access from different threads

### LINKED ISSUE #13462: [BUG]: Crash when launching a game through big picture mode while verifying the hash of an ISO file
### Describe the Bug

If you try to launch a game through big picture mode while the hash of a game is being verified, PCSX2 will crash because both the UI thread and the CPU thread are calling non-reentrant CDVD functions that modify the same global state.

### Reproduction Steps

- Go into big picture mode.
- Start verifying the hash of an ISO from the Qt game properties dialog.
- Launch a game through big picture mode.
- PCSX2 will crash.

### Expected Behavior

No crash.

### PCSX2 Revision

v2.5.258

### Operating System

Windows 11

### If Linux - Specify Distro

Linux

### Logs & Dumps

Stack trace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimised out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimised out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimised out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff4c4527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff4c288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555fd0c92 in CrashHandler::CrashSignalHandler (signal=<optimised out>, siginfo=<optimised out>, ctx=0x7fffffffaa00) at /home/thomas/projects/pcsx2/common/CrashHandler.cpp:325
#6  <signal handler called>
#7  ThreadedFileReader::InternalBlockSize (this=0x0) at /home/thomas/projects/pcsx2/pcsx2/CDVD/ThreadedFileReader.h:89
#8  ThreadedFileReader::ReadSync (this=0x0, pBuffer=0x5555593b63b8 <ISOreadSector(unsigned char*, unsigned int, int)::cdbuffer+24>, sector=85690, count=1) at /home/thomas/projects/pcsx2/pcsx2/CDVD/ThreadedFileReader.cpp:294
#9  0x0000555555e4577d in ISOreadSector (tempbuffer=0x555563280280 "\255g(\262\030\027\350_\213V\201\264$\240b\377\370\312\020\247\022\t#\033&\226\215\302@\261\243X\0344\v,r\205\204\004\265Aa%\234", lsn=85690, mode=3) at /home/thomas/projects/pcsx2/pcsx2/CDVD/CDVDisoReader.cpp:332
#10 0x0000555555e3cd2e in DoCDVDreadSector (buffer=buffer@entry=0x555563280280 "\255g(\262\030\027\350_\213V\201\264$\240b\377\370\312\020\247\022\t#\033&\226\215\302@\261\243X\0344\v,r\205\204\004\265Aa%\234", lsn=lsn@entry=85690, mode=mode@entry=3)
    at /home/thomas/projects/pcsx2/pcsx2/CDVD/CDVDcommon.cpp:430
#11 0x0000555555e486f9 in IsoHasher::ComputeTrackHash (this=this@entry=0x7fffffffbdd8, track=..., callback=callback@entry=0x7fffffffbf08) at /home/thomas/projects/pcsx2/pcsx2/CDVD/IsoHasher.cpp:163
#12 0x0000555555e4855b in IsoHasher::ComputeHashes (this=0x7fffffffbdd8, callback=0x7fffffffbf08) at /home/thomas/projects/pcsx2/pcsx2/CDVD/IsoHasher.cpp:131
#13 0x00005555559b7d6a in GameSummaryWidget::onVerifyClicked (this=0x55556326dd40) at /home/thomas/projects/pcsx2/pcsx2-qt/Settings/GameSummaryWidget.cpp:288
#14 0x00007ffff55f49db in void doActivate<false>(QObject*, int, void**) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#15 0x00007ffff6cbe926 in QAbstractButton::clicked(bool) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#16 0x00007ffff6cbeb9e in QAbstractButtonPrivate::emitClicked() () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#17 0x00007ffff6cc03ab in QAbstractButtonPrivate::click() () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#18 0x00007ffff6cc05eb in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#19 0x00007ffff6bf4840 in QWidget::event(QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#20 0x00007ffff6b90d9a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#21 0x00007ffff6b9a225 in QApplication::notify(QObject*, QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#22 0x00007ffff5590938 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#23 0x00007ffff6b98e70 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#24 0x00007ffff6c08263 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#25 0x00007ffff6c0aec0 in QWidgetWindow::event(QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#26 0x00007ffff6b90d9a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Widgets.so.6
#27 0x00007ffff5590938 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#28 0x00007ffff61eea9c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Gui.so.6
#29 0x00007ffff625697c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Gui.so.6
#30 0x00007ffff099cdbe in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /home/thomas/projects/pcsx2/deps/plugins/platforms/../../lib/libQt6XcbQpa.so.6
#31 0x00007ffff45145c5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff4573737 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff4513a63 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff58996c0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#35 0x00007ffff559cfdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#36 0x00007ffff559886a in QCoreApplication::exec() () from /home/thomas/projects/pcsx2/deps/lib/libQt6Core.so.6
#37 0x0000555555906ee2 in main (argc=1, argv=<optimised out>) at /home/thomas/projects/pcsx2/pcsx2-qt/QtHost.cpp:2417
```

### PR DESCRIPTION
**Pull request by chaoticgd**
### Description of Changes
Wrap the CDVD system in a lock so that multiple threads can't access it at the same time.

I've added cdvdLock and cdvdUnlock functions for this purpose. Not the cleanest, but DoCDVDopen usually isn't the first CDVD function a thread calls (if it does at all), so I think this is okay as a temporary measure.

### Rationale behind Changes
Fixes #13462 and some other related issues (e.g. trying to refresh the game list and verifying a game at the same time).

Hopefully this will just be temporary and eventually we can make CDVD not rely on so much global state.

Previously the only attempts to prevent race conditions were some half-hearted if statements. I think this is a better fix than what is currently on #13463 and I want to get this sorted sooner than later.

### Suggested Testing Steps
Test starting/shutting down the VM, refreshing the game list, and verifying the hashes of ISO files, all at the same time and in different orders.

### Did you use AI to help find, test, or implement this issue or feature?
No.

### CODE REVIEW

File: pcsx2/CDVD/IsoHasher.cpp [hunk 1]
```diff
@@ -103,6 +106,12 @@ bool IsoHasher::Open(std::string iso_path, Error* error)
 
 void IsoHasher::Close()
 {
+	if (!m_is_locked)
```
Comment (TheTechnician27) [inline pcsx2/CDVD/IsoHasher.cpp:109]: It's understandable to track a private variable for the lock state since there's no such thing as `try_unlock()` for a normal mutex. However, I'm wondering if it might be more elegant to use a `std::unique_lock` which [has access to](https://cplusplus.com/reference/mutex/unique_lock/) `std::unique_lock:owns_lock()`. This makes it especially easier to avoid undefined behavior if the CDVD lock ever needs to get used elsewhere in the codebase.

I might be missing something, as I'm not as familiar with multithreading in C++ as in other languages.

File: pcsx2/VMManager.cpp [hunk 2]
```diff
@@ -485,7 +485,7 @@ void VMManager::UpdateLoggingSettings(SettingsInterface& si)
 	if (system_console_enabled != Log::IsConsoleOutputEnabled())
 		Log::SetConsoleOutputLevel(system_console_enabled ? level : LOGLEVEL_NONE);
 
-	// Debug console only exists on Windows.
+		// Debug console only exists on Windows.
```
Comment (TellowKrinkle) [inline pcsx2/VMManager.cpp:488]: What happened here?

File: pcsx2/CDVD/IsoHasher.cpp (hunk 1 above)
Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp]: > This makes it especially easier to avoid undefined behavior if the CDVD lock ever needs to get used elsewhere in the codebase.

I'm a bit confused as to what UB that would help avoid and how it would help avoid it.  Could you explain what you mean?

**Review by TellowKrinkle — COMMENTED** [review]
Not crashing is definitely an improvement, but I feel like the proper thing to do would be to make it possible to make multiple instances of our CDVD reading stuff and use them independently.

~~I can understand if you'd rather use this for now and deal with that later though.~~ Missed that you mentioned it in the PR description

File: pcsx2/CDVD/IsoHasher.cpp (hunk 1 above)
Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > This makes it especially easier to avoid undefined behavior if the CDVD lock ever needs to get used elsewhere in the codebase.

I'm a bit confused as to what UB that would help avoid and how it would help avoid it.  Could you explain what you mean?

Comment (TheTechnician27) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > I'm a bit confused as to what UB that would help avoid and how it would help avoid it. Could you explain what you mean?

Well it seems like they're using a `m_is_locked` private variable to keep track of if they currently own the lock in order to not accidentally `unlock()` while they don't own the lock (as doing so is [undefined behavior](https://en.cppreference.com/w/cpp/thread/mutex/unlock)).

Being able to just call `std::unique_lock:owns_lock()` instead of keeping quasi-duplicate state information on a per-class basis seems like it'd make it harder for someone using the CDVD lock elsewhere in the code to screw this up. Obviously not impossible, but it's just one less layer of convolution for something that's inherently dangerous (at what I can't imagine is any performance penalty worth considering, because it's not like we're hitting the lock repeatedly waiting to acquire it).

Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp:109]: To ask another way, how would changing
```cpp
if (!m_is_locked)
    return;
cdvdUnlock();
m_is_locked = false;
```
to
```cpp
if (!m_unique_lock.owns_lock())
    return;
m_unique_lock.unlock();
```
affect users of CDVD other than IsoHasher, or are you proposing something else?

I don't really understand what keeping quasi-duplicate state information on a per-class basis means here, but this change doesn't seem like it would affect that.

Comment (TheTechnician27) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > affect users of CDVD other than IsoHasher, or are you proposing something else?

I'm suggesting that this'll be easier to safely implement in the future if other tools which use the CDVD also want to use the mutex. "Decoupled" would've been a better word choice.

As you presented, it'd be a lot easier for someone to just copy–paste:

```
if (!m_unique_lock.owns_lock())
    return;
m_unique_lock.unlock();
```

to another object rather than having to set up a private variable and maintain that separate from unlocking (locking is basically coupled thanks to `cdvdLock()`). So it's not about what IsoHasher is doing – this current code is fine and safe and works. Just that if we have other tools like IsoHasher it in the future that also grab CDVD, it could be nicer for them not to have to do this, and it seems like an implementation using `unique_lock` has no actual drawbacks.

It could be the case by then as you and chaotic suggest that we can just spawn multiple CDVDs, so it's probably fine not to look that far ahead and just leave it be.

Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > As you presented, it'd be a lot easier for someone to just copy–paste \[code] to another object rather than having to set up a private variable

But they still have to set up a private variable.  `m_unique_lock` is a private variable that they now have to set up.  Unless you were planning on that being a global `g_unique_lock`, in which case that would just be broken.

File: pcsx2/VMManager.cpp (hunk 2 above)
Comment (chaoticgd) [reply pcsx2/VMManager.cpp:488]: I think clang-format did that.

File: pcsx2/CDVD/IsoHasher.cpp (hunk 1 above)
Comment (chaoticgd) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > This makes it especially easier to avoid undefined behavior if the CDVD lock ever needs to get used elsewhere in the codebase.

~~It kinda sounds like you're mixing up std::unique_lock and std::mutex.~~ No, I was misreading. I assume you probably just mean if unlock accidentally never gets called.

Returning a std::unique_lock does make more sense than a bool now I think about it, I'll refactor the PR.

Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > Returning a std::unique_lock does make more sense than a bool now I think about it, I'll refactor the PR.

Might make the VMManager section a bit difficult

Comment (chaoticgd) [reply pcsx2/CDVD/IsoHasher.cpp:109]: Pushed a std::unique_lock version. The VMManager has an extra static variable now, but I don't think it's too bad. The other call sites are a bit simpler. I can revert it if you disagree.

**Comment by chaoticgd** [comment]
There's an issue where if you try to launch a game from big picture multiple times it will open multiple message boxes stacked on top of each other. I've thought about this and decided I would like to wait for a future PR to address this properly, instead of just adding a hack for this one case.

File: pcsx2/CDVD/IsoHasher.cpp (hunk 1 above)
Comment (TellowKrinkle) [reply pcsx2/CDVD/IsoHasher.cpp:109]: I feel like it would work better with the original interface and a separate class that handles RAII for places where it works

Not a huge fan of the static unique_lock

```cpp
class CDVDLock {
    bool locked = false;
public:
    CDVDLock() = default;
    ~CDVDLock() { unlock(); }
    bool tryLock(Error* err) {
        assert(!locked);
        if (!locked) locked = cdvdLock(err);
        return locked;
    }
    bool unlock() {
        if (locked) {
            locked = false;
            cdvdUnlock();
            return true;
        }
        return false;
    }
};
```

Comment (chaoticgd) [reply pcsx2/CDVD/IsoHasher.cpp:109]: > I feel like it would work better with the original interface and a separate class that handles RAII for places where it works
> 
> Not a huge fan of the static unique_lock

Alright, I've reverted it. I don't think it's worth it making a whole extra class just for two call sites. Especially since if you didn't also implement the move constructor and assignment operator and such it would be buggy. But this comment made me realise the IsoHasher class also has this problem, so I've fixed that now.

Comment (chaoticgd) [reply pcsx2/CDVD/IsoHasher.cpp:109]: Whoops, just pushed again because I forgot to actually commit the copy constructor/assignment operator deleter.

File: pcsx2-qt/Settings/GameSummaryWidget.cpp [hunk 3]
```diff
@@ -195,6 +195,7 @@ void GameSummaryWidget::populateTrackList(const GameList::Entry* entry)
 		return;
 	}
 
+
```
Comment (F0bes) [inline pcsx2-qt/Settings/GameSummaryWidget.cpp]: Extra line

**Review by JordanTheToaster — APPROVED** [review]
Tested the checklist on standard and BPM using games on device and using an external DVD drive everything seems fine.

File: pcsx2-qt/Settings/GameSummaryWidget.cpp (hunk 3 above)
Comment (chaoticgd) [reply pcsx2-qt/Settings/GameSummaryWidget.cpp]: Fixed.

**Review by F0bes — APPROVED** [review]
